### ISSUE TITLE
Add total_limbo_balance to "Closing" sum on channels page

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#1007]
We should add `total_limbo_balance` it to the Closing sum at the top of the channel page on desktop: https://api.lightning.community/#pendingchannels

**Comment by valentinewallace** [comment]
@tanx Not add, but replace maybe? There is overlap between `total_limbo_balance` and the `local_balance` for each pending channel, which is what we currently sum for the Closing sum.

**Comment by tanx** [comment]
> @tanx Not add, but replace maybe? There is overlap between `total_limbo_balance` and the `local_balance` for each pending channel, which is what we currently sum for the Closing sum.

@Roasbeef does `total_limbo_balance` include the balance from `pending-open` channels and non force closed channels? If so, we need to remove `pendingBalanceSatoshis` from the total, otherwise it would be added twice?  
https://github.com/lightninglabs/lightning-app/blob/4c586796ca9bf4ee2cbb585178fa81cb252691dd/src/computed/wallet.js#L19-L32

**Comment by tanx** [comment]
@Roasbeef also, why is `total_limbo_balance` not just added to the `ChannelBalance` grpc api call?

https://api.lightning.community/?javascript#channelbalance

**Comment by tanx** [comment]
@valentinewallace confirmed that `total_limbo_balance` includes the pending open balance. This means: `closing = store.limboBalanceSatoshis - store.pendingBalanceSatoshis`.

**Comment by tanx** [comment]
Ok I take that back. `channelBalanceClosingSatoshis` needs to be `limboBalanceSatoshis`
