### ISSUE TITLE
Suggestion change to UI of Lightning app mobile.

### ISSUE THREAD

**Issue by bitcoinuser** [lightninglabs/lightning-app#1015]
Hi,

1- Feedback: I really liked the (% on lightning). 
2- I think the (WALLET) word on main window on top center should be removed and in the same place added a (+ TOP UP) button like the one from Wallet of Satoshi.
3- Where is the QRCODE icon on top left should be the Settings icon. On top right, instead of Settings icon, should be the transaction icon.
4- On bottom center where is the (Transactions), instead of Transactions, could be a LAPPS, so when we click on it, will list the lapps list.

Hope you consider my suggestions, thanks.

![photo4920513383149709386](https://user-images.githubusercontent.com/1178856/54300373-7c598600-459b-11e9-884a-b64330bc610f.jpg)

![photo4920513383149709387](https://user-images.githubusercontent.com/1178856/54300385-81b6d080-459b-11e9-863c-909daea8ad68.jpg)

**Comment by tanx** [comment]
Thanks for the feedback. We'll definitely take it into considering. Gonna close this issue for now.
