### ISSUE TITLE
Show tenths of cents on invoice confirmation page

### ISSUE THREAD

**Issue by bryanvu** [lightninglabs/lightning-app#1023]
### Description

When entering an invoice for Yalls.org, the cost of an article is $0.006, but the App rounds it to $0.01. Would be useful to show tenths of a cent for very small invoices (e.g. < $0.05)

### Steps to reproduce the behavior

Create an invoice to view an article at Yalls.org (current cost is 150 sats, or $0.006)

### Expected behavior

Show the invoice value of $0.006.

### Actual behavior

Shows the invoice value of $0.01

**Comment by tanx** [comment]
> Would be useful to show tenths of a cent for very small invoices (e.g. < $0.05)

@bryanvu good catch. The way Wallet of Satoshi does this is to display `< $0.01` for sub-cent amounts. We should probably do the same.
