### ISSUE TITLE
Cannot perform initial btcd sync

### ISSUE THREAD

**Issue by adiack** [lightninglabs/lightning-app#106]
### Description

I am running Fedora Linux workstation 27, 64 bits. Using btcd from roastbeef fork. 
Sync always fails at a specific block "corruption on data-block (pos=1700981)"
 
`2017-12-10 20:55:40.673 [ERR] SYNC: Failed to process block 00000000000002b6528998757cab7d80ce5b40ff1b32c01d117300d75d76bc9a: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=1700981): checksum mismatch, want=0x278edefa got=0xc17772e6 [file=055731.ldb]
panic: failed to open ldb transaction: leveldb/table: corruption on data-block (pos=1700981): checksum mismatch, want=0x278edefa got=0xc17772e6 [file=055731.ldb]

goroutine 39 [running]:
github.com/roasbeef/btcd/netsync.(*SyncManager).handleBlockMsg(0xc4200b4630, 0xc43e277120)
	/home/adiack/gocode/src/github.com/roasbeef/btcd/netsync/manager.go:584 +0x16a4
github.com/roasbeef/btcd/netsync.(*SyncManager).blockHandler(0xc4200b4630)
	/home/adiack/gocode/src/github.com/roasbeef/btcd/netsync/manager.go:1152 +0x588
created by github.com/roasbeef/btcd/netsync.(*SyncManager).Start
	/home/adiack/gocode/src/github.com/roasbeef/btcd/netsync/manager.go:1374 +0xe5
`
`[adiack@diackca ~]$ btcd -V
btcd version 0.12.0-beta
[adiack@diackca ~]$ lnd -V
lnd version 0.3.0-alpha
`
### Steps to reproduce the behavior
btcd --testnet --txindex --rpcuser=kek --rpcpass=kek

### Expected behavior
Fully synced node.

**Comment by Roasbeef** [comment]
Unfortunately, looks like you hit database corruption :/ 

To proceed, you'll need to delete the prior `btcd` database, and restart the sync from scratch

**Comment by adiack** [comment]
ok thanks it's fine now.
