### ISSUE TITLE
Syncs forever at 99-100% Whats wrong with this?

### ISSUE THREAD

**Issue by Illustratum** [lightninglabs/lightning-app#1096]
### Description

It just syncs syncs syncs syncs and guess what? it syncs

### Steps to reproduce the behavior

Deleted everything over and over ... went in and deleted everything but the wallet file .

Yup still the exact same hours of waiting and then it hits the last block... it just continues .

Says "syncing to chain (block 574209) gets the new block as expected but STILL says it's syncing .. let it run for two days like that.

It's synced but still says Syncing . logs are doing its thing...

Nothing happens.

Stupid bugs .. deposited 125k satoshi and I can see it .

It never shows up in wallet after it "synced" to last block .. but nothing.

Just looks very stupid and sloppy coded.

**Comment by tanx** [comment]
Does restarting the app resolve the issue?

**Comment by Illustratum** [comment]
Lost money restarting.

Moving on to another projects with their sanity intact.
