### ISSUE TITLE
[Feature] Show warning message about alpha

### ISSUE THREAD

**Issue by DaniellMesquita** [lightninglabs/lightning-app#1102]
"This release is primarily targeted at users who want to test spending and sending Lightning payments, as there are still UX challenges to overcome to automatically get inbound capacity for channels. We’re working on integrating our Lightning Loop service to make it easier for users to receive Lightning payments and top off their channels in future releases of the App. In the meantime, users can receive if they have enough inbound capacity e.g. after sending a few payments".
As on: https://blog.lightning.engineering/announcement/2019/04/23/mainnet-app.html

**Comment by tanx** [comment]
You can see alpha in the version in the about dialog

**Comment by DaniellMesquita** [comment]
@tanx 
Shouldn't it haves a label on app title, and its logo on app?
And this alpha label could have this tooltip
