### ISSUE TITLE
migrated from RaspiBlitz to LN Desktop

### ISSUE THREAD

**Issue by vamp111** [lightninglabs/lightning-app#1105]
my RaspiBlitz died, with somewhat 25 active channels

all attempts to recover it so far failed so i have used the 24 words mnemonic code to the LND desktop app.

my onchain funds showed, as well as all the transactions for opening channels with the Raspi
however is there a way i can gain some control on these channels from the Desktop app, since i want to force close them all and start fresh

sorry for the noob question, thanks for not bashing me

**Comment by Roasbeef** [comment]
Which version of RaspiBlitz were you on? Was it running 0.6?

**Comment by vamp111** [comment]
it was Raspiblitz with v1.1 when problems started to ocure , it was running LND 5.2  since my issue was supposed to be resoloved in LND 0.6 (you were the one apointed me to them) https://github.com/lightningnetwork/lnd/issues/2874   i waited to upgrade to Raspi 1.2, after the upgrade LND fails to start completly.

**Comment by Roasbeef** [comment]
Our Static Channel Backups were added in `lnd` v0.6. As a result, if you were on prior versions when it died, then you won't be able to use that new feature. However, if you're able to get it to start up again, then you can close out the channels.
