### ISSUE TITLE
Allow download of complete log file in mobile app

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#1109]
Add a share button on the upper right corner of the CLI/LOGs view header using the react-native `share` api and the react-native-fs `readFile` api.

See: https://facebook.github.io/react-native/docs/share#share

See: https://github.com/itinance/react-native-fs#readfilefilepath-string-encoding-string-promisestring

The log file can be found under: https://github.com/lightninglabs/lightning-app/blob/master/src/action/wallet.js#L304

Button should appear in the upper right of the header:

![image](https://user-images.githubusercontent.com/1374174/61380862-70176980-a8aa-11e9-84d0-29016b27dfce.png)

**Comment by wbobeirne** [comment]
Looking into this a bit, I see that there is also some app-level logging that _doesn't_ go to file, with `src/action/log.js`'s `error` and `info` functions. Simply exporting the log file would leave out those logs, but exporting only what's in `store.logs` would leave out any historical log data that's only in the file. Which do you think is preferable, or do you think there should be some way to do both?

**Comment by tanx** [comment]
I think it would be a good first step to just export lnd's log file. The main issue right now is debugging what's going wrong under the hood. The app level logging we can deal with later.
