### ISSUE TITLE
"No active channels exist"

### ISSUE THREAD

**Issue by fresheneesz** [lightninglabs/lightning-app#111]
### Description

I just downloaded the latest release (0.3.1-alpha) and I think my syncing has failed and stopped. This is on windows 8.1.

### Steps to reproduce the behavior

Open up the Lightning App.

### Expected behavior

It should sync correctly.

### Actual behavior

I get the error "lnd Error: no active channels exist". I noticed that the logs also say `LTND: Version 0.3.0-alpha` which seems wrong to me, since I downloaded version 0.3.1 . I double checked this. I do have version 0.3.0 on my computer, but it has testnet coins in it and doesn't fail to sync. 

### Screenshot and/or logs if applicable

Logs
lnd: 2017-12-17 16:42:11.861 [WRN] LTND: open ../lnd.conf: The system cannot find the file specified. 2017-12-17 16:42:11.861 [INF] LTND: Version 0.3.0-alpha 2017-12-17 16:42:11.862 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0 2017-12-17 16:42:11.873 [INF] LTND: Primary chain is set to: bitcoin 2017-12-17 16:42:11.907 [INF] BTCN: Loaded 1723 addresses from file 'C:\Users\fresheneesz\AppData\Local\Lnd\data\testnet3\bitcoin\peers.json' 2017-12-17 16:42:11.908 [INF] CMGR: DNS discovery failed on seed x49.testnet-seed.bitcoin.jonasschnelli.ch: lookup x49.testnet-seed.bitcoin.jonasschnelli.ch: no such host 2017-12-17 16:42:11.908 [INF] CMGR: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org: no such host 2017-12-17 16:42:11.908 [INF] CMGR: 1 addresses found from DNS seed testnet-seed.bluematt.me 2017-12-17 16:42:11.908 [INF] CMGR: 25 addresses found from DNS seed testnet-seed.bitcoin.schildbach.de
lnd: 2017-12-17 16:42:12.135 [INF] BTCN: New valid peer 165.227.7.29:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)
lnd: 2017-12-17 16:42:12.154 [INF] BTCN: Catching up regular filter headers from 1219000 to 1221000 2017-12-17 16:42:12.154 [INF] BTCN: Catching up extended filter headers from 1219000 to 1221000
lnd: 2017-12-17 16:42:12.156 [INF] BTCN: Syncing to block height 1255235 from peer 165.227.7.29:18333
lnd: 2017-12-17 16:42:12.997 [INF] LNWL: Opened wallet
lnd: 2017-12-17 16:42:11.861 [WRN] LTND: open ../lnd.conf: The system cannot find the file specified. 2017-12-17 16:42:11.861 [INF] LTND: Version 0.3.0-alpha 2017-12-17 16:42:11.862 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0 2017-12-17 16:42:11.873 [INF] LTND: Primary chain is set to: bitcoin 2017-12-17 16:42:11.907 [INF] BTCN: Loaded 1723 addresses from file 'C:\Users\fresheneesz\AppData\Local\Lnd\data\testnet3\bitcoin\peers.json' 2017-12-17 16:42:11.908 [INF] CMGR: DNS discovery failed on seed x49.testnet-seed.bitcoin.jonasschnelli.ch: lookup x49.testnet-seed.bitcoin.jonasschnelli.ch: no such host 2017-12-17 16:42:11.908 [INF] CMGR: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org: no such host 2017-12-17 16:42:11.908 [INF] CMGR: 1 addresses found from DNS seed testnet-seed.bluematt.me 2017-12-17 16:42:11.908 [INF] CMGR: 25 addresses found from DNS seed testnet-seed.bitcoin.schildbach.de
lnd: 2017-12-17 16:42:12.135 [INF] BTCN: New valid peer 165.227.7.29:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)
lnd: 2017-12-17 16:42:12.154 [INF] BTCN: Catching up regular filter headers from 1219000 to 1221000 2017-12-17 16:42:12.154 [INF] BTCN: Catching up extended filter headers from 1219000 to 1221000
lnd: 2017-12-17 16:42:12.156 [INF] BTCN: Syncing to block height 1255235 from peer 165.227.7.29:18333
lnd: 2017-12-17 16:42:12.997 [INF] LNWL: Opened wallet
lnd: 2017-12-17 16:42:14.111 [INF] LNWL: The wallet has been unlocked without a time limit
lnd: 2017-12-17 16:42:14.124 [INF] LTND: LightningWallet opened
lnd: 2017-12-17 16:42:14.135 [INF] LNWL: Started rescan from block 00000000b123c3b298e7e34236fb66f94f9b133335747385fa31c8a9c6756448 (height 1211001) for 90 addresses
lnd: 2017-12-17 16:42:14.135 [INF] LNWL: Catching up block hashes to height 1211002, this might take a while
lnd Error: no active channels exist

**Comment by Roasbeef** [comment]
Between 0.3 and 0.3.1 the on-disk database schema of `lnd` changed in a backwards incompatible manner. To you'll need to close out your old channels using the prior version, then clear out the old data directory, and update to the new version.

**Comment by fresheneesz** [comment]
Hmm, the channels don't seem to be closing. When I try, it says "closing" then switches back to "open". Maybe It'll close properly if I just wait for the next block? I'm getting a lot of logs like this on my old version:

```
lnd: 2017-12-17 17:10:15.478 [INF] RPCS: [listchannels] fetched 5 channels from DB
lnd: 2017-12-17 17:10:17.213 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters 2017-12-17 17:10:17.213 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-12-17 17:10:22.321 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters
lnd: 2017-12-17 17:10:22.321 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-12-17 17:10:25.902 [INF] RPCS: [listchannels] fetched 5 channels from DB
lnd: 2017-12-17 17:10:27.351 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters
lnd: 2017-12-17 17:10:27.351 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-12-17 17:10:32.659 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters 2017-12-17 17:10:32.660 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-12-17 17:10:35.479 [INF] RPCS: [listchannels] fetched 5 channels from DB
lnd: 2017-12-17 17:10:37.692 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters
lnd: 2017-12-17 17:10:37.692 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-12-17 17:10:41.176 [INF] RPCS: [listchannels] fetched 5 channels from DB
lnd: 2017-12-17 17:10:42.955 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters 2017-12-17 17:10:42.955 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-12-17 17:10:47.984 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters 2017-12-17 17:10:47.985 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-12-17 17:10:53.087 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters 2017-12-17 17:10:53.087 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-12-17 17:10:55.483 [INF] RPCS: [listchannels] fetched 5 channels from DB
lnd: 2017-12-17 17:10:58.133 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters 2017-12-17 17:10:58.133 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-12-17 17:11:03.171 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters
lnd: 2017-12-17 17:11:03.171 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-12-17 17:11:08.201 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters
lnd: 2017-12-17 17:11:08.201 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
```

**Comment by Roasbeef** [comment]
Some underlying details of the way neutrino worked changed between those versions. So the new peers won't be able to serve the old node. 

There's an open bug where force closing in the UI doesn't work properly. As a result, you'll need to force close them on the command line.

**Comment by fresheneesz** [comment]
Hmm, what cli do I use to do that? It would be a shame if these testnet bitcoins were lost forever. And when you say "clear out the old data directory" you mean like delete my `C:\Users\fresheneesz\AppData\Local\Lnd` directory?

**Comment by molxyz** [comment]
@fresheneesz you can send your test coins back to where you got them, like your Core wallet or a faucet. On the command line, do: `lncli sendcoins <bitcoin address> <amount of coin in satoshi>`

**Comment by fresheneesz** [comment]
@molxyz where is `lncli`? I have the directory `C:\lightning\lnd\cmd\lncli` but neither `go run main.go` nor `go run commands.go` seems to work.

**Comment by fresheneesz** [comment]
Ok I couldn't figure out how to find `lncli` on windows, so I might just have to ditch these testnet coins : /

**Comment by bryanvu** [comment]
@fresheneesz in order to get lncli, you have to [build lnd](https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md). It doesn't come with the app itself. But it's probably easier to just ditch the testnet coins. That's what they're for. I ditch TBTC almost every day :)

**Comment by fresheneesz** [comment]
@bryanvu Hmm, shouldn't we ship the cli with the app? Why not do that? Should I open an issue for that?

**Comment by bryanvu** [comment]
My thinking is that including the CLI is a bit of a crutch and I don't want us to get into a situation where non-technical users are having to use it. I think we should make the app work properly so that users don't have to use the CLI unless they're doing something very advanced (and able/willing to build lnd). If we rely on telling users to use the CLI, that basically means that the functionality of the app is incomplete (which it definitely still is at this point!)

**Comment by fresheneesz** [comment]
>  I don't want us to get into a situation where non-technical users are having to use it

Well I agree with that goal. Is everything that's accessible through the cli going to make sense to make accessible via a gui? Aren't there special cases where you want to keep it out of the gui but still allow a user to use it if they really need to?

**Comment by bryanvu** [comment]
Basically, my thinking is that for the set of use cases that we expect the App to handle, we should build it such that the user doesn't need to use the CLI. If there are special cases, then those should either be declared out of scope for this app (potentially to be served by other apps), or be fully supported from the GUI.
