### ISSUE TITLE
Android app freezes on welcome screen

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#1115]
### Description

Android app freezes during first startup on welcome screen with the following output to Logcat in Android Studio

```
2019-05-13 16:27:43.656 17004-17057/engineering.lightning.LightningApp E/ExponentNotificationIntentService: java.io.IOException: SERVICE_NOT_AVAILABLE
2019-05-13 16:28:42.464 17004-17024/engineering.lightning.LightningApp E/FirebaseInstanceId: Token retrieval failed: SERVICE_NOT_AVAILABLE
```

### Steps to reproduce the behavior

1. Uninstall the current Android app from your device to start with an empty state
2. Build the current lnd mobile branch for Android
3. Run `npm start` under `lightning-app/mobile`
4. Build and start the app in Android Studio 

### Expected behavior

The app should continue to the generate-wallet/seed-recovery selection screen.

### Actual behavior

The app freezes on the welcome screen.

### Screenshot and/or logs if applicable

![image](https://user-images.githubusercontent.com/1374174/57660589-1fc71700-759c-11e9-935f-3e759d9e9e39.png)

**Comment by halseth** [comment]
Looks like your internet connection was down/timed out?

**Comment by tanx** [comment]
Your're right. It works now.
