### ISSUE TITLE
Use LightContent status bar style on iOS

### ISSUE THREAD

**Issue by cfromknecht** [lightninglabs/lightning-app#1118]
Currently the iOS status bar displays battery, time, bars, etc in a black font since it uses the default status bar style. Given that most of the text in the app is white, it would be great if the status bar was updated to use `UIStatusBarStyleLightContent` to unify the status bar with the rest of the UI :)

**Comment by tanx** [comment]
Nice catch. Looks like the new dropdown caused the regression.

**Comment by tanx** [comment]
@valentinewallace still broken. #1123 should finally fix this issue.

**Comment by cfromknecht** [comment]
Can confirm that this works :D
