### ISSUE TITLE
[android] Build 64-bit version for Play Store

### ISSUE THREAD

**Issue by halseth** [lightninglabs/lightning-app#1125]
From August 1st 2019, the app must include 64-bit binaries in order to be accepted to Google Play: https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html

The current app doesn't seem to have that:

> As the deadline approaches, we wanted to remind you that at least one of your apps* uses native code but does not currently offer a 64-bit variant:		
Lightning: Fast Bitcoin Wallet

**Comment by tanx** [comment]
We just need to change `ndk.abiFilters` to `'armeabi-v7a','arm64-v8a','x86','x86_64'` as specified in https://developer.android.com/distribute/best-practices/develop/64-bit

**Comment by tanx** [comment]
It seems Expo 32 does not support 64 bit APKs yet. These will be fully supported by Expo 34. See: https://blog.expo.io/expo-sdk-v33-0-0-is-now-available-52d1c99dfe4c

**Comment by tanx** [comment]
Seems like many others are having this issue: https://github.com/facebook/react-native/issues/24261

Tested `react-native@0.59.10` but unfortunately the `arm64` APK still crashes on the Moto G7.

**Comment by tanx** [comment]
Also tried to migrate to the new `react-native@0.60.3` but the unimodules are not yet compatible with AndroidX :/

**Comment by tanx** [comment]
New RN issue tracked here https://github.com/facebook/react-native/issues/25494
