### ISSUE TITLE
Multiple usability UI UX issues when restoring a wallet

### ISSUE THREAD

**Issue by marsrobertson** [lightninglabs/lightning-app#1127]
_(no real funds at this BIP39 seed phrase)_ 

<img width="1618" alt="Screenshot_2019-05-25_at_06_56_46" src="https://user-images.githubusercontent.com/44369284/58366880-5b34e000-7ed0-11e9-823a-83c5e0265e45.png">

1. Typing words 3 at a time. Pressing enter. Focus should move to a new field

2. `endless` not on the list?

3. Clicking `<` to go back gets me to the homescreen, without ability to correct words

**Comment by Roasbeef** [comment]
Are you using a seed provided by the wallet? (also it's not bip 39)

**Comment by marsrobertson** [comment]
Not sure.

By default it uses `mainnet`

But I'm cheap bastard, `#stackingsat` decided to run on `testnet`.

Because I have already backed up (screenshot) my backup phrase for `mainnet`, I thought there is no harm reusing it for `testnet`.

-----

Why it is not BIP39? https://en.bitcoin.it/wiki/Seed_phrase

> The English-language wordlist for the BIP39 standard has 2048 words

Is it some gotcha such as Electrum not being BIP39 - http://docs.electrum.org/en/latest/seedphrase.html - and Binance Coin not being ERC20 while on Ethereum chain (mostly yes, some inconsistent event emitting).

**Comment by Roasbeef** [comment]
`lnd` doesn't use bip39. I think you have have a space at the end of "endless" which causes the app to reject it.

**Comment by valentinewallace** [comment]
Thanks for pointing this out, @marsrobertson. Submitted #1129 which should prevent the failed wallet initialization problem.

**Comment by marsrobertson** [comment]
Yeah, it looks like an extra space!

![image](https://user-images.githubusercontent.com/44369284/58629603-d5040980-82d4-11e9-94ec-fcfe8a05b68b.png)

**Comment by tanx** [comment]
This should be resolved in the upcoming `v0.5.2-alpha`
