### ISSUE TITLE
Unable to close channel

### ISSUE THREAD

**Issue by dhueys** [lightninglabs/lightning-app#1128]
Unable to close the channel, what should I do?
![jietu](https://user-images.githubusercontent.com/38090383/58388009-3e70e780-804b-11e9-8ce7-5727a9b9e898.JPG)

**Comment by Roasbeef** [comment]
Looks like it's closing, but was force closed. In this case, you'll need to wait a period of time before the funds are available.

**Comment by tanx** [comment]
Closing this issue for now. @dhueys if the issue persists we can reopen.
