### ISSUE TITLE
'Fee estimation failed' on Payment

### ISSUE THREAD

**Issue by GuusLieben** [lightninglabs/lightning-app#1131]
### Description
When attempting to send a payment to any Bitcoin address, the application throws the error 'Fee estimation failed' without producing additional logging.

### Steps to reproduce the behavior
Select 'Pay', enter Bitcoin address, enter any amount to transfer. Pressing Next shows the error above.

### Expected behavior
Expected to be able to transfer BTC to any given address.

### Screenshot and/or logs if applicable
No additional logs are generated, screenshot :
![image](https://user-images.githubusercontent.com/10957963/58747028-98b3e300-8465-11e9-96a4-7c83b35565d4.png)

**Comment by valentinewallace** [comment]
Could you share the full logs from the console?

**Comment by tanx** [comment]
I've gotten the error as well. Steps to reproduce:
1. disable autopilot in settings
2. close all channels
3. don't wait for closing tx to get confirmed
4. fee estimation fails

**Comment by tanx** [comment]
This is fixed in the current mobile build.
