### ISSUE TITLE
 Lightning payment failed! +  Fee estimation failed!

### ISSUE THREAD

**Issue by vamp111** [lightninglabs/lightning-app#1135]
LND Desktop latest version

initiated an on-chain paymet, got error: fee estimation failed
initiated an off-chain payment, got error: Ln payment failed
logs: https://pastebin.com/iHtD0kPZ

Other funds locked in *waiting close* since 1 month npw
funding txid: 6b64aca2b00826b9028496552bf8bba9bc992d615bb65bc268273f92005bc2f0

**Comment by tanx** [comment]
Duplicate of #1131

**Comment by vamp111** [comment]
got it, thx
