### ISSUE TITLE
Disable automatic channel creation by default - channels should only be created manually

### ISSUE THREAD

**Issue by fresheneesz** [lightninglabs/lightning-app#114]
Given the high-fee environment we're in and likely to remain in until the LN becomes widespread, users need to be able to carefully control their channel creation. This should include

* Controlling the fee explicitly
* Controlling how many bitcoins to commit
* Controlling how many bitcoins you require your channel partner to commit (for receiving)
* Giving users a way to choose a channel from a list, where each channel has important info like their uptime record, transaction fees, etc

Creating X number of channels without the user's explicit OK isn't going to work, especially early on.

**Comment by MidnightLightning** [comment]
The app is creating them automatically? That explains it; I left my client on overnight to sync the chain, and was surprised to find this morning that I had five channels created without me touching it.

Yes, some visual indicator that "automatic channel making is on" would be good to explain to the user what's being seen.

**Comment by ktorn** [comment]
This was also confusing to me at first, and makes testing specific node/route setups impossible.

**Comment by r0zar** [comment]
I think setting up channels should be an opinionated, guided process, but not automatic. I also don't think it should be as fully manual as it is now.

**Comment by fresheneesz** [comment]
@tanx Could you please comment on why you closed this? Was there a commit that went along with this?
