### ISSUE TITLE
Sending a lightning payment does not display spinner until payments success screen

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#1140]
It looks like the app navigates back to the confirmation screen when trying to send a lightning payment, rather than displaying the waiting spinner screen. After a while the app goes from the confirmation screen directly to the payment success screen.

**Comment by valentinewallace** [comment]
Is this on mobile? On desktop I'm seeing the waiting spinner as expected.

**Comment by valentinewallace** [comment]
What platform is this on? I'm unable to repro on iOS or desktop.

**Comment by tanx** [comment]
I think this was a side affect of calling the qr code scanner handler multiple times. Should be resolved with #1148 

Gonna close this for now.
