### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by lucaszanella** [lightninglabs/lightning-app#1146]
After typing the seed, the app crashes on the first sync. Both the mainet and testnet have this problem. I already sent a feedback with the crash in the testnet (several times). I'm on a Moto G6 (32 bits) with Android 9

**Comment by tanx** [comment]
Hey. We pushed an update to Google Play. Can you test if this resolved the issue on your device?

**Comment by lucaszanella** [comment]
There's no update for me right now

-------- Mensagem Original --------
Ativo 7 de jun de 2019 20:41, Tankred Hase escreveu:

**Comment by lucaszanella** [comment]
now the mainet app does not crash but when it loads it freezes on a pink screen forever

**Comment by bitcoinuser** [comment]
Fixed?

**Comment by lucaszanella** [comment]
Yes

-------- Mensagem Original --------
Ativo 10 de jun de 2019 10:15, bitcoinuser escreveu:

**Comment by bitcoinuser** [comment]
So close the issue. Thanks.

**Comment by lucaszanella** [comment]
After today's update the screen is purple again after I put the password
