### ISSUE TITLE
Opening a channel with a certain amount doesn't seem to use the right amount

### ISSUE THREAD

**Issue by fresheneesz** [lightninglabs/lightning-app#115]
### Description
After opening a channel, the "My Balance" for that channel shows a different number than I input.

### Steps to reproduce the behavior
Create a channel with some node address and input 1000 satoshi.

### Expected behavior
The channel (once opened) should show 1000 satoshi under "My Balance"

### Actual behavior
The channel shows 1312 satoshi under "My Balance" for some reason.

**Comment by Roasbeef** [comment]
When opening a channel, some of the funds goes to fees. You should actually be seeing _less_ than you opened the channel with. 

Also 1000 satoshis is also a pretty small channel FWIW, by default the software doesn't even let you make a channel that small.

**Comment by fresheneesz** [comment]
Ah, maybe I meant 10,000 satoshi. In that case, the form for channel creation should allow you to set both a channel balance and a separate fee.

**Comment by ktorn** [comment]
This. Ideally we can set the funding amount for the channel, and pay the fee separately so that the initial channel balance shows the exact amount input on the channel creation dialog.

**Comment by r0zar** [comment]
Should also be form validation/messages on channel opening to go with these requirements.

**Comment by fresheneesz** [comment]
@tanx Could you please comment on why you closed this? Was there a commit that went along with this?
