### ISSUE TITLE
"transaction output is dust"

### ISSUE THREAD

**Issue by fresheneesz** [lightninglabs/lightning-app#116]
### Description
When I try to send 100 satoshi, it tells me "transaction output is dust". I don't know what to do about that. Is it not possible to send 100 satoshi? Looking at the log I pasted, it looks like maybe it thinks I'm trying to make an on-chain transaction. I can't just pay a LN node however much I want to pay them? I have to get a payment request? Seems like the Pay section should recognize LN addresses and handle them appropriately.

### Steps to reproduce the behavior
Attempt to send 100 satoshi to the Lightning address: 025eeb02baf7555a3601b9eb894319bb7db594c9be11e5b5c289938274e1752894

### Expected behavior
Sending should work properly

### Actual behavior
A popup message is generated saying "transaction output is dust"

### Screenshot and/or logs if applicable

lnd: 2017-12-22 15:29:52.995 [INF] RPCS: [sendcoins] addr=025eeb02baf7555a3601b9eb894319bb7db594c9be11e5b5c289938274e1752894, amt=0.000001 BTC, sat/byte=50

**Comment by Roasbeef** [comment]
Sending 100 satoshis on-chain is dust. 

You can't yet pay using _just_ a node's public key.

**Comment by fresheneesz** [comment]
@Roasbeef Should I open a separate issue to track making that possible (paying using just a node's public key)?
