### ISSUE TITLE
Channels screen doesnot show channel as closed after many confirmations

### ISSUE THREAD

**Issue by molxyz** [lightninglabs/lightning-app#1163]
### Description
Running the lightning-app on desktop in testnet.  One of my channels was inactive so I closed it, and now the closing tx has had many confirmations but the `CHANNELS` screen still shows this channel as `Pending Force Closing`, while the log screen keeps showing these messages:
```
[19:13:48.401] [info] lnd: 2019-06-13 19:13:48.401 [INF] UTXN: NurseryReport: building nursery report for channel 2a8ef59e9e31b0157fbb477e5a4cd1e101e370b4820a3149e7c28d88e864dfa7:0

[19:13:50.396] [info] lnd: 2019-06-13 19:13:50.396 [INF] UTXN: NurseryReport: building nursery report for channel 2a8ef59e9e31b0157fbb477e5a4cd1e101e370b4820a3149e7c28d88e864dfa7:0
```
### Screenshot and/or logs if applicable
![image](https://user-images.githubusercontent.com/21127776/59473523-c78c6a80-8e10-11e9-9284-9803c7ef7206.png)

EDIT: Sorry, I had a blonde moment... Of course the `CHANNELS` screen has to say `Pending Force Closing` because it was a force-closing tx and it has to wait for more blocks before it can be closed.  But why does it keep running this message constantly every second?: 
```
[INF] UTXN: NurseryReport: building nursery report for channel 2a8ef59e9e31b0157fbb477e5a4cd1e101e370b4820a3149e7c28d88e864dfa7:0
```

**Comment by molxyz** [comment]
Ok.. so now my tx had enough blocks and the coin went back to wallet. That message `UTXN: NurseryReport: building nursery report for channel` is gone. I am going to close this issue but one last question...  

@Roasbeef is there a plan to reduce this msg spamming in logs in the future?

**Comment by tanx** [comment]
> is there a plan to reduce this msg spamming in logs in the future?

Yes. I believe @wpaulino is already working on this.
