### ISSUE TITLE
Silent failure when attempting to pay to an invalid address

### ISSUE THREAD

**Issue by fresheneesz** [lightninglabs/lightning-app#117]
### Steps to reproduce the behavior
Try paying 100,000 satoshi to (what I thought was a) LN address 025eeb02baf7555a3601b9eb894319bb7db594c9be11e5b5c289938274e1752894

### Expected behavior
It should either send properly or give me an error.

### Actual behavior
Nothing happens immediately (no message or UI change). After about 10 seconds, the form is cleared.

**Comment by Roasbeef** [comment]
That's not an LN address. There are no addresses in Lighting. 

It _should_ properly detect this fact and display an error though.

**Comment by fresheneesz** [comment]
>  There are no addresses in Lighting.

I suppose I meant public key then? In any case, yeah, the lack of an error is the issue.

**Comment by fresheneesz** [comment]
@tanx Could you please comment on why you closed this? Was there a commit that went along with this?
