### ISSUE TITLE
iOS: Creating a new wallet results in a screen with blank seed words

### ISSUE THREAD

**Issue by alexbosworth** [lightninglabs/lightning-app#1174]
### Description

When I try to make a wallet on iOS it results in blank seed words.

### Steps to reproduce the behavior

1. Install Lightning version 0.1.1 (6) on testflight
2. Go to 'generate new seed'
3. See empty seed words where the seed words should be

### Expected behavior

Seed words should appear

### Actual behavior

Seed words don't appear on any of the seed word screens

### Workaround

Killing and restarting the App makes the seed words come back

**Comment by alepop** [comment]
I got the same issue. Step to reproduce:
- Open app
- Click "restore from seed"
- Go back
- Click "generate new seed"

**Comment by valentinewallace** [comment]
I think this issue was resolved by the merge of https://github.com/lightninglabs/lightning-app/pull/1247

**Comment by tanx** [comment]
> I think this issue was resolved by the merge of #1247

Yep
