### ISSUE TITLE
Set non-standard port for lnd on Android to prevent app from crash in case another wallet is open

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#1180]
Set `--nolisten`

**Comment by Roasbeef** [comment]
An alternative solution proposed in: #1184 (basically just disable listening all together). For the testnet vs mainnet app, we can use different RPC ports via these two options: 
```
      --rpclisten=                                            Add an interface/port/socket to listen for RPC connections
      --restlisten=                                           Add an interface/port/socket to listen for REST connections
```

**Comment by mautematico** [comment]
For instance, ligtning-app and @ACINQ/eclair-mobile are unable to run at the same time.

**Comment by tanx** [comment]
thanks @Roasbeef !
