### ISSUE TITLE
Replace pool of autoconnect LN with nodes that commit some satoshi on their end

### ISSUE THREAD

**Issue by fresheneesz** [lightninglabs/lightning-app#119]
I'm having a problem testing sending between this and eclair because none of the nodes I've connected to commit any funds on their end, so I have no way to receive LN transactions on either end, which leaves me stuck not being able to make transactions. We need nodes in there that will commit at least a small amount of funds so its easier to test sending.

**Comment by Roasbeef** [comment]
You can't receive if all the funds in a channel are on your side.

**Comment by fresheneesz** [comment]
@Roasbeef Right, which is why I'm suggesting that the test nodes that this app uses commits some funds on their side as well (since they all seem to commit nothing themselves). I need to purchase something first.
