### ISSUE TITLE
[Android][Alpha] When app tries to sync blocks, app crashes.

### ISSUE THREAD

**Issue by sicksubroutine** [lightninglabs/lightning-app#1205]
### Description

After recording the wallet's seed and creating a pin, the app reaches the block syncing page, after 5 seconds on this page, the app crashes.

### Steps to reproduce the behavior

1. Create a new wallet and record the seed. 
2. Create a pin.
3. When app moves to the next screen, it shows block number at the top of the screen, then crashes.

### Expected behavior

Syncing blocks normally I'd assume.

### Actual behavior

Crashing upon the start of syncing.

**Comment by jrosco** [comment]
Getting the same issue. Happens after blocks have been synced.

**Comment by lobsterpub** [comment]
Same on iOS, shows that it has synced to the latest block, screen goes black for a second and crashes.  This is on a iPhone SE.

**Comment by joernroeder** [comment]
same here

**Comment by Roasbeef** [comment]
Those on Android: do you have another LN wallet installed that listens actively on the default port?

**Comment by sicksubroutine** [comment]
> Those on Android: do you have another LN wallet installed that listens actively on the default port?

I do have several other Lightning wallet apps on my phone, I'm unclear on how to verify if any of them are listening on the default port.

**Comment by jrosco** [comment]
@Roasbeef yes I have breez wallet installed on the same device.

**Comment by Roasbeef** [comment]
#1209 should fix a variant of this issue for those that have other LN apps also running/installed on Android.

**Comment by izzytdi** [comment]
Same issue, no other wallets installed on phone

**Comment by sicksubroutine** [comment]
Can confirm that the new version on Android has corrected this issue.

**Comment by izzytdi** [comment]
Can also confirm that the new version on Android has corrected this issue =]

**Comment by valentinewallace** [comment]
Thanks @sicksubroutine and @izzytdi for the updates :) closing now.
