### ISSUE TITLE
app starts but nothing happens (does not show up

### ISSUE THREAD

**Issue by roberto68** [lightninglabs/lightning-app#121]
I builded the packaged electron app, ` npm start ` webpack is built but the app does not display anywhere, in the browser at ` http://localhost:9997/ ` I have ` Inspectable WebContents ` , that's all I got. Oh and I am getting this msg too ` [error] lnd: either bitcoin.active or litecoin.active must be set to 1 (true) `. Do I have to install lnd separately? it is not mentioned  anywhere in the readme. Btw I've official bitcoind installed. And here is the output of  ` ps -ef | grep lightning ` if it helps someway
` roberto  23954 23946  1 14:33 pts/2    00:00:00 node /home/roberto/lightning-app/apps/desktop/node_modules/.bin/concurrently --kill-others npm run start-electron --  npm run start-webpack -n electron,webpack -p name
roberto  23999 23997  0 14:33 pts/2    00:00:00 node /home/roberto/lightning-app/apps/desktop/node_modules/.bin/cross-env NODE_ENV=development node -r babel-register scripts/dev-server.js
roberto  24000 23996  0 14:33 pts/2    00:00:00 node /home/roberto/lightning-app/apps/desktop/node_modules/.bin/cross-env HOT=1 NODE_ENV=development electron -r babel-register ./main.dev --
roberto  24014 24000  0 14:33 pts/2    00:00:00 node /home/roberto/lightning-app/apps/desktop/node_modules/.bin/electron -r babel-register ./main.dev --
roberto  24025 24014 10 14:33 pts/2    00:00:02 /home/roberto/lightning-app/apps/desktop/node_modules/electron-prebuilt/dist/electron -r babel-register ./main.dev --
roberto  24027 24025  0 14:33 pts/2    00:00:00 /home/roberto/lightning-app/apps/desktop/node_modules/electron-prebuilt/dist/electron --type=zygote --no-sandbox
roberto  24053 24025  0 14:33 pts/2    00:00:00 /home/roberto/lightning-app/apps/desktop/node_modules/electron-prebuilt/dist/electron --type=gpu-process --channel=24025.0.1062047672 --mojo-application-channel-token=F82547CD61E8F040343212D736941C3D --no-sandbox --window -workarounds=5,18,56,70 --gpu-vendor-id=0x10de --gpu-device-id=0x1140 --gpu-driver-vendor --gpu-driver-version --gpu-driver-date --gpu-secondary-vendor-ids=0x8086 --gpu-secondary-device-ids=0x0166 --v8-natives-passed-by-fd --v8-snapshot-passed-by-fd
roberto  24089 23953  0 14:33 pts/3    00:00:00 grep --color=auto lightning
`

**Comment by bryanvu** [comment]
Hi @roberto68, you shouldn't have to build lnd separately. The app should just start. I assume you did npm run setup prior to npm start? Also, for these kinds of setup questions, it's easier to interact via Slack in the #lightning-app channel here: https://lightningcommunity.slack.com/join/shared_invite/MjI4OTg3MzQ4MjI2LTE1MDMxNzM1NTMtNjlmOGYzOTI1Ng

**Comment by roberto68** [comment]
ok thanks, btw the link is no longer active can you invite me again?
