### ISSUE TITLE
Seed generator not random enough?

### ISSUE THREAD

**Issue by timdj** [lightninglabs/lightning-app#1210]
### Description
The seed generator does not seem overly random for the first seed word. I've recreated a new seed and the first word always starts with an a. This could be pure chance but might be worth investigating. Anyone else seeing this behaviour?

See screenshots to get an idea

### Steps to reproduce the behavior
Install app create seed
### Expected behavior
More randomness. Different starting words
### Screenshot and/or logs if applicable
![Screenshot_20190622-204753](https://user-images.githubusercontent.com/524112/59967749-1633b600-952f-11e9-8bc6-f2869ae3320e.jpg)
![Screenshot_20190622-183130](https://user-images.githubusercontent.com/524112/59967750-1633b600-952f-11e9-9bdb-c0b75a60d6c6.jpg)
![Screenshot_20190622-204719](https://user-images.githubusercontent.com/524112/59967751-1633b600-952f-11e9-95f6-b6c3626086d0.jpg)
![Screenshot_20190622-183110](https://user-images.githubusercontent.com/524112/59967752-16cc4c80-952f-11e9-9ddb-aef4fb01e516.jpg)
![Screenshot_20190622-182701](https://user-images.githubusercontent.com/524112/59967753-16cc4c80-952f-11e9-9c36-0986886c5b98.jpg)
![Screenshot_20190622-204241](https://user-images.githubusercontent.com/524112/59967754-16cc4c80-952f-11e9-8ba0-9bd9c29891db.jpg)
![Screenshot_20190622-182855](https://user-images.githubusercontent.com/524112/59967755-1764e300-952f-11e9-82e8-52562ce2a9a5.jpg)
![Screenshot_20190622-182840](https://user-images.githubusercontent.com/524112/59967756-1764e300-952f-11e9-9724-dfdadb6efff9.jpg)
![Screenshot_20190622-182824](https://user-images.githubusercontent.com/524112/59967757-1764e300-952f-11e9-8c2e-9fad5178f68d.jpg)
![Screenshot_20190622-182716](https://user-images.githubusercontent.com/524112/59967758-1764e300-952f-11e9-90a1-2f09f81645ec.jpg)
![Screenshot_20190622-182808](https://user-images.githubusercontent.com/524112/59967759-17fd7980-952f-11e9-81d4-aebc8f2b3ffc.jpg)
![Screenshot_20190622-182753](https://user-images.githubusercontent.com/524112/59967760-17fd7980-952f-11e9-8451-67f1095e2bf5.jpg)

**Comment by Roasbeef** [comment]
The app [uses `lnd`'s seed format](https://github.com/lightningnetwork/lnd/tree/master/aezeed), which uses the first few bytes of the "raw seed" to store metadata like the external version of the seed. Amongst many other improvements this seed format represents, the external version allows a seed to be easily upgraded in the future to modify things like the crypto primitives it uses.

**Comment by cfromknecht** [comment]
@timdj the first word always starts with “a” because the currently employed external version is 0, only the last three bits of the first word are random
