### ISSUE TITLE
Unintended autopilot channel opened, closed channel, now 0 balance. 

### ISSUE THREAD

**Issue by enoughofme** [lightninglabs/lightning-app#1235]
### Description
I setup a wallet on the Lighting Wallet on two days ago. After transferring in some funds autopilot opened a channel with my whole balance. I didn't want a random channel open with my whole balance so I (admittedly) hastily closed the channel. It immediately said closing pending, stayed like that for a couple hours then had a message that there was no response so it was attempting to force close, about 30 minutes later no sign of the channel but also the balance has said 0 ever since. I'm not technical incompetent but I am relatively new to Bitcoin and completely new to Lightning so I honestly don't know how to troubleshoot or investigate this further on my own. Is this normal and I just don't know?

This is the transaction: 511d526a692c521db69e20d98cfa4f7c8eb689136bec19f5cceeb90aa6164b5c

Any help or advice is greatly appreciated.

**Comment by gerfmarquez** [comment]
I had a similar situation and not sure if channels are recoverable but that would be so handy.
I would've expected the pass phrase to recover channels normally.
