### ISSUE TITLE
Error running the app

### ISSUE THREAD

**Issue by iamparkerm** [lightninglabs/lightning-app#124]
### Description
Running the app. .exe produces and error stating Uncaught Exception, failed to load gRPC binary module b/c it's not at the expected directory of Electron-v1.4-win32-x64-unknown. 2 other people in the slack are getting the same error.

### Steps to reproduce the behavior
In windows cmd shell I pulled the github files, 'npm run setup', then 'npm run package-eletron'. The /release folder was created and the lightnin-app.exe is there.

### Expected behavior
I expected I could run the app .exe

### Actual behavior
I get screenshot #1.
As the error suggests I ran 'npm rebuild' and still get the same error.
I then tried to run the app in development mode and 'npm start' and get the error in screen shot #2

### Screenshot and/or logs if applicable
#1 
![image](https://user-images.githubusercontent.com/31193148/34451480-1154b474-ecf5-11e7-9878-617cb788a3a7.png)

#2 
![image](https://user-images.githubusercontent.com/31193148/34451476-f6411a60-ecf4-11e7-8cf2-097d2016ea34.png)

**Comment by champbronc2** [comment]
Curious, does the app launch if you download the binaries from https://github.com/lightninglabs/lightning-app/releases/download/v0.1.4-alpha/Lightning-win32-x64v0.1.4.zip, extract and run "lightning.exe"

I was also getting the 'f' is not recognized, couldn't fix it on my node. Could only run lightning.exe directly.

**Comment by iamparkerm** [comment]
Thanks, yes the app launches from the binaries.
