### ISSUE TITLE
Login loop after password validation

### ISSUE THREAD

**Issue by CandleHater** [lightninglabs/lightning-app#1241]
### Description
After updating the app to the latest release (v0.1.2) on my Android Pixel 2 with the latest stock rom, opening the app and then closing one channel, I can't use the app anymore.

It shows me the pin unlock screen and when I then enter the correct pin, the app loads like usual at first. Then it even displays the current balance for a few milliseconds (see second 10 in video below) and returns me back to the pin unlock screen.

### Steps to reproduce the behavior
I'm not sure if these steps always lead to this result, but what I did was:
- update the app to the latest version
- open it (everything worked well)
- close one inactive (since days) channel
- reopen the app

### Expected behavior
After I enter the correct pin, the app should unlock.

### Actual behavior
It loops me back to the pin unlock screen and I'm not able to use the app anymore.

### Video and logcat output
[screencast.zip](https://github.com/lightninglabs/lightning-app/files/3355704/screencast.zip)
[cat.log](https://github.com/lightninglabs/lightning-app/files/3355728/cat.log)

**Comment by kennylindholm** [comment]
Exactly the same scenario for me too... Unfortunately I had quite a lot (for me) coins there I had sent by mistake, which I now cannot access. Is there any recovery procedures?

**Comment by enoughofme** [comment]
I had this happen after I closed a channel too. But I was since able to reinstall, and got an update, after that was able to restore with seed and pin works again. Now I'm just hoping my funds eventually come back from the closed channel. I hope all the Bitcoin doesn't get burned as we iron out all the wrinkles in the tech that will help push adoption of Bitcoin.

**Comment by tanx** [comment]
We're looking into this. Also adding a restore PIN from recovery phrase feature https://github.com/lightninglabs/lightning-app/issues/1227

**Comment by drvnoo** [comment]
Just want to say I have the exact same issue.
Running Pixel 3 XL. I closed my only channel and now I can't log in anymore. The app keep sending me to the pin view. Sometimes I see the logged in view - but only for 0.5sec.

**Comment by CandleHater** [comment]
This issue is resolved at my end with the latest update. Thank you.
