### ISSUE TITLE
'f' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by findbl0k** [lightninglabs/lightning-app#126]
### Description

npm start does not start the app, but instead NPM err's. Running the latest npm v5.6.0 on windoze 10.

### Steps to reproduce the behavior
1. Clone zip from github
2. $ npm run setup
3. $ npm start

### Expected behavior

start the app :D

### Actual behavior

NPM ERROR :(

### Screenshot and/or logs if applicable

```
$ npm start

> lightning-app@0.1.4 start C:\Users\MY_USER\Desktop\lightning-app-master
> cd apps/desktop && npm start -s --

npm WARN invalid config loglevel="notice"
'f' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lightning-app@0.1.4 start: `cd apps/desktop && npm start -s --`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lightning-app@0.1.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MY_USER\AppData\Roaming\npm-cache\_logs\2018-01-01T22_49_44_852Z-debug.log
```

**Comment by diofeher** [comment]
I think this problem is introduced due to this change: https://github.com/lightninglabs/lightning-app/commit/40191cbf42c5b9db538ae44ac152ff62b1110cbb

I'm on it.

**Comment by diofeher** [comment]
@findbl0k Which version of windows are you using it?

**Comment by findbl0k** [comment]
@diofeher thanks for your reply.

I am running Windows 10 Home Version 1703 (OS Build 15063.786). My PC has an Intel Core i7-6700HQ and 16 GB of RAM. Thanks again for taking a look and let me know if you need any more info or need me to try anything.

**Comment by iamparkerm** [comment]
same with my issue #124. I don't know what was wrong with the nodejs method, but I downloaded the binaries and ran the app succesfully as was suggested -> https://github.com/lightninglabs/lightning-app/issues/124

**Comment by yate** [comment]
Is this as simple as changing `f;` to f`();`? What's the reason for the wrapper function in 40191cb anyway?

**Comment by diofeher** [comment]
@yate this is used to pass arguments in the middle of concurrently program, with that we can pass extra arguments to lnd. I'm getting a Windows machine this week and I should fix that.

**Comment by findbl0k** [comment]
For anyone else trying to run this on windows, the windows release at https://github.com/lightninglabs/lightning-app/releases works just fine for me.
