### ISSUE TITLE
Fiat exchange rate is null in certain cases (causes infinite balance on home screen)

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#1262]
See: https://twitter.com/provoost/status/1151110007079002114

**Comment by tanx** [comment]
Related to #1263

**Comment by bolatovumar** [comment]
I'm just looking into this and it looks like this is intended behaviour when something goes awry when retrieving the exchange rate (?).

See unit tests under `helpers.spec.js`: 
>should be infinity if exchange rate is not set (fiat)

and
>should be infinite for unknown rate

The only way something can go wrong with exchange rate is if the server API returns some invalid value as there is only one place where `store.settings.exchangeRate` is set in `wallet.js`.
