### ISSUE TITLE
Settings reset after update to 0.2.0 on iOS

### ISSUE THREAD

**Issue by tobiasl1** [lightninglabs/lightning-app#1263]
### Description
After updating to version 0.2.0 (10) on iOS the settings for 'Fiat Currency' and 'Enable Autopilot' were reset to their default values.

### Steps to reproduce the behavior
Update to 0.2.0 with settings different from default.

### Expected behavior
Settings should persist on updates.

### Actual behavior
Settings were reset to default.

**Comment by tanx** [comment]
The user settings are stored in `AsyncStorage`, which seems to be different in the bare react native build than the expo one: https://github.com/lightninglabs/lightning-app/issues/1054

Unfortunately not much we can do here. Restarting the app fetched the exchange rates and nodes scores. Once all users are upgraded to `0.2.0` the issue should be resolved for future updates.

**Comment by tobiasl1** [comment]
So if the bug should not occur in future updates, i guess this issue can be closed.
