### ISSUE TITLE
Failed to open a channel on lightningapp 0.1.4

### ISSUE THREAD

**Issue by bitcoinuser** [lightninglabs/lightning-app#128]
Tried to open a channel and appear this message on settings:

nd: 2018-01-09 21:19:14.005 [INF] FNDG: Starting funding workflow with 45.77.115.33:9735 for pendingID(c323711a205209fef366644116733c759fbeb3fca26e2093b732992f6e205ef4) 2018-01-09 21:19:14.005 [INF] SRVR: Attempting to send msgs 1 to: 02ecafd1d828301da58edacdd61232835940c91767a01b3bfba57240989f9df4da
lnd Error: panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x839b88] goroutine 1 [running]:
lnd Error: github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcutil/gcs.(*Filter).MatchAny(0x0, 0x52f322688c2f6a6d, 0x6c850403701f747d, 0xc4205ddc00, 0x1, 0x1, 0x0, 0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcutil/gcs/gcs.go:313 +0x48 github.com/lightningnetwork/lnd/routing/chainview.(*CfFilteredChainView).FilterBlock(0xc42000fc30, 0xc420e3c600, 0xc420e3c600, 0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/routing/chainview/neutrino.go:258 +0x631 github.com/lightningnetwork/lnd/routing.(*ChannelRouter).syncGraphWithChain(0xc42000fd90, 0xc420f62c30, 0x1) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/routing/router.go:450 +0x6c2 github.com/lightningnetwork/lnd/routing.(*ChannelRouter).Start(0xc42000fd90, 0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/routing/router.go:324 +0x407 main.(*server).Start(0xc420500000, 0xe6f4c3, 0x2e) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/server.go:415 +0x11d main.lndMain(0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/lnd.go:401 +0x170b main.main() /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/lnd.go:450 +0x36

**Comment by Roasbeef** [comment]
Were you running a prior version of the application? Are you connecting to your own node on the command line?

**Comment by bitcoinuser** [comment]
No, I was not using a prior version. I was trying to create a channel with yalls.org

**Comment by Roasbeef** [comment]
Were you running a btcd node locally?

**Comment by bitcoinuser** [comment]
I'm a newbie user. The only thing I tried before was install zap app.

**Comment by Roasbeef** [comment]
If the Zap app was on a prior version, and left a dated database state on-disk, then this may occur. Some details concerning the way the light client work changed recently.

**Comment by bitcoinuser** [comment]
Ok, closing.
