### ISSUE TITLE
Expired Windows code signing certificate

### ISSUE THREAD

**Issue by andronoob** [lightninglabs/lightning-app#1286]
The digital signature of `Lightning-win32v0.5.5-alpha.exe` is not considered valid by Windows, because it was signed with a expired certificate.

Auto-update feature seemed to stop working due to this reason as well.

**Comment by valentinewallace** [comment]
Hello, thank you for the report! We're in the process of renewing the cert.

**Comment by tanx** [comment]
Should be resolved in `0.5.6`
