### ISSUE TITLE
Make payment error messages more comprehensive and more persistent

### ISSUE THREAD

**Issue by ptoussai** [lightninglabs/lightning-app#129]
When clicking on Send Payment I see:

`Payment route failure`

However lnd returns something like:

```
{
	"payment_error": "unable to route payment to destination: TemporaryChannelFailure: insufficient capacity in available outgoing links: need 9002018 mSAT, max available is 1312000 mSAT",
	"payment_preimage": "",
	"payment_route": null
}
```

I would expect to see the full error message, or enough information so I can understand what it going on.

I think that in the current state, it is fine to show the payment error as it is.

**Comment by bryanvu** [comment]
@botrunner These error messages are something that we've been wanting to get around to improving. I changed the issue title, but this is a good placeholder for that work.

**Comment by botrunner** [comment]
Note: For some reason, haven’t looked at the code yet, some other errors seemed to display in full.
