### ISSUE TITLE
Add Channel Funding UI with status and errors 

### ISSUE THREAD

**Issue by bitcoinuser** [lightninglabs/lightning-app#130]
lnd: 2018-01-10 16:23:01.781 [INF] PEER: unable to read message from 45.63.87.131:9735: EOF
lnd: 2018-01-10 16:23:01.781 [ERR] FNDG: unable to cancel reservation for node=03b83283765f36daa497207f214416177020d962e4d38a805f17bd5583bd8a18d2: attempted to cancel non-existent funding state 2018-01-10 16:23:01.781 [INF] HSWC: Removing channel link with ChannelID(e520a692bbdd7a5e3615bd0aadf8e1fad2fd2d550e4fcc63eb6bc25901ef6a57)
lnd: 2018-01-10 16:23:01.781 [INF] HSWC: ChannelLink(576aef0159c26beb63cc4f0e552dfdd2fae1f8ad0abd15365e7addbb92a620e5:0) is stopping
lnd: 2018-01-10 16:23:01.781 [ERR] RPCS: unable to open channel to identityPub(03b83283765f36daa497207f214416177020d962e4d38a805f17bd5583bd8a18d2) nor peerID(0): peer disconnected
lnd: 2018-01-10 16:23:01.781 [INF] HSWC: ChannelLink(576aef0159c26beb63cc4f0e552dfdd2fae1f8ad0abd15365e7addbb92a620e5:0) has exited
lnd: 2018-01-10 16:23:01.781 [INF] NTFN: Cancelling epoch notification, epoch_id=5
lnd: 2018-01-10 16:23:15.999 [INF] RPCS: [listchannels] fetched 3 channels from DB
lnd: 2018-01-10 16:23:19.454 [INF] SRVR: Established connection to: 45.63.87.131:9735
lnd: 2018-01-10 16:23:35.960 [INF] RPCS: [listchannels] fetched 3 channels from DB

**Comment by bitcoinuser** [comment]
The channel page appear CID:0

**Comment by bitcoinuser** [comment]
When I restarted the lightningapp, now I see: CID: 1383541869510197248

**Comment by bitcoinuser** [comment]
Hum, But tried to pay htlm.me, and failed as: payment route failure.

**Comment by bitcoinuser** [comment]
I see tha the channel is not Active.

**Comment by skwp** [comment]
I had the same issue opening up a channel with yalls.org. The button appeared to do nothing for a long time (no feedback from clicking), then I got a thing that said it's opening a channel but it showed "0 sats" so that's pretty misleading since that wasn't the number I typed in. Need better visual feedback as to the process going on.

**Comment by swilliams96** [comment]
I'm having the same issues as described by @skwp after making a channel. No response or feedback is provided to show it's processing after pressing the "Create Channel" button, then it continues to show "CID: 0" on the channels UI after the opening transaction has 2+ confirmations. Restarting the application fixes this so I'd guess it is something to do with the channels UI not updating properly when a new block is found.

Additionally, perhaps the channel ID should be hidden if the channel status is not "OPEN" to improve UX and minimise confusion?

**Comment by skwp** [comment]
It took a long time but my channel showed up. Is this due to long tx mining times on testnet? This is my first time on testnet and looking at the blocks I'm seeing something like 15 min between some of the blocks. Perhaps what we experienced is that?

**Comment by bryanvu** [comment]
@skwp, not sure about exactly what's going on with your channel. However, I do think that we can improve the overall channel funding process. Changed the title of the issue to reflect that.
