### ISSUE TITLE
Private Key Information on Storage/Recovery missing from Read Me?

### ISSUE THREAD

**Issue by esquinato** [lightninglabs/lightning-app#131]
Being in this space for a long time, this is something i immediately looked for and couldn't find.

I've already compiled and synced however I'm not willing to send mainnet transactions until I can see/copy/store whatever sort of key is needed to restore my account later when re-compiled....

Am I just missing something?

Thanks in advance!

**Comment by bryanvu** [comment]
@esquinato, @kevinejohn has done some initial work on the seed generation and backup flow, but it's not merged yet. One of the things we'll need to get done before the App is ready for mainnet.

**Comment by tiero** [comment]
Any link to this? How I can extract the Node Private Key? Thanks
