### ISSUE TITLE
btc funding doesn't show up on macos catalina

### ISSUE THREAD

**Issue by haukehess** [lightninglabs/lightning-app#1319]
### Description

sent btc to lightning wallet adress 3BEBoUsHZgceSjwL9n598MXmmsVF6c1iQM.

tx is: https://blockstream.info/tx/ef16bb9b814e86995f4cac394598b25a919d3d402c281dd7b37f05b8d12c296a
<img width="504" alt="Bildschirmfoto 2019-10-31 um 14 20 58" src="https://user-images.githubusercontent.com/39943892/67950307-ac689e80-fbe9-11e9-94ae-9d76ff09fdcd.png">

Amount didn't show up

### Steps to reproduce the behavior

don't know, restarting app is not changing anything

### Expected behavior

showing the amount and stop synching loop

### Actual behavior

not showing amount

### Screenshot and/or logs if applicable
<img width="432" alt="Bildschirmfoto 2019-10-31 um 14 29 01" src="https://user-images.githubusercontent.com/39943892/67950910-d1a9dc80-fbea-11e9-8421-912deb57733b.png">

**Comment by bolatovumar** [comment]
@haukehess this looks like a sync issue where it got stuck so you don't see because of that.

**Comment by haukehess** [comment]
I recovered my funds with zap and the seed from ln-app, will wait for the next version to continue.

von unterwegs gesendet...
