### ISSUE TITLE
Not opening in High Sierra

### ISSUE THREAD

**Issue by MichelDiz** [lightninglabs/lightning-app#133]
### Description
Don't do anything.
Download Lightning-darwin-x64v0.1.4.zip
### Steps to reproduce the behavior
Extract it, run.
### Expected behavior
Be Running
### Actual behavior
Not running LOL
Just Shows "Quit" option from electron.

**Comment by MichelDiz** [comment]
Oh, well, take a time but suddenly worked.

**Comment by MichelDiz** [comment]
Oh, well, take a time but suddenly worked.

**Comment by bryanvu** [comment]
Hi @MichelDiz, when the app starts the first time, it generates TLS certificates that can take a little while. Issue #122 is to make it more clear what's going on during that wait time.
