### ISSUE TITLE
recover fund in the ios wallet after 12/31?

### ISSUE THREAD

**Issue by moulin1024** [lightninglabs/lightning-app#1343]
Hi guys,

I was trying to play with the bitcoin lighting networks last summer a bit to support some local business. So I installed the iso mobile wallet in an old iphone. But as time flies I kind of forgot it.

However, recently when I check that phone again I saw the app now add a line (Move Funds by 12/31)...... And when I try to move the funds now (08/01/2021), it just keeps showing "insufficient funds available" even in the app it shows that there are still 0.02 btc.

So I was wonder if it is still possible to recover the fund in here? Does the dev team just abandon this project? 

Thanks a lot.

An update: It turns out that there is a pending force closing channel in the wallet. After waiting till it close I was able to transfer the fund.

**Comment by bolatovumar** [comment]
It's probably possible to recover the funds with some fiddling. Is "insufficient funds available" the exact error that you get? Or is worded differently? I feel like this error comes from LND and someone who knows LND well enough should be able to tell you what this error means exactly.
