### ISSUE TITLE
"EOF"

### ISSUE THREAD

**Issue by settdigger** [lightninglabs/lightning-app#135]
### Description

Hi, I tried to open a channel with:

03459c42e997536a3347cb31c19c50df2d8e0d22e4b064de4c435a75bb275b9d47@lnd.bitrefill.com

(following Justin Camarena's helpful instructions - https://blog.bitrefill.com/lightning-payments-on-testnet-for-bitrefill-b3edac845654 )

All that happened was a little "EOF" flashed in the lower right. What does this mean?

**Comment by molxyz** [comment]
@settdigger That's a very old node key that doesn't exist anymore. If you read the blog the correct URI to open a channel with Bitrefill is:  lncli connect 0298d0c6987e2e64451c7f723e15aff4dfca92f0e3973d214e206257abb0d1dd55@lnd.bitrefill.com

**Comment by evanrinehart** [comment]
Use <pubkey>@<ipaddr>:<port>
or click the "copy URI" link. Not all of the nodes shown will work, perhaps because they don't really exist, stale info on the explorer.

**Comment by settdigger** [comment]
Thanks for your help! I did get a few channels to work. How could I set my IP address to public, if I wanted to? (My node does show on that map now, but no one can connect to it.)

**Comment by Roasbeef** [comment]
In order to accept inbound connections, you'll need to figure out your NAT situation. 

Closing as the original situation has been resolved.
