### ISSUE TITLE
Wallet amount displayed incorrectly while channel waiting to be opened

### ISSUE THREAD

**Issue by MidnightLightning** [lightninglabs/lightning-app#140]
### Description
After creating a new channel, and being taken back to the "Channels" tab, the blue bar at the top of the page incorrectly identifies that zero satoshis are on-chain, and the only balance of the account is locked in payment channels.

### Steps to reproduce the behavior
Create a new channel, and note the wallet balance while the chain is being opened.

### Expected behavior
Show both on-chain balance and channel balance

### Actual behavior
On-chain balance is incorrectly displayed as zero.

### Screenshot and/or logs if applicable
While the channel's opening:
![Channels listing](https://user-images.githubusercontent.com/250250/34920389-798dda18-f937-11e7-980a-05ef9ebb4a78.PNG)
Note the lower-left and top-center wallet balances show as 77 million satoshis, and in the upper-right, 77 million satoshis in channel states, and zero on-chain (incorrect; there should be 34 million still in on-chain balance).

After the channel opens:
![channels after](https://user-images.githubusercontent.com/250250/34920498-3bcb9952-f939-11e7-9f8b-85fa0bbf77e7.PNG)
Lower-left balance and top-center balance show 111 million satoshis, and upper-right indicator shows 34 million in on-chain balance (correct).

**Comment by r0zar** [comment]
Tested this is an issue in v0.1.4-alpha

**Comment by robertDurst** [comment]
Also tested in v0.1.4 and can confirm. This is a bit wonky.
