### ISSUE TITLE
Channels in a "Pending closing" state show no balance

### ISSUE THREAD

**Issue by MidnightLightning** [lightninglabs/lightning-app#142]
### Description
When a channel is closing (and awaiting an on-chain transaction to close it out), both the "My balance" and "able to receive" are shown as zero. All the funds the user is receiving are shown in the "in limbo" entry for the wallet.

### Steps to reproduce the behavior
Close a channel.

### Expected behavior
The amount that I'll be receiving out of the channel closing remain in the "My Balance" indicator. The color of the whole transaction going to gray indicates it's not yet finalized.

### Actual behavior
"My Balance" shows as zero, which if there's multiple channels pending closing, makes it impossible to tell how much funds are waiting for which on-chain transaction to clear.

### Screenshot and/or logs if applicable
![capture](https://user-images.githubusercontent.com/250250/34920791-6f215e54-f93e-11e7-93ca-02e35b65cf42.PNG)

**Comment by halfik** [comment]
confirm. have same issue on windows 7 (64).
