### ISSUE TITLE
"Payment route failure"

### ISSUE THREAD

**Issue by brunoaduarte** [lightninglabs/lightning-app#144]
### Description
"Payment route failure" when trying to pay for 0.000019 BTC to starblocks.acinq.co.

### Steps to reproduce the behavior
- Start "lightning.exe" from "Lightning-win32-x64".
- Get the wallet address, add funds from "https://testnet.manu.backend.hamburg/faucet" and wait for it to be confirmed
- Create a new channel with "0298d0c6987e2e64451c7f723e15aff4dfca92f0e3973d214e206257abb0d1dd55@lnd.bitrefill.com"
 (1,000,000 SAT) and wait for it to open (3 confirmations).
- Try to make the payment of 1,900 SAT to "lntb19u1pd9699hpp5pcqrq8uuzav9dpjj3er945fklhfnfgrdmu555xp4hwfgrt9qw5wqdp8xys9xcmpd3sjqsmgd9czq3njv9c8qatrvd5kumcwyxyyyq9nkn9d00j0f0shytq6kpvm5um4r8m3u72ucsxp8z4sanxzq8dr6arnyvn58phe4wr7texnghvq036ctuwrkj2330s4kcprqcqqc7rwq"
- Error message showed "PAYMENT ROUTE FAILURE"

Same problem when trying to pay lightning.bitrefill.com

### Screenshot and/or logs if applicable

![01](https://user-images.githubusercontent.com/5354345/34961583-072b19d6-fa27-11e7-975b-e7deea8c8387.png)

![02](https://user-images.githubusercontent.com/5354345/34961590-10c3d60e-fa27-11e7-92a2-f6033c9e4e6f.png)

**Comment by Roasbeef** [comment]
You only have a single channel. There may not be an active path through bitrefill to starblocks. If you look at the logs, you'll see additional debugging details.

**Comment by brunoaduarte** [comment]
Correct. A connected to 1 more channel and 3 more channels appeared (people connecting to my channel ?). Now it worked, i was able to pay Starblocks.
BTW, is it possible to run lightning-app on the main net so i can pay torguard ?

**Comment by Roasbeef** [comment]
@DionJakobs the ability to pay to a node depends on the level of connectivity a node has. Starblocks only has a single channel leading to it as it doesn't listen itself. If this channel becomes fully unbalanced, then it won't be able to support payments. As this is testnet, no one is actually incentivized to increase connectivity.
