### ISSUE TITLE
Attempt to send payment  UnknownNextPeer

### ISSUE THREAD

**Issue by halfik** [lightninglabs/lightning-app#150]
### Description
I left application up and running during night. Now i tried to make a payment for starblocks cofffe and get this error:

[ERR] CRTR: Attempt to send payment 84a5dae8e28382e51b059caf612453a2f0ad48717db366fb2a6d9955fceb8f31 failed: UnknownNextPeer

Using: v0.1.4-alpha on windows 7 (64)

### Steps to reproduce the behavior
Leave app up and runing for some period of time?

**Comment by Roasbeef** [comment]
This isn't an actual issue. This is a protocol level error, which will eventually be hidden from the end user. It means one of the hops in the route wasn't available to actually complete the payment.

**Comment by halfik** [comment]
Then it is an issue but on protocol level i belive. Still you can add some kind of handler for this error.
