### ISSUE TITLE
Channel update for edge not found

### ISSUE THREAD

**Issue by halfik** [lightninglabs/lightning-app#151]
### Description
Yesterday app was running ok (v0.1.4-alpha on Windows 7(64)). It opened like 5 auto channales.
Today it coudn't find a route so i restart it and when i try to make a starblocks coffe payment i get this errors:

lnd: 2018-01-19 14:27:22.445 [INF] DISC: Got ChannelUpdate for edge not found in graph(shortChanID=1383435216882892800), saving for reprocessing later

lnd: 2018-01-19 14:27:22.899 [ERR] DISC: Router rejected channel edge: unable to fetch utxo for chan_id=1383624332886016000, chan_point=5a4cd411df963ba111df68469fd8f5a65c7ff0819c4c32bc7cae7c6f3a3f6fea:0: target output has been spent

**Comment by Roasbeef** [comment]
Not an issue, just some nodes on testnet don't properly validate announcements.
