### ISSUE TITLE
MacOS - "Hide" menubar commands

### ISSUE THREAD

**Issue by photonclock** [lightninglabs/lightning-app#152]
### Description
GUI feature for MacOS:
Add "Hide", "Hide Others", "Show All" commands to "Lightning" menubar of MacOS version of Lightning App

### Steps to reproduce the behavior
Press command-H or command-option-H

### Expected behavior
command-H or select "Hide" from "Lightning" menu - hide Lightning app
command-option-H or select "Hide Others" from "Lightning" menu - hide other applications leaving Lightning app in foreground

### Actual behavior
Hide and Hide Others commands are not implemented in Lightning menu.
"Show All" command is a related command that is considered universal for a MacOS application's menubar.

**Comment by bryanvu** [comment]
Addressed by PR #157.
