### ISSUE TITLE
Panic Error >> lnd Error: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by machine-uprising** [lightninglabs/lightning-app#156]
### Description
Received lnd panic error during initialization of peer network bootstrappers. Lightning had been working well all day and the past week. I had closed it down for about an hour and then on restarting this error has occurred twice in a row. 

The version I'm using is the pre-packaged .exe for Windows. Have been using it the past week without errors occuring. 
 
### Steps to reproduce the behavior
1. Open Lightning
No abnormal action before error.

### Expected behavior
Lightning opens and normal initialisation starts and completes successfully. 

### Actual behavior
Lightning opens and starts initialisation process but hits runtime panic error causing initialisation to stop. 

### Screenshot and/or logs if applicable
[lightning-app panic error 20170120.txt](https://github.com/lightninglabs/lightning-app/files/1649245/lightning-app.panic.error.20170120.txt)

**Comment by Roasbeef** [comment]
This has been fixed within `lnd` itself, and should be fixed when we roll out a new version of the application early next week.

**Comment by machine-uprising** [comment]
Thanks for the update. Do you have any info or link to info about the cause of the error?

**Comment by rick-kln** [comment]
Great to hear this is possibly fixed, this sounds like it might be related to the same problem I had here: https://github.com/lightninglabs/lightning-app/issues/155 If so, and a fix is on the way I will close my issue :)

**Comment by DionJakobs** [comment]
I have the same problem. 
Same packages and aswell after restarting (since channels took too long to load).

**Comment by Roasbeef** [comment]
A version of `lnd` with this fix included is now packaged with the latest version of the application.
