### ISSUE TITLE
Channel creation: Change disappears

### ISSUE THREAD

**Issue by Liongrass** [lightninglabs/lightning-app#162]
### Description
When creating a new channel with a smaller funding amount than my total on-chain wallet balance, frequently (but not always) the change would not be credited back to my on-chain balance.

### Steps to reproduce the behavior
1. Fund wallet with x satoshi
2. Create new channel with <x satoshi

### Expected behavior
3. I expect the difference between the channel amount be credited back to my on-chain balance

### Actual behavior
3. The channel is opened successfully, the channel amount is credited to my in-channels balance. The off-chain balance is at 0.
This does not always happen, and I'm unable to reliable reproduce it, but it's quite frequent.

### Screenshot and/or logs if applicable
Transaction example:
https://live.blockcypher.com/btc-testnet/tx/c672962312e9ff3b21e9ea4d4fba4fe3500b373029b453ee79011e96777364db/

**Comment by bryanvu** [comment]
With the version of lnd that's packaged with the app, you'll have to wait 3 confirmations before your change appears back in your on-chain balance. If this isn't happening and you're still not seeing your balance being updated, please reopen and post logs.

**Comment by Liongrass** [comment]
Can confirm that the balance does not appear after three confirmations or more, even after restarting the app. Will post logs when I have them
