### ISSUE TITLE
"Payment route failure" issue, can't conduct any transaction

### ISSUE THREAD

**Issue by Tryptohash** [lightninglabs/lightning-app#166]
Hello,
I've set up a node using Lightning App ( the newest release ) on testnet and came across some issues with payments.
I had spend three channels. Any time I try to conduct a payment to Starblocks to test it, I receive the following notice:
"Payment route failure"
It is just not only for Starblocks, but for other sites too. 

<img width="745" alt="lightning app" src="https://user-images.githubusercontent.com/35743171/35297064-2fce44a0-007e-11e8-9012-79b7e7c4c03d.png">

Thanks in advance.

PS. Does Lightning App work ATM on mainnet?

**Comment by Beyonderx** [comment]
Yeah i get the same...

**Comment by bryanvu** [comment]
Is one of your channels opened directly with Starblocks? Please see the issue that references this one. If you're still having issues, please reopen and post the logs.
