### ISSUE TITLE
Unable to syncing to the chain

### ISSUE THREAD

**Issue by silver-moose** [lightninglabs/lightning-app#168]
### I unable to send transaction into my Lightning App
Transaction#  03c4b20397d476a0d008e61022c96803ada3c11918fff8133db4f7d27273710e03

My transaction stay in-progress... never confirm 

It should be fine from the trace
....
lnd: 2018-01-24 14:37:38.570 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-24 14:37:58.638 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-24 14:38:18.600 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-24 14:38:38.592 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-24 14:38:42.392 [INF] BTCN: Processed 1 block in the last 5m3.43s (height 1260298, 2018-01-24 14:38:09 -0500 EST)
lnd: 2018-01-24 14:38:58.525 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-24 14:39:19.225 [INF] RPCS: [listchannels] fetched 0 channels from DB

**Comment by silver-moose** [comment]
Here another example:
2NB1znSyMTkkbDr6r4GrcjnFtKRMRNLVQsx
TX ID: e9dcfb4c68e79a76f036c63fb60991565a63e8bab5d8c007ee33ed7bb4dd7824

Trace from Lightning-app
lnd: 2018-01-24 15:02:29.991 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-24 15:02:36.352 [INF] RPCS: [newaddress] addr=2NB1znSyMTkkbDr6r4GrcjnFtKRMRNLVQsx
lnd: 2018-01-24 15:02:38.531 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-24 15:02:58.543 [INF] RPCS: [listchannels] fetched 0 channels from DB
...

**Comment by Beyonderx** [comment]
This bug happens here too, it seems it is database corruption, it works after i delete the database and download it again.

**Comment by Beyonderx** [comment]
This must be fixed, it's really bad atm.

**Comment by Roasbeef** [comment]
I can't find your first transaction in the testnet mempool of any of my nodes. The second transaction you listed https://testnet.smartbit.com.au/tx/e9dcfb4c68e79a76f036c63fb60991565a63e8bab5d8c007ee33ed7bb4dd7824? 

There's no known database corruption. This issue itself also doesn't provide any actionable details.

**Comment by silver-moose** [comment]
Here my steps:
1)From Lightning App
click <Request> pick up the wallet 2MyNYcr1zC3BQYDNjedj6ces1VbZ8C5jhzN

2)  https://testnet.manu.backend.hamburg/faucet
enter wallet  2MyNYcr1zC3BQYDNjedj6ces1VbZ8C5jhzN
click <Give me some coin> 
Sent! TX ID: cf4d0f1f7da93235546ce7194a35881e0401f0a3182cf05a0da0dd66df05af9b

https://live.blockcypher.com/btc-testnet/address/2MyNYcr1zC3BQYDNjedj6ces1VbZ8C5jhzN/

Transaction confirmed, however I still have 0 satoshi in my Lightning App
How can I refresh my database?

----- Trace 
lnd: 2018-01-25 08:35:16.994 [INF] LNWL: Opened wallet
lnd: 2018-01-25 08:35:19.131 [INF] LNWL: The wallet has been unlocked without a time limit
lnd: 2018-01-25 08:35:19.346 [INF] LTND: LightningWallet opened
lnd: 2018-01-25 08:35:19.984 [INF] RPCS: RPC server listening on 127.0.0.1:10009
lnd: 2018-01-25 08:35:20.212 [INF] RPCS: gRPC proxy started at localhost:8080
lnd: 2018-01-25 08:35:20.444 [INF] LTND: Waiting for chain backend to finish sync, start_height=1260486
lnd: 2018-01-25 08:35:20.761 [INF] LNWL: Started rescan from block 00000000002f32b4c93d32061f893b355f3027972bd816fc0ad6cef89d537991 (height 1239543) for 39 addresses
lnd: 2018-01-25 08:35:21.110 [INF] LNWL: Catching up block hashes to height 1239544, this might take a while
lnd: 2018-01-25 08:35:21.231 [INF] LNWL: Done catching up block hashes
lnd: 2018-01-25 08:35:21.328 [INF] LNWL: Rescanned through block 0000000000003eccc200ab3905b2043d8b5449a941ee32db1223bfd9dfd55b2b (height 1239544)
lnd: 2018-01-25 08:35:41.143 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-25 08:36:00.960 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-25 08:36:20.972 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-25 08:36:37.786 [INF] RPCS: [newaddress] addr=2MyNYcr1zC3BQYDNjedj6ces1VbZ8C5jhzN
lnd: 2018-01-25 08:36:40.981 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-25 08:37:00.958 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-25 08:37:20.960 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-25 08:37:40.983 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-25 08:38:00.964 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-25 08:38:20.965 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-25 08:38:40.966 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2018-01-25 08:38:48.827 [INF] BTCN: Processed 133 blocks in the last 3m33.98s (height 1260487, 2018-01-25 08:38:34 -0500 EST)
....

**Comment by bryanvu** [comment]
The block your transaction was confirmed in as 1260488, and in this log, your node is only caught up to 1260487.
