### ISSUE TITLE
Syncing to chain frozen

### ISSUE THREAD

**Issue by halfik** [lightninglabs/lightning-app#171]
### Description
If computer goes to sleep or lose network connection while apllication is up and running it stays in state "syncing to chain".

If application gets closed and started again, it syncs after couple of minutes.
I was waiting for over 1h and it never get out of "syncing" state in both cases: computer was sleep and i diconetected network.

Its doing somthing - i see changes in log. But state remains and im unable to do any payments.

### Steps to reproduce the behavior
Disconect nertwork or put machine to sleep.

### Expected behavior
Get synced.

### Actual behavior
Forever syncing.

**Comment by bryanvu** [comment]
For help with this, we would need to see the actual log. Please post. It may also be easier to discuss in the lightning-app channel on the developer Slack. Also, if you close and reopen the app, does it sync at that point?

**Comment by halfik** [comment]
Ok i will try to do reproduce problem and then paste logs.
Tried today with network off for 15min but nothing happend. Maybe it need more time with out network? Gona test it in days. And yes, restarting application solves the problem.
