### ISSUE TITLE
npm run setup fails debian arm

### ISSUE THREAD

**Issue by cheeseSnake** [lightninglabs/lightning-app#172]
chip@chip:/scratch/lightning-app$ sudo npm run setup
[sudo] password for chip: 

> lightning-app@0.1.4 setup /scratch/lightning-app
> npm install && npm run install-grpc

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'case/eslint-config' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'lightning-app'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.4.13-ntc-mlc
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /scratch/lightning-app
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /scratch/lightning-app/npm-debug.log
npm ERR! not ok code 0

npm ERR! lightning-app@0.1.4 setup: `npm install && npm run install-grpc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lightning-app@0.1.4 setup script.
npm ERR! This is most likely a problem with the lightning-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install && npm run install-grpc
npm ERR! You can get their info via:
npm ERR!     npm owner ls lightning-app
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.4.13-ntc-mlc
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "run" "setup"
npm ERR! cwd /scratch/lightning-app
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /scratch/lightning-app/npm-debug.log
npm ERR! not ok code 0

**Comment by cheeseSnake** [comment]
vi scratch/lightning-app/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'setup' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose run-script [ 'presetup', 'setup', 'postsetup' ]
5 info presetup lightning-app@0.1.4
6 info setup lightning-app@0.1.4
7 verbose unsafe-perm in lifecycle true
8 info lightning-app@0.1.4 Failed to exec setup script
9 error lightning-app@0.1.4 setup: `npm install && npm run install-grpc`
9 error Exit status 1
10 error Failed at the lightning-app@0.1.4 setup script.
10 error This is most likely a problem with the lightning-app package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     npm install && npm run install-grpc
10 error You can get their info via:
10 error     npm owner ls lightning-app
10 error There is likely additional logging output above.
11 error System Linux 4.4.13-ntc-mlc
12 error command "/usr/bin/nodejs" "/usr/bin/npm" "run" "setup"
13 error cwd /scratch/lightning-app
14 error node -v v0.10.29
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by bryanvu** [comment]
We currently don't bundle the arm binary of lnd with the app. To make this work, you'd have to build the arm version of [lnd](https://github.com/lightningnetwork/lnd) and replace the lnd binary in apps/desktop/bin/linux. If you're building lnd on a non-arm system, you can use/modify the release.sh to set the build parameters.
