### ISSUE TITLE
panic when activating app

### ISSUE THREAD

**Issue by mntetai** [lightninglabs/lightning-app#174]
### Description
Panic is created when lightning app is activated
Application is running on windows 10 , version of app is v0.1.4
### Steps to reproduce the behavior
Install app on windows 10  , add channels .
### Expected behavior
app should run 
### Actual behavior
app is stuck on startup
### Screenshot and/or logs if applicable
Logs
<pre>
lnd: 2018-01-26 23:37:14.822 [INF] CMGR: Server listening on [::]:9735 2018-01-26 23:37:14.822 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
lnd: 2018-01-26 23:37:14.830 [INF] ATPL: Autopilot Agent starting
lnd: 2018-01-26 23:37:14.830 [INF] ATPL: Processing new external signal
lnd: 2018-01-26 23:37:14.856 [INF] SRVR: Attempting to send msgs 1 to: 02d2ccdf98507238b7980c94616815ad2fec75f048caeaba738f408da363e43ba1 2018-01-26 23:37:14.856 [ERR] SRVR: unable to send message to 02d2ccdf98507238b7980c94616815ad2fec75f048caeaba738f408da363e43ba1, peer not found 2018-01-26 23:37:14.856 [ERR] DISC: unable to send AnnounceSignatures message to peer(02d2ccdf98507238b7980c94616815ad2fec75f048caeaba738f408da363e43ba1): unable to find peer. Will retry when online.
lnd: 2018-01-26 23:37:14.937 [INF] CRTR: Updated vertex data for node=02fcc36d8017f87d8be4240b9308ea1413bbc2b94afb30808aa66cbac2df8ec47d
lnd: 2018-01-26 23:37:14.944 [INF] DISC: Obtained 3 addrs to bootstrap network with
lnd: 2018-01-26 23:37:15.016 [INF] SRVR: Established connection to: 5.51.143.110:9735
lnd: 2018-01-26 23:37:15.249 [INF] NTFN: New spend notification for outpoint=532314c90697a5eaf48bfa64c24dc3459a96905e89cd67b63f753f3d010e0546:0, height_hint=1260269
lnd: 2018-01-26 23:37:16.182 [INF] PEER: peerID(1) loading ChannelPoint(532314c90697a5eaf48bfa64c24dc3459a96905e89cd67b63f753f3d010e0546:0) 2018-01-26 23:37:16.182 [INF] LNWL: Close observer for ChannelPoint(532314c90697a5eaf48bfa64c24dc3459a96905e89cd67b63f753f3d010e0546:0) active
lnd: 2018-01-26 23:37:16.182 [INF] BRAR: ChannelPoint(532314c90697a5eaf48bfa64c24dc3459a96905e89cd67b63f753f3d010e0546:0) is now live, abandoning state contract for live version 2018-01-26 23:37:16.182 [INF] NTFN: New spend subscription: utxo=532314c90697a5eaf48bfa64c24dc3459a96905e89cd67b63f753f3d010e0546:0 2018-01-26 23:37:16.182 [INF] NTFN: New block epoch subscription
lnd: 2018-01-26 23:37:16.182 [INF] NTFN: Cancelling spend notification for out_point=532314c90697a5eaf48bfa64c24dc3459a96905e89cd67b63f753f3d010e0546:0, spend_id=3
lnd: 2018-01-26 23:37:16.212 [INF] HSWC: ChannelLink(532314c90697a5eaf48bfa64c24dc3459a96905e89cd67b63f753f3d010e0546:0) is starting 2018-01-26 23:37:16.212 [INF] HSWC: Added channel link with chan_id=46050e013d3f753fb667cd895e90969a45c34dc264fa8bf4eaa59706c9142353, short_chan_id=((lnwire.ShortChannelID) 1260269:123:0 )
lnd: 2018-01-26 23:37:16.212 [INF] HSWC: HTLC manager for ChannelPoint(532314c90697a5eaf48bfa64c24dc3459a96905e89cd67b63f753f3d010e0546:0) started, bandwidth=991312000 mSAT 2018-01-26 23:37:16.212 [INF] HSWC: Attempting to re-resynchronize ChannelPoint(532314c90697a5eaf48bfa64c24dc3459a96905e89cd67b63f753f3d010e0546:0)
lnd: 2018-01-26 23:37:16.212 [INF] SRVR: Established connection to: 159.89.4.162:9735 2018-01-26 23:37:16.212 [INF] HSWC: Received re-establishment message from remote side for channel(532314c90697a5eaf48bfa64c24dc3459a96905e89cd67b63f753f3d010e0546:0)
lnd: 2018-01-26 23:37:16.217 [INF] NTFN: New spend notification for outpoint=f8d154bc8d75cb56b70dd4575f5ea124958f3b153915b67d9fd50fb1f0319a83:0, height_hint=1260502
lnd: 2018-01-26 23:37:16.464 [INF] HSWC: ChannelLink(532314c90697a5eaf48bfa64c24dc3459a96905e89cd67b63f753f3d010e0546:0) has exited
lnd Error: panic: runtime error: index out of range goroutine 333 [running]: github.com/lightningnetwork/lnd/lnwallet.genHtlcSigValidationJobs(0xc05256e000, 0xc042698240, 0xc0424ec098, 0x1, 0x1, 0xc052568080, 0xc0525680d8, 0xf4240, 0xc04221c240, 0x20) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3476 +0x754 github.com/lightningnetwork/lnd/lnwallet.(*LightningChannel).ReceiveNewCommitment(0xc04260ca80, 0xc0425b6100, 0xc0424ec098, 0x1, 0x1, 0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/lnwallet/channel.go:3577 +0x718 github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).handleUpstreamMsg(0xc0420e83c0, 0x1445620, 0xc0426ea2c0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:898 +0xfcc
lnd Error: github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).htlcManager(0xc0420e83c0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:596 +0xcb2 created by github.com/lightningnetwork/lnd/htlcswitch.(*channelLink).Start /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/htlcswitch/link.go:267 +0x132
</pre>

**Comment by Argonath** [comment]
Same happening here. Windows 10 running v0.1.4

```
lnd Error: panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005code=0x0 addr=0x0 pc=0xbca889] goroutine 94 [running]: github.com/lightningnetwork/lnd/discovery.createChanAnnouncement(0x0, 0xc04204c960, 0x0, 0x0, 0x0, 0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/utils.go:26 +0x79 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processRejectedEdge(0xc042210a00, 0xc042201180, 0x0, 0x2, 0x2, 0x1, 0x1, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:1127 +0xc7 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processNetworkAnnouncement(0xc042210a00, 0xc0422eaf90, 0xc042201180, 0xc04268a300, 0xc04218fc60)
lnd Error: /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:1331 +0x5901 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler.func1(0xc042680180, 0xc0422eaf90, 0xc042210a00, 0xc042684000) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:841 +0x98 created by github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:857 +0x693
```
