### ISSUE TITLE
Panic when a channel is added 

### ISSUE THREAD

**Issue by mntetai** [lightninglabs/lightning-app#178]
### Description
I have added two channels to the app , once I have rebooted it it caused a crash .
Running on windows 10 Pro.
### Steps to reproduce the behavior
Open application after it's been closed.
### Expected behavior
App should run as usual 
### Actual behavior
App is stuck.
### Screenshot and/or logs if applicable
<pre>

lnd Error: panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x0 pc=0xbca889] goroutine 161 [running]: github.com/lightningnetwork/lnd/discovery.createChanAnnouncement(0x0, 0xc0421d21e0, 0x0, 0x0, 0x0, 0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/utils.go:26 +0x79 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processRejectedEdge(0xc042264100, 0xc04212a600, 0x0, 0x2, 0x2, 0x1, 0x1, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:1127 +0xc7 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processNetworkAnnouncement(0xc042264100, 0xc042171ad0, 0xc04212a600, 0x0, 0x0)
lnd Error: /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:1331 +0x5901 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler.func1(0xc042635d10, 0xc042171ad0, 0xc042264100, 0xc042633e00) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:841 +0x98 created by github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:857 +0x693

lnd Error: panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x0 pc=0xbca889] goroutine 80 [running]: github.com/lightningnetwork/lnd/discovery.createChanAnnouncement(0x0, 0xc04257a6e0, 0x0, 0x0, 0x0, 0x0, 0x0)
lnd Error: /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/utils.go:26 +0x79 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processRejectedEdge(0xc0422dca80, 0xc042062300, 0x0, 0x2, 0x2, 0x1, 0x1, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:1127 +0xc7 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processNetworkAnnouncement(0xc0422dca80, 0xc042245e30, 0xc042062300, 0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:1331 +0x5901 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler.func1(0xc042150660, 0xc042245e30, 0xc0422dca80, 0xc0424e80c0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:841 +0x98 created by github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:857 +0x693

lnd Error: panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x0 pc=0xbca889] goroutine 251 [running]:
lnd Error: github.com/lightningnetwork/lnd/discovery.createChanAnnouncement(0x0, 0xc0421bc280, 0x0, 0x0, 0x0, 0x0, 0x0)
lnd Error: /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/utils.go:26 +0x79 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processRejectedEdge(0xc0424f4880, 0xc05254a980, 0x0, 0x2, 0x2, 0x1, 0xd90601, 0xc0422f40e0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:1127 +0xc7 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).processNetworkAnnouncement(0xc0424f4880, 0xc04222d350, 0xc05254a980, 0xc0422f1920, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:1331 +0x5901 github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler.func1(0xc052514960, 0xc04222d350, 0xc0424f4880, 0xc0425cd760) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:841 +0x98 created by github.com/lightningnetwork/lnd/discovery.(*AuthenticatedGossiper).networkHandler /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/discovery/gossiper.go:857 +0x693
</pre>

**Comment by mntetai** [comment]
Found a way to activate the application.
close application.
cd C:\Users\<your user>\AppData\Local\Lnd\data\testnet3\bitcoin
rename channel.db to channel.db.old
re run application.
your channels are gone , but at least the app is running again :-)

**Comment by Roasbeef** [comment]
This is fixed in the latest version of `lnd` (has been for a few weeks), but the packaged version in the app isn't yet updated. We'll be updating it this coming week.

**Comment by mntetai** [comment]
ok , waiting for next release to close issue.

**Comment by DionJakobs** [comment]
I do have the same problem. After adding new channels and rebooting the application since it took too long for the channels to add.
