### ISSUE TITLE
Monitor npm dependencies for security using snyk

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#180]
See https://snyk.io

**Comment by MDrollette** [comment]
Doesn't Github basically have this feature already? Might just be a matter of flipping a switch under repo settings. https://help.github.com/articles/about-security-alerts-for-vulnerable-dependencies/

**Comment by tanx** [comment]
@MDrollette good point. Thanks for pointing. @kaplanmaxe has used snyk previously and made this suggestion. I don't know what features snyk has above what github already offers, as this features was just recently introduced by github and snyk has been around for a while?

**Comment by kaplanmaxe** [comment]
This is a good point @MDrollette . This is a new feature from GitHub and one I have not used. I would be curious to see a comparison between the 2 services. It also might not be a bad idea to add both. Have you used GitHub's feature before?

**Comment by tanx** [comment]
The GitHub dependency graph does indeed do a good job of this already. No need for snyk.io
