### ISSUE TITLE
Keep npm dependencies up to date using Greenkeeper

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#181]
See https://greenkeeper.io

This will only work once for monitoring dependencies on the main branch. So we would have to switch `v2` to be the main branch or active this once v2 replaces the current master.

Closes #19, closes #165

**Comment by kaplanmaxe** [comment]
I would highly advise against this. I think the opposite approach should be taken meaning dependencies should be locked to a specific version. Just 1 month ago, NPM had some data loss, and several packages were missing. This gave the opportunity for malicious actors to publish packages with the same name to NPM. If the `yarn.lock` file was removed, every `yarn install` would install the latest dependency. As the malicious actor, I could have set up a postinstall script to send a user's `wallet.dat` file to my server and thus stole the user's funds. I think this could be potentially very dangerous.

https://status.npmjs.org/incidents/41zfb8qpvrdj

**Comment by tanx** [comment]
Mmmmh. In general I share your concerns around npm. We generally don't want end users to `yarn install` though as they would get a prebuilt version. So the question is what's more important in terms of security... up-to-date dependencies or a stable/well-known working state. I'd err on the side of up-to-date dependencies, but I'm also not sure what the best approach is. In general I'd suggest we minimize npm dependencies and therefor attack surface on our developer machine. What do you think?

**Comment by kaplanmaxe** [comment]
I think there are good arguments for both approaches. In theory, keeping dependencies up to date sounds like the best as whenever a vulnerability is patched, we would automatically get the latest version. However, I think this places a lot of trust in who is actually publishing these packages. If a maintainers account is compromised for any reason, the attacker could publish a malicious package and if that makes it into the prebuilt version, it could result in the loss of users funds. I do agree with you we should minimize npm dependencies (without reinventing the wheel with everything of course). I've personally erred on the side of picking a dependency version, doing an audit, and locking to that version. I would be interested to hear other opinions, however.

**Comment by tanx** [comment]
Ok. Let's stick with the lock file for now. Seems like the safe approach in terms of protecting user funds. If we are really shipping an npm dependency with a CVE our [snyk/github monitoring](https://github.com/lightninglabs/lightning-app/issues/180) should notify us and we can patch quickly.

**Comment by tanx** [comment]
The sandbox for electron has been activated. So malicious npm updates should be less of an issue.
