### ISSUE TITLE
Increase unit tests coverage for existing mobx action/computed/store logic

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#189]

**Comment by tanx** [comment]
@bryanvu I've finished refactoring the core JS logic and added all the unit tests. Some feedback/review would be helpful: https://github.com/lightninglabs/lightning-app/compare/d3b730edf127365a1501586dc54545bf0289ff03...v2

**Comment by bryanvu** [comment]
One quick note on this is that the openChannels streaming RPC doesn't seem to be fully handled here: https://github.com/lightninglabs/lightning-app/blob/1baba0686c0b1b5c7dc67d2b531e4b1a7ddf618a/src/actions/channels.js#L104.

The four streaming response messages are described here: http://api.lightning.community/#openchannel.
