### ISSUE TITLE
Ability to open a new channel

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#191]

**Comment by valentinewallace** [comment]
Hey, have a PR that i think completes this feature! just need to clean it up but should be able to submit in the next day or so

**Comment by tanx** [comment]
Hey. Thanks for the PR. I actually just implemented this today on the [integration-tests branch](https://github.com/lightninglabs/lightning-app/blob/integration-tests/src/actions/channels.js). Need to get that reviewed/merged into v2. But no need to implement this again. Thanks though :)
