### ISSUE TITLE
Refactor the payment view to completely use the mobx store

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#192]
Parts of `view/pay.js` are using the mobx store while others are still using the react component's state. We should consolidate all state in the mobx store to have a single source of truth.

**Comment by kaplanmaxe** [comment]
I can take this one on as it somewhat relates to #175

**Comment by tanx** [comment]
> I can take this one on as it somewhat relates to #175

Cool. Feel free to just assign it yourself and pull the ticket to `In Progress` whenever you're ready.

**Comment by tanx** [comment]
I'm just seeing that I can't actuall assign issues to contributor who aren't in the lighting organization. I can assign outside PRs however. So we'll just pull that on the board whenever a PR opens.
