### ISSUE TITLE
Implement acceptance testing with jest / enzyme

### ISSUE THREAD

**Issue by kaplanmaxe** [lightninglabs/lightning-app#195]
I think it could be very beneficial to have some acceptance tests written for some of the views / components. I'm not the biggest fan of snapshot testing as they can be a pain to deal with, however I think testing certain props triggering view level logic would help reduce regression errors going forward.

Can't add labels to tickets, otherwise I would.

**Comment by tanx** [comment]
Ideally, I'd like to try to get the react components purely functional and have all testable business-logic and state in the mobx actions/computed code.

There might still be some value in having a few smoke tests on the UI layer, but those are generally very expensive to maintain. Also, considering there will be a complete redesign of the UI soon, we should hold off on any investments into user acceptance tests right now.

Happy to revisit the discussion later if it makes sense. Closing for now.
