### ISSUE TITLE
Handshake failed with fatal error SSL_ERROR_SSL

### ISSUE THREAD

**Issue by JimmyMow** [lightninglabs/lightning-app#20]
After installing dependencies and running setup, I am getting the following:

`Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE`

**Comment by JimmyMow** [comment]
This is due to the certs `lnd` generates in your `Lnd` directory. Manual fix for the time being that works for me:

```
# cd into your lnd directory and run these commands
openssl ecparam -genkey -name prime256v1 -out ~/Library/Application\ Support/Lnd/tls.key
openssl req -new -sha256 -key ~/Library/Application\ Support/Lnd/tls.key -out ~/Library/Application\ Support/Lnd/csr.csr -subj '/CN=localhost/O=lnd'
openssl req -x509 -sha256 -days 3650 -key ~/Library/Application\ Support/Lnd/tls.key -in ~/Library/Application\ Support/Lnd/csr.csr -out ~/Library/Application\ Support/Lnd/tls.cert
rm ~/Library/Application\ Support/Lnd/csr.csr
```

**Comment by Roasbeef** [comment]
Hmm, on which OS? 

We've done some work in `lnd` itself to be more liberal in the cipher suites that we advertised which I _thought_ fixed this issue.

**Comment by JimmyMow** [comment]
Oh dang, could be related to my env.

I'm on macOS Sierra 10.12.6 atm

**Comment by anthonyyaco** [comment]
I am seeing same error with Ubuntu 17.04

`E1013 22:53:36.912650084   27727 ssl_transport_security.c:940] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
`

**Comment by bryanvu** [comment]
Thanks @JimmyMow! Let us know if you see this again. It could be that you may have had a cert from an older install of lnd.

**Comment by Empact** [comment]
I'm getting this now:
```
E0306 01:58:25.678888000 140735889335104 ssl_transport_security.c:970] Handshake failed with fatal error SSL_ERROR_SSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE.
```

**Comment by mrfelton** [comment]
I'm getting a similar issue:

```
E0307 10:05:23.045336000 140736107729792 ssl_transport_security.cc:979] Handshake failed with fatal error SSL_ERROR_SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure.
```

I've tried the suggestion at https://github.com/lightninglabs/lightning-app/issues/20#issuecomment-336269293 to generate a different tls certificate but it doesn't seem to make a difference.

**Comment by tanx** [comment]
Which branch are you guys on? Are you using the released version of the app, the master or v2 branch?

**Comment by Empact** [comment]
I'm on master.

**Comment by tanx** [comment]
@Empact are you using the current master of lnd in your PATH or the bundled binary under https://github.com/lightninglabs/lightning-app/tree/master/apps/desktop/bin ?

**Comment by Empact** [comment]
In my PATH - I'm running `lnd` directly in another window.

**Comment by Empact** [comment]
Oh btw the lnd commit was a few days old, not the current master, updating and retrying now.

**Comment by tanx** [comment]
Ok. I'm currently not watching if the current master of `lightning-app` breaks against `lnd`. Focusing on v2 branch right now. I've set up a CI build there that does grcp integration tests against the current lnd master. See: https://travis-ci.org/lightninglabs/lightning-app/builds/350124317#L3802

So my right now my suggestion is to use the release if you want to test the app: https://github.com/lightninglabs/lightning-app/releases

Or if you want to hack on the app use the v2 branch. See also: https://github.com/lightninglabs/lightning-app/blob/master/README.md#lightning-desktop-app
