### ISSUE TITLE
Better communicate balance after funding channels

### ISSUE THREAD

**Issue by orweinberger** [lightninglabs/lightning-app#202]
This is more of an enhancement. When I opened a channel and funded it, my balance at the left hand side went to 0. This is because the funding tx is not confirmed and therefore the funds in the change address are unconfirmed.

If you could somehow communicate the fact that we have funds that are unconfirmed heading our way, that would be great.

**Comment by Roasbeef** [comment]
Yeah the response returned does show the total balance (confirmed+unconfirmed), but the unconfirmed portion isn't _yet_ displayed within the application.

**Comment by LNBIG-COM** [comment]
I tested today iPhone version - unconfirmed on-chain funds are not viewed in balance till they will be confirmed. Ordinary users will be puzzled. And better to have ability to spend unconfirmed funds for opening channels (for wow effect). I see that this ticket as "added in v0.1". But i don't know what is fresh verdion of iPhone. May be this ticket should be reopened?
