### ISSUE TITLE
CPU usage through the roof

### ISSUE THREAD

**Issue by klauslovgreen** [lightninglabs/lightning-app#204]
I noticed that running the app on Mac the CPU usage remains at ~100%

<img width="671" alt="screen shot 2018-02-08 at 14 58 50" src="https://user-images.githubusercontent.com/9731754/35976511-a4499e24-0ce0-11e8-82ec-30ebd9eb4ec6.png">

MacOS 10.13.3
iMac 5k 4 GHz Intel Core i7 - 32GB

**Comment by Roasbeef** [comment]
Which version of the application are you running? We're aware of high resource utilization upon initial _launch_ of the application. There're known areas that need to be optimized as far as the initial channel graph verification. Once this initial bootstrap phase is over, utilization should return to a "normal" level.

**Comment by klauslovgreen** [comment]
I was using v0.1.4-alpha - will try the latest version today
