### ISSUE TITLE
New install needs further visual user feedback of chain sync before address creation possible

### ISSUE THREAD

**Issue by bretton** [lightninglabs/lightning-app#207]
### Description

New installation of 0.1.5 on a mac. When run for first time there is limited indication the application is 'catching up' except in the logs under Settings, and 'syncing to chain' message. This may be confusing for new users who would expect settings to be under Settings, and no idea it will take a while to sync to current.

Additionally no wallet funding address is available until fully synced, just a blank line with 'copied to clipboard' message when clicked.

The funding address becomes visible after the sync is completed.

### Steps to reproduce the behavior

Delete ~/Library/Application Data/Lnd/*

Download and install 0.1.5 by extracting the file and copying Lightning.app to /Applications. Select 'Replace' when prompted to overwrite any existing file.

Launch the application. Select the 'Add Funds' tab.

The address is empty, despite a QR code shown.

### Expected behavior

Visual prompt, or progress bar, with a message that syncing needs to complete before wallet addresses are available. 

No 'copied to clipboard' prompt if there is no address in the funding tab.

### Actual behavior

Empty address bar, 'copied to clipboard' message on blank data.

### Screenshot and/or logs if applicable

N/A

**Comment by bretton** [comment]
Slight correction: it would appear the sync process is still not finished
```
lnd: 2018-02-08 22:21:24.723 [INF] LNWL: Caught up to height 480000
```
so address creation is somewhat delayed from start, but not dependent on being fully synced, just partially so - if that is the cause of the delay.

**Comment by bretton** [comment]
Now it's fully synced, but I can no longer get an address, nor have faucet deposits arrived at addresses which were created earlier, after some delay.

Seems stuck on blank, or sometimes this message

https://i.imgur.com/QJ65uXc.png

**Comment by cheeseSnake** [comment]
Great comment, I was about to enter the same thing, I hope someone can add a splash at initial setup that one has to: 1, let it sync (estimated time of wait - xminutes), 2) send some btc to the wallet (estimated time of wait - y mins) 3) open channel (est time of wait -zmins), 4) make a lightning payment (should be instant)...something like that, which one would be able to open in the help menu or something?
