### ISSUE TITLE
Initializing Wallet / Opening Wallet...

### ISSUE THREAD

**Issue by fresheneesz** [lightninglabs/lightning-app#24]
I downloaded the windows version of this, ran the program, gave it network access when the popup came up. Next step is to send myself some sats from a faucet. I assume to do that I need to copy my address in the Receive section and send to it. Problem is that the address text line contains either "Opening Wallet..." or "Initializing Wallet" for like half an hour. Does it have to finish "Syncing to Chain" before I can use my wallet? I would have thought I could just have an address i could immediately use, even if the client couldn't see my transactions until its done syncing. 

Another problem, if I click the "Wallet Address" text, it copies the text in the address line (eg "Opening Wallet..."). Might want to disable copying the wallet address until there's an address to copy. 

The UI looks neat so far tho! Looking forward to testing it out once I can drink from a faucet!

**Comment by DaReaper** [comment]
Prevent copying 'Opening Wallet', 'Initializing Wallet' values in Wallet Address field and disable QR code until address available.

![Screenshot of copying wallet address](https://user-images.githubusercontent.com/567661/31584418-d01edb9c-b1cb-11e7-9355-61d26814f6d2.png)
![Screenshot of scanned QR code](https://user-images.githubusercontent.com/567661/31584431-3aac758c-b1cc-11e7-9896-3e57cff9c8e4.png)

**Comment by jcsmesquita** [comment]
Mine's also stuck on Initializing wallet in the Request tab. I was able to fund the wallet by grabbing the pub key in Settings though.

**Comment by fresheneesz** [comment]
@tanx Could you please comment on why you closed this?
