### ISSUE TITLE
lnd version is not compatible with the version of Windows

### ISSUE THREAD

**Issue by nm123github** [lightninglabs/lightning-app#242]
### Description
I'm attempting to run Lightning.exe on Windows 7 32bit PC. I get some error which says "lnd version is not compatible with the version of Windows."

### Steps to reproduce the behavior
npm run setup
npm run package-electron
cd C:\lightning-app\release\Lightning-win32-ia32\resources\app\bin\win32
lnd -version

### Expected behavior
I believe it should output a correct lightning version.

### Actual behavior
Get some error that says "lnd version is not compatible with the version of Windows.". Attached screenshot below.

### Screenshot and/or logs if applicable
![image](https://user-images.githubusercontent.com/8527474/37449926-4e0723a0-27e9-11e8-8a63-d1af1733b05b.png)

**Comment by Roasbeef** [comment]
IIRC, we actually build for 32-bit systems by default. At this point, we need to create a new version of the application as the underlying DNS has changed, so it would be difficult to bootstrap a new node unless it had existing data. 

You can actually recompile a version for you target OS if you wish.
