### ISSUE TITLE
Getting a "Windows protected your PC" error when running.

### ISSUE THREAD

**Issue by yigbau** [lightninglabs/lightning-app#25]
Not sure it's important at this stage, but getting an error when running on a windows system.

![screenshot_2](https://user-images.githubusercontent.com/32767123/31542660-99dde26e-b01b-11e7-9ff9-8934473d265a.png)

**Comment by bryanvu** [comment]
Thanks @yigbau. At some point we'll have to figure out how Windows registers apps, but it's a bit early at this point.
