### ISSUE TITLE
Problem syncing chain

### ISSUE THREAD

**Issue by galaxydoctor** [lightninglabs/lightning-app#29]
lnd: 2017-10-13 23:09:56.718 [WRN] LTND: open ../lnd.conf: Le fichier spécifié est introuvable. 2017-10-13 23:09:56.774 [INF] LTND: Version 0.3.0-alpha 2017-10-13 23:09:56.775 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0 2017-10-13 23:09:56.775 [INF] LTND: Primary chain is set to: bitcoin unable to create chain control: unable to create neutrino: EOF
lnd Error: unable to create neutrino: EOF
lnd: 2017-10-13 23:09:56.718 [WRN] LTND: open ../lnd.conf: Le fichier spécifié est introuvable. 2017-10-13 23:09:56.774 [INF] LTND: Version 0.3.0-alpha 2017-10-13 23:09:56.775 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0 2017-10-13 23:09:56.775 [INF] LTND: Primary chain is set to: bitcoin unable to create chain control: unable to create neutrino: EOF
lnd Error: unable to create neutrino: EOF

**Comment by bruceleeroy18** [comment]
Same issue: 

nd: 2017-10-14 08:38:55.153 [WRN] LTND: open ../lnd.conf: no such file or directory
lnd: 2017-10-14 08:38:55.159 [INF] LTND: Version 0.3.0-alpha
lnd: 2017-10-14 08:38:55.165 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0
lnd: 2017-10-14 08:38:55.166 [INF] LTND: Primary chain is set to: bitcoin
lnd: 2017-10-14 08:38:55.175 [INF] BTCN: Loaded 0 addresses from file '/home/browning/.lnd/data/simnet/bitcoin/peers.json'
lnd: 2017-10-14 08:39:01.955 [INF] LNWL: Opened wallet
lnd: 2017-10-14 08:39:05.997 [INF] LNWL: The wallet has been unlocked without a time limit
lnd: 2017-10-14 08:39:06.003 [INF] LTND: LightningWallet opened
lnd: 2017-10-14 08:39:06.013 [INF] LNWL: Started rescan from block 683e86bd5c6d110d91b94b97137ba6bfe02dbbdb8e3dff722a669b5d69d77af6 (height 0) for 11 addresses
lnd: 2017-10-14 08:39:06.015 [INF] LNWL: Catching up block hashes to height 0, this might take a while
lnd: 2017-10-14 08:39:06.017 [INF] LNWL: Done catching up block hashes
lnd: 2017-10-14 08:39:06.018 [INF] LNWL: Finished rescan for 11 addresses (synced to block 683e86bd5c6d110d91b94b97137ba6bfe02dbbdb8e3dff722a669b5d69d77af6, height 0)
lnd: 2017-10-14 08:39:06.039 [INF] RPCS: RPC server listening on 127.0.0.1:10009
lnd: 2017-10-14 08:39:06.043 [INF] HSWC: Starting HTLC Switch
lnd: 2017-10-14 08:39:06.046 [INF] NTFN: New block epoch subscription 2017-10-14 08:39:06.046 [INF] DISC: Authenticated Gossiper is starting
lnd: 2017-10-14 08:39:06.047 [INF] RPCS: gRPC proxy started at localhost:8080
lnd: 2017-10-14 08:39:06.047 [INF] CRTR: FilteredChainView starting
lnd: 2017-10-14 08:39:06.048 [INF] CRTR: Prune tip for Channel Graph: height=0, hash=<nil> 2017-10-14 08:39:06.049 [INF] CRTR: Filtering chain using 0 channels active 2017-10-14 08:39:06.049 [INF] NTFN: New block epoch subscription 2017-10-14 08:39:06.049 [ERR] DISC: unable to rebroadcast stale channels: error while retrieving outgoing channels: no graph edges exist
lnd: 2017-10-14 08:39:06.051 [INF] SRVR: Auto peer bootstrapping is disabled 2017-10-14 08:39:06.051 [INF] ATPL: Instantiating autopilot with cfg: (*main.autoPilotConfig)(0xc4204b1c80)({ Active: (bool) true, MaxChannels: (int) 5, Allocation: (float64) 0.6 })
lnd: 2017-10-14 08:39:06.055 [INF] ATPL: Autopilot Agent starting 2017-10-14 08:39:06.055 [INF] ATPL: Processing new external signal
lnd: 2017-10-14 08:39:06.056 [INF] CMGR: Server listening on [::]:9735
lnd: 2017-10-14 08:39:33.470 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-10-14 08:39:53.806 [INF] RPCS: [listchannels] fetched 0 channels from DB

**Comment by bryanvu** [comment]
@bruceleeroy18, it looks like you're running in simnet mode, so there's no peer bootstrapping. @galaxydoctor, if you see this behavior again, please reopen and we can debug further. Not sure what would be causing that error, and we'd need a bit more detail about your environment and such.
