### ISSUE TITLE
Get current exchange rates for BTC via an API

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#290]
e.g. https://blockchain.info/tobtc?currency=USD&value=1

**Comment by farhaanbukhsh** [comment]
Hey @tanx I would like to work on this, I have cloned the repo and set things up.

**Comment by tanx** [comment]
@farhaanbukhsh sorry saw your comment just now. I already implemented this in https://github.com/lightninglabs/lightning-app/commit/453e3ed8706bd9165bcde40d190ccc9d65444131
