### ISSUE TITLE
Handle lnd.conf gracefully

### ISSUE THREAD

**Issue by bryanvu** [lightninglabs/lightning-app#30]
Currently, in order to get the app's lnd to use the default lnd configuration and to ignore any other pre-existing lnd installations, the app is configured to look for lnd.conf in a directory where it shouldn't exist. This should be handled either by not looking for lnd.conf or having the app look for an lnd.conf in a different directory than lnd normally uses.

**Comment by autemox** [comment]
What directory is it looking for lnd.conf?  I cant get my lnd.conf file to register regardless of where I put it
