### ISSUE TITLE
Implement react-native grpc module for iOS

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#302]
Implement a react-native grpc module for iOS. See: https://facebook.github.io/react-native/docs/native-modules-ios.html

Ideally, the module would be a drop-in replacement for the desktop application's `GrpcAction` module that uses the react-native bridge on iOS instead of electron's `ipcRenderer`. The api is defined here: https://github.com/lightninglabs/lightning-app/blob/master/src/action/grpc.js

For now we can build the mobule in a separate git repo that's generated using `create-react-native-app`. See: https://facebook.github.io/react-native/docs/getting-started.html

After we know how we want to integrate the module, we can merge the iOS specific code in the `lightning-app` repo.

**Comment by halseth** [comment]
Initial react test app binding to lnd: https://github.com/halseth/lndReactTest

**Comment by halseth** [comment]
https://github.com/halseth/lndReactTest/blob/master/App.js#L68

**Comment by tanx** [comment]
So, having give this some more thought ... it looks like the integration requires only mocking the `ipc` module that get's passed into the `grpc.js` action constructor in:

https://github.com/lightninglabs/lightning-app/blob/41d86b0a171647d9546643f5d210880532e8a378/src/action/grpc.js#L11

The `ipc.js` action module is a very simple wrapper around electron`s IPC api:

https://github.com/lightninglabs/lightning-app/blob/41d86b0a171647d9546643f5d210880532e8a378/src/action/ipc.js

So basically we'd need a version called `ipc-mobile.js` that wraps the React Native bridge IPC with the same api. This way, we can reuse the Duplex stream multiplexing already implemented in `grpc.js` and share that code between desktop and mobile.

On the native module side, we'd need to provide a handler, that handles the multiplexed event like we do in the electron main process in `grpc-client.js`: 

https://github.com/lightninglabs/lightning-app/blob/41d86b0a171647d9546643f5d210880532e8a378/public/grpc-client.js#L100-L106
