### ISSUE TITLE
no controllable web interface

### ISSUE THREAD

**Issue by takaya-imai** [lightninglabs/lightning-app#313]
### Description
I installed lightning-app and booted web development server.
but I did not have controllable web interface like attached screenshot(no links to other pages, it's like just image) when I accessed it from browser.

This is correct installation?

### Steps to reproduce the behavior

* Environment
    * OS: Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-47-generic x86_64)
    * nodejs version: v10.0.0
    * npm version: 6.0.0

Reproduce steps are the same as installation procedure.

```
git clone https://github.com/lightninglabs/lightning-app.git
cd lightning-app
npm install
npm run electron-dev
```

### Screenshot and/or logs if applicable

<img width="1244" alt="2018-05-06 18 44 44" src="https://user-images.githubusercontent.com/2457450/39672015-947ba192-515d-11e8-8034-d8327acb0d56.png">

**Comment by tanx** [comment]
@takaya-imai have you followed the lnd installation instruction in the readme?

**Comment by takaya-imai** [comment]
yes, I already booted lnd . Backend of lnd is bitcoind.

**Comment by tanx** [comment]
You need lnd and btcd: https://github.com/lightninglabs/lightning-app#developing-locally

Also, the app is still in development. So we can't really support usage yet. Closing this for now.

**Comment by takaya-imai** [comment]
it needs that btcd is booted and it can use rpc? or it is enough to be able to use btcd command?
