### ISSUE TITLE
Display fee estimate for on-chain transaction

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#315]
This would require an additional grpc call `estimateFee`.

**Comment by halseth** [comment]
Added issue for the rpc call: https://github.com/lightningnetwork/lnd/issues/1212

**Comment by tanx** [comment]
I mean the design currenty supports only sending to a single address. But how is the app supposed to know how many inputs are required for the amount sent? Seems like something the lnd wallet will need to calculate anyway. So why duplicate that logic in JS?

**Comment by halseth** [comment]
I see, it totally makes sense not duplicating this in JS. So what should such an RPC interface return, and what information about the transaction is it given?

**Comment by tanx** [comment]
I would recommend the following:

```
estimateFee(amount: int64, num_outputs: int32) ->  satoshis: int64
```

If I understand correctly all transactions in lnd are segwit, so the amount (in satoshis) and the number of outputs (in this case 1) should be enough to estimate to fee in satoshis. lnd should be able to implicitly calculate if an additional `change` output is required if the input amounts don't match the exact output amount?
