### ISSUE TITLE
Test app build locally (Electron+lnd)

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#324]

**Comment by valentinewallace** [comment]
electron-builder doesn't support arch apparently, i'll try in a container like it says? 

<img width="631" alt="arch_native_builds_not_supported" src="https://user-images.githubusercontent.com/10647624/40582156-55c52b98-6121-11e8-89b4-ca1ecce8d739.png">

**Comment by tanx** [comment]
> i'll try in a container like it says?

Yeah sounds good
