### ISSUE TITLE
Error building 'boringssl' on linux

### ISSUE THREAD

**Issue by mrwhythat** [lightninglabs/lightning-app#33]
While running `npm run setup`, this error occurs:
```
make: Entering directory '/home/whythat/00_util/lightning-app/apps/desktop/node_modules/grpc/build'
  CC(target) Release/obj.target/boringssl/third_party/boringssl/crypto/bio/fd.o
../third_party/boringssl/crypto/bio/fd.c: In function ‘fd_ctrl’:
../third_party/boringssl/crypto/bio/fd.c:192:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
       num = 0;
       ~~~~^~~
../third_party/boringssl/crypto/bio/fd.c:193:5: note: here
     case BIO_C_FILE_SEEK:
     ^~~~
cc1: all warnings being treated as errors
make: *** [boringssl.target.mk:439: Release/obj.target/boringssl/third_party/boringssl/crypto/bio/fd.o] Error 1
```

GCC 7.2.0.
System Linux 4.9.51-1-MANJARO.

**Comment by mrwhythat** [comment]
It seems that the problem is in `grpc` v1.1.1, which depends on an older `boringssl` version, which doesn't have marks for switch-statement *fallthrough* behaviour.

**Comment by mrwhythat** [comment]
It could be fixed on the `grpc` side by updating git submodule for `boringssl`.

**Comment by Thann** [comment]
Even the latest release of grpc (1.6.6) uses an ancient version of boringssl that's over a thousand commits behind. Naïvely updating to the latest version has even worse errors =[

**Comment by mrwhythat** [comment]
For now, an easy way to bypass this until there's a more general solution, is to add `-Wno-implicit-fallthrough` to `cflags` field in `target-defaults` in `apps/desktop/node_modules/grpc/binding.gyp` file, which is pulled in with `npm run setup`.

**Comment by bryanvu** [comment]
Thanks @mrwhythat. I'll play around with this a bit. Building boringssl on Windows was a huge pain as well, and if this works, that would be a big plus.

**Comment by PowerInside** [comment]
This would most likely get fixed if the following is done:

~~1. https://boringssl.googlesource.com/boringssl/+/60931e2d8afff685f5460cf9a88469b96942849b (merged)~~
2. Submodule update PR (that contains above fix): https://github.com/grpc/grpc/pull/12922 (PR contributor seems to have bit of an issue here I think)
3. Bump grpc npm package to get the fixes.
