### ISSUE TITLE
lndReady is not trigger in production build

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#362]

**Comment by valentinewallace** [comment]
It triggers on Linux

**Comment by tanx** [comment]
> It triggers on Linux

Probably because you have a local `lnd.conf` setup? I'm wondering where the data dir is created when the production build is started?

**Comment by tanx** [comment]
Ok fixed this in https://github.com/lightninglabs/lightning-app/commit/ffbb92b88f1edfed669efcfb12642677e08dafb4
