### ISSUE TITLE
Linux production build broken upon electron-builder upgrade

### ISSUE THREAD

**Issue by valentinewallace** [lightninglabs/lightning-app#371]
We're now getting this error in Linux production builds: https://github.com/electron-userland/electron-builder/issues/2958

I ran `git bisect` and the bug started on the commit that upgraded us to electron-builder 20.15.1: 

![deepinscreenshot_select-area_20180606180333](https://user-images.githubusercontent.com/10647624/41072975-d6120ac2-69b5-11e8-8132-bcc2bf403ce0.png)

**Comment by valentinewallace** [comment]
@tanx  I'm thinking we should wait a bit to see if it gets fixed, but wondering if you think either downgrading or spending time trying to fix it ourselves is a better idea

**Comment by tanx** [comment]
@valentinewallace good catch! This PR https://github.com/lightninglabs/lightning-app/pull/374 reverts the upgrade. Does this fix the issue for you?
