### ISSUE TITLE
Display appropriate error message when balance is low in channel when paying

### ISSUE THREAD

**Issue by DaReaper** [lightninglabs/lightning-app#39]
Currently while attempting to make a payment and if the channel balance is low, then the error message displayed is "Payment route failure". This is the same message that's displayed even when a channel isn't created and connected. Instead I feel it would be more useful for the user if it were to display "Balance low on channel <channel id> to make payment"

**Comment by Argonath** [comment]
Receiving this same error message "Payment route failure" when trying to make a transaction, even though the channel is created, active and with sufficient balance.

**Comment by bryanvu** [comment]
When you get this error, are you seeing any errors in the logs/settings page? We're probably not handling the RPC response correctly.

**Comment by copumpkin** [comment]
I'm getting "payment route failure" right now on a channel that should have sufficient funding. No messages in logs. Is there anything I should try?

**Comment by copumpkin** [comment]
Oh never mind, the balance was indeed too low. It could be a lot friendlier though 😄

**Comment by alaniz3** [comment]
I have a similar issue. I think having a more appropriate and wider range of error messages would be useful.
