### ISSUE TITLE
ATPL: Autopilot Agent starting 2017-10-15 20:52:04.767 [ERR] DISC: Router rejected channel edge: pkScript mismatch

### ISSUE THREAD

**Issue by DaReaper** [lightninglabs/lightning-app#44]
I received this error in the log when I started the Lightning App. Any idea what this indicates?

`ATPL: Autopilot Agent starting 2017-10-15 20:52:04.767 [ERR] DISC: Router rejected channel edge: pkScript mismatch: expected 00209121200672048a92798683b436b498a36f5fa00a3504b680149fb60d14427c53, got 002083fa767a13244df8c33bb5f279a8b275f397d4a974eca76b43f88b0c0eae4e4c 2017-10-15 20:52:04.767 [ERR] FNDG: channel announcement failed: pkScript mismatch`

**Comment by Roasbeef** [comment]
Will be addressed by https://github.com/lightningnetwork/lnd/pull/364

**Comment by Roasbeef** [comment]
`v0.1.3` include the above fix. Closing.
