### ISSUE TITLE
Generate github release changelog from merged PRs

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#480]

**Comment by willpiers** [comment]
I found a couple of nice projects for this kind of thing. But it depends what kind of process you'd want to have. Using [conventional commit message](https://conventionalcommits.org/) would help make a nice release notes. [Commitizen](https://github.com/commitizen/cz-cli) is really helpful with this.

The best option i've seen is [semantic-release](https://github.com/semantic-release/semantic-release). It's quite popular and well-maintained, and it has a simple enough [setup process](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#automatic-setup-with-semantic-release-cli)

**Comment by tanx** [comment]
To clarify, we already have semantic versioning and CI builds with auto updates in place via travis/electron-builder/electron-updater. This issue is just to generate the change log from commit/PR messages and publish those in our github release notes: https://github.com/lightninglabs/lightning-app/releases

**Comment by willpiers** [comment]
Yep, understood. My main suggestion is that standardizing commit messages would make it easier/possible to have release notes automatically generated.

**Comment by erkarl** [comment]
As we don't have conventional commit messages in place I'm going to take a stab at implementing a primitive solution that just bundles all the commit messages together into an unsorted `CHANGELOG`.

**Comment by erkarl** [comment]
Really primitive solution is ready for review: https://github.com/lightninglabs/lightning-app/pull/536

**Comment by tanx** [comment]
Thanks @erkarl. Taking a look now.

**Comment by erkarl** [comment]
@tanx there's also:
* https://github.com/github-tools/github-release-notes
* https://github.com/conventional-changelog/conventional-changelog

...and some others that I already ruled out due to old releases. Looking into those.

**Comment by valentinewallace** [comment]
Was this not closed by https://github.com/lightninglabs/lightning-app/pull/536?

**Comment by tanx** [comment]
No. The script didn’t work last time I tested it. @erkarl does it work on your fork when you run the script after deployment?

**Comment by erkarl** [comment]
@tanx Sorry to hear it didn't work. I haven't setup Travis deployment on my fork. It successfully appended to a manually generated draft release, though.
