### ISSUE TITLE
Detect currency based on locale

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#486]
Electron has an api to detect the current locale: https://electronjs.org/docs/api/locales

N.B. this api needs to be called after the `ready` event in the main process to work correctly.

We can then send the locale string via IPC to the rendering process and detect the local currency using:
https://github.com/tadeegan/locale-currency

**Comment by willpiers** [comment]
I would like to give this issue a try - just letting others know

**Comment by tanx** [comment]
> I would like to give this issue a try - just letting others know

Awesome thanks!

**Comment by willpiers** [comment]
Got it working on a branch :) https://github.com/willpiers/lightning-app/commit/95683e26e8895ed47015837eaf894d6484f7e341

I'll take a look at tests tomorrow
