### ISSUE TITLE
Feature Request: Channel info

### ISSUE THREAD

**Issue by fresheneesz** [lightninglabs/lightning-app#50]
There should be some additional info you can access about a channel:
* **The channel address** - This one's really important. Is the CID a standard that other people (like eclair) should be using? Right now I can't even tell if I've already connected to an address because it doesn't show the address you're connected to.
* Whether the channel was created by autopilot or not
* Fees and fee rates
* Which transaction(s) funded/closed the channel
* Which lightning transactions have been sent through it
* How long its been open for (or date created)
* the transaction history/total volume for the channel
* If its closing, whether its waiting for a normal closing transaction to confirm vs waiting for a time-lock refund transaction to resolve

Would it also be possible to know how much of the network you can access through your channel(s)? It would be interesting/useful to know that your channels give you access to X% of the network of known endpoints, and which of your connections give you access to what percent. If channels are charging fees to create or send, that info would be useful to evaluate whether you should keep one open over another. 

From bryanvu: "Some of this data may be considered advanced, so this information should probably be split into a basic channel detail and a more advanced one."

**Comment by windsok** [comment]
Additionally, I think it would be good if the users can add their own custom labels to each channel. Once you have a few open it's hard to keep track of who they were opened too / what they were opened for. The user could optionally add this info in their own client-side only labels.

**Comment by fresheneesz** [comment]
@tanx Could you please comment on why you closed this?
