### ISSUE TITLE
Paying to your own Bitcoin Wallet address - Missing funds in wallet?

### ISSUE THREAD

**Issue by DaReaper** [lightninglabs/lightning-app#51]
I'm not sure what's happening here but when receiving Bitcoin (on-chain) funds to my Lightining app Bitcoin address, I had received the funds in 2 confirmations (both the tx id and the wallet balance updated right after 2 confirmations) 

I tried to pay my Bitcoin Wallet address generated in the lightning app (I know, that's dumb but I was experimenting) and I've waited 2 transaction confirmations. The transactions have confirmed but I haven't received the funds I had sent to myself. 

Wallet balance and transaction before paying myself: In this image you can see the log that the new address has been generated by the wallet and I've sent coins to it.

![image](https://user-images.githubusercontent.com/567661/31613909-24f4ff9e-b2a2-11e7-96bc-c69e6e51d95f.png)

Wallet balance and transactions after paying myself:

![image](https://user-images.githubusercontent.com/567661/31613880-11006dde-b2a2-11e7-8193-a70a76497121.png)

Here's the tx id: https://testnet.smartbit.com.au/tx/7c200913e9ecb63dee1868b638a8850713a3906751be4c9467dd262ae8c185cc

and one more tx (this is the first time I tried it and haven't received this one either): https://testnet.smartbit.com.au/tx/fb2c4c2dae3c2886ee3e1280c6657bad0a39d94eb6244b439ba8706900749d6b

**Comment by Roasbeef** [comment]
Related to https://github.com/lightninglabs/neutrino/pull/23
