### ISSUE TITLE
Cannot serve compact filters. 

### ISSUE THREAD

**Issue by rstmsn** [lightninglabs/lightning-app#511]
Hi Folks,

I've spun up 'lightning-app-0.2.0-prealpha.21-mac', recorded seed and created a wallet. 
App is at the home screen, showing zero balance and 'syncing to chain' in the top tool bar. 
I was following the logs, and the sync seemed to be up as far as the current testnet block height. I made a transaction to fund the wallet, which now has 6+ confirmations, yet the wallet balance still appears as zero. The settings-> logs reads as follows. Any thoughts on why I have an on-going 'syncing to chain' status, and zero balance, despite funding ?

LOGS
30:05.589 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:30:05.590 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:30:10.595 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:30:10.595 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:30:15.614 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:30:15.615 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:30:20.617 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:30:20.617 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:30:25.623 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:30:25.623 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:30:31.591 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:30:31.592 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:30:36.650 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:30:36.650 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:30:41.657 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:30:41.657 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:30:46.663 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:30:46.663 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:30:51.672 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:30:51.672 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:30:56.677 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:30:56.678 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:31:01.680 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:31:01.680 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:31:06.686 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:31:06.687 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:31:11.688 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:31:11.688 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:31:16.694 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:31:16.694 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:31:21.697 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:31:21.697 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:31:26.699 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:31:26.699 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:31:31.703 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:31:31.703 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:31:36.708 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:31:36.708 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:31:42.067 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:31:42.067 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:31:47.433 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:31:47.433 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:31:56.135 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:31:56.136 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:32:01.138 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:32:01.138 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:32:06.400 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:32:06.400 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:32:11.436 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:32:11.436 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:32:16.438 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:32:16.438 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:32:23.449 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:32:23.450 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:32:28.917 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:32:28.917 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:32:52.564 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:32:52.564 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:33:26.314 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:33:26.314 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:33:35.169 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:33:35.169 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:33:57.101 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:33:57.101 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:34:12.800 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:34:12.800 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:34:23.206 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:34:23.206 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:34:32.139 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:34:32.139 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:34:37.224 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:34:37.224 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:34:44.149 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:34:44.149 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:34:49.152 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:34:49.152 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:34:54.157 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:34:54.157 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:36:03.931 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:36:03.931 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:36:13.511 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:36:13.511 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:36:42.193 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:36:42.193 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:36:52.447 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:36:52.448 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:37:06.959 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:37:06.959 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:37:12.604 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:37:12.604 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:37:25.913 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:37:25.913 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:37:43.398 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:37:43.398 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:37:54.044 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
2018-08-11 18:37:54.044 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:38:07.240 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:38:07.240 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:38:13.256 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:38:13.256 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:38:23.868 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:38:23.868 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2018-08-11 18:38:42.561 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2018-08-11 18:38:42.561 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)

**Comment by tanx** [comment]
> I made a transaction to fund the wallet, which now has 6+ confirmations, yet the wallet balance still appears as zero.

This should be addressed in #516.

**Comment by Roasbeef** [comment]
So the version of `btcd` you're using isn't the latest version that's able to serve filters as neutrino requires. You'll need to update to the latest version of `btcd` master if you want to be able to sync against your local node.

**Comment by tanx** [comment]
@Roasbeef thanks. Closing this for now.
