### ISSUE TITLE
rename ID to payment hash for lightning payments 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/lightning-app#526]
For Lightning payments, we show the users this atm: 
<img width="446" alt="screen shot 2018-08-15 at 3 10 35 pm" src="https://user-images.githubusercontent.com/998190/44176471-c4b0d400-a09e-11e8-8d1d-d890be8d8837.png">

The ID nomenclature is a bit confusing here, as users _generally_ know this field as the "payment hash" 
and it may be used in the future to give a merchant an invoice ID for support, etc.

**Comment by tanx** [comment]
> users generally know this field as the "payment hash"

When you mean "users" are you referring to the 100 enthusiasts on our slack? We should be careful to use that audience as a proxy for a wider bitcoin user audience. I doubt even advanced bitcoiners know what a `paymant hash` is.

Having said that I agree that using the same terminology `ID` as for on-chain transactions. Is confusing.

> and it may be used in the future to give a merchant an invoice ID for support

What about using `Invoice ID` for lightning transactions and `Transaction ID` for on-chain?

**Comment by erkarl** [comment]
+1 for using `Invoice ID` and `Transaction ID`.
