### ISSUE TITLE
rename ID to txid for on-chain payments 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/lightning-app#527]
For on-chain payments atm we show the users this: 
<img width="466" alt="screen shot 2018-08-15 at 3 10 46 pm" src="https://user-images.githubusercontent.com/998190/44176507-f164eb80-a09e-11e8-8835-63bb26a824cb.png">

For _existing_ Bitcoin users, this can be a bit confusing as they're used to txid referring to the ID of the payment. IMO, this should be changed to txid to be more in line with the existing wallets/explorers out there.

**Comment by tanx** [comment]
> For existing Bitcoin users, this can be a bit confusing as they're used to txid referring to the ID of the payment. IMO, this should be changed to txid to be more in line with the existing wallets/explorers out there.

I took a look at how other wallets display the ID. Breadwallet calls it `Transaction ID` and Coinbase links to a Block Explorer with the terminology `Show Transaction`.

Since the attribute is under `Transaction Details` in this modal, calling it `ID` seems to be pretty in line with other wallets?
