### ISSUE TITLE
Transaction list with lots of entries is slow

### ISSUE THREAD

**Issue by erkarl** [lightninglabs/lightning-app#544]
### Description
Transaction list with lots of entries is very janky.

### Steps to reproduce the behavior
Using simnet mine to block 2400 so that the transaction list has many transaction list items.

### Expected behavior
Transaction list opens immediately and incrementally loads more entries when there's enough room in the performance budget. The maximum render time should be 1000 (second) / 60 (frames per second) = ~16.67ms so that there's no noticeable slow down for the end user.

### Actual behavior
On a powerful desktop CPU (i7-7700k) clicking on the transactions results in a noticeable delay - making the app feel slow.

### Screenshot and/or logs if applicable
![screen shot 2018-08-21 at 10 45 21](https://user-images.githubusercontent.com/1056569/44387852-556c3180-a52f-11e8-9cdc-b82aedbb5ed1.png)

**Comment by tanx** [comment]
@erkarl thanks for benchmarking. Paging transactions for lnd is in the pipeline. In the meantime we could mitigate the performance issue by calling `return all.slice(0, 100)` when computing `store.computedTransactions`.
