### ISSUE TITLE
Make integration tests more reliable by removing sleeps etc.

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#546]

**Comment by valentinewallace** [comment]
@tanx Does this just refer to: [this](https://github.com/lightninglabs/lightning-app/blob/master/test/integration/action/action-integration.spec.js#L110), [this](https://github.com/lightninglabs/lightning-app/blob/master/test/integration/action/action-integration.spec.js#L110), and [this](https://github.com/lightninglabs/lightning-app/blob/master/test/integration/action/action-integration.spec.js#L229) or also naps like [these](https://github.com/lightninglabs/lightning-app/blob/master/test/integration/action/action-integration.spec.js#L385)?

**Comment by tanx** [comment]
Don't remember why I opened this issue. Tbh I don't really see a need to remove sleeps as integration tests are pretty stable already. Closing this for now
