### ISSUE TITLE
Unable to Copy Deposit Address

### ISSUE THREAD

**Issue by cfromknecht** [lightninglabs/lightning-app#547]
### Description
I'm having trouble copying the deposit address, both after seed confirmation and after the wallet has fully synced from the Add Funds page.  The copy button appears to be working visually, the button depresses, and then returns to a normal state.  The "Copied to Clipboard" ntfn appears the first time, but then never disappears.

Mac OS 10.13.5
lnd commit: 6c903393e50bd3c60db533102d5f681aa407d01b (master at time of writing)

### Steps to reproduce the behavior
1. Build from master:
```
npm i
cp $GOPATH/bin/lnd ./assets/bin/darwin
npm run electron-pack
```

2. Start application
```
./dist/mac/Lightning.app/Contents/MacOS/Lightning --btcd.rpcuser=kek --btcd.rpcpass=kek
```

3. Finish seed recovery/confirmation

4. Copy deposit (fails to copy, but says copied to clipboard, copied ntfn remains)

5. Click through Done, and wait for sync

6. Navigate to Add Funds page

7. Same as step 4

### Expected behavior
Expected to have deposit address in clipboard after step 4 and 7. Also though I might be able to circumvent the copying error by highlighting the address, but text selection is disabled for the address.

### Actual behavior
Retained my previously clipboard entry

### Screenshot and/or logs if applicable

Picture after trying to copy multiple times, but ntfn never disappears.
<img width="1920" alt="screen shot 2018-08-21 at 4 08 08 pm" src="https://user-images.githubusercontent.com/2013993/44433898-3f756580-a55d-11e8-948f-1924458d4607.png">

**Comment by cfromknecht** [comment]
Was able to figure out the issue. I was running the executable from inside tmux, which captures clipboard copies. I tried starting the app in a different tab and everything worked.

**Comment by erkarl** [comment]
@cfromknecht awesome - fortunately this won't be an issue for the average user :).

**Comment by tanx** [comment]
> Was able to figure out the issue. I was running the executable from inside tmux, which captures clipboard copies. I tried starting the app in a different tab and everything worked.

Nice.

**Comment by joostjager** [comment]
@tanx I have this issue too: copied to clipboard appears, but nothing on the clipboard.

- Ubuntu 16.04 LTS
- Running `Lightning-linux-x86_64v0.2.0-prealpha.25.AppImage` from a terminal window (not tmux).

**Comment by tanx** [comment]
Yep. See https://github.com/lightninglabs/lightning-app/issues/614
