### ISSUE TITLE
Synching to chain - lnd-error: fatal error: concurrent map writes

### ISSUE THREAD

**Issue by DaReaper** [lightninglabs/lightning-app#55]
I was attempting my 3rd re-sync to the testnet blockchain after I had encountered a panic rollback error (similar to the issue mentioned here https://github.com/lightninglabs/lightning-app/issues/32). I had attempted the workaround referenced there, but after my 3rd sync successfully completed, after a while I had encountered the following error when it started to sync to chain again: (check .txt file attached for extensive error log. It's a long one)

`lnd Error: fatal error: concurrent map writes
lnd Error: goroutine 4841 [running]: runtime.throw(0xdbff6b, 0x15) /usr/local/go/src/runtime/panic.go:596 +0x9c fp=0xc04368de18 sp=0xc04368ddf8 runtime.mapdelete(0xc96d20, 0xc042246300, 0xc04368df60) /usr/local/go/src/runtime/hashmap.go:612 +0x329 fp=0xc04368de80 sp=0xc04368de18 main.(*server).OutboundPeerConnected(0xc042000900, 0xc0429d9130, 0x1349320, 0xc0425ce980) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/server.go:1229 +0x36e fp=0xc04368df98 sp=0xc04368de80 main.(*server).OutboundPeerConnected-fm(0xc0429d9130, 0x1349320, 0xc0425ce980) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/server.go:326 +0x4f fp=0xc04368dfc8 sp=0xc04368df98 runtime.goexit() /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc04368dfd0 sp=0xc04368dfc8 created by github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr.(*ConnManager).connHandler
lnd Error: /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/vendor/github.com/roasbeef/btcd/connmgr/connmanager.go:236 +0x3b1 goroutine 1 [chan receive, 10 minutes]: main.lndMain(0x0, 0x0) /Users/bryanvu/work/src/github.com/lightningnetwork/lnd/lnd.go:399`

**The entire error**: [lnderror.txt](https://github.com/lightninglabs/lightning-app/files/1390560/lnderror.txt)

Operating system: Windows 7 Enterprise 64 bit

**Comment by Roasbeef** [comment]
This should be fixed in the latest release of the app as a result of https://github.com/lightningnetwork/lnd/pull/343

**Comment by DaReaper** [comment]
Closing this issue since I'm not longer receiving this error on the new alpha release version - 0.1.1
