### ISSUE TITLE
Set a 1 minute timeout when sending a lightning payment and display "no route found" screen

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#555]
If no route is found, payments can take forever and the wait spinner just sits there and the app is unresponsive.

We could set a timeout before calling the `sendPayment` grpc api in the `payLightning` payment action. If the timeout is reached, we can display the "no route found" view.

This approach would make the user experience more responsive. The downside is if the user retries the payment a second time and the first payment does eventually go through in the background, he will have paid twice.

**Comment by erkarl** [comment]
If we always display the `no route found` error after a certain timeout it would assume it's the only cause. What about calling it `payment failed` instead?

Think the problem of paying twice will go away once there's a restriction of not being able to pay the same invoice twice on the implementation level.

**Comment by tanx** [comment]
> If we always display the no route found error after a certain timeout it would assume it's the only cause. What about calling it payment failed instead?

We already had a design implemented for ` no route found `. We just haven't integrated it until now. No strong opinion on the wording.

> Think the problem of paying twice will go away once there's a restriction of not being able to pay the same invoice twice on the implementation level.

@Roasbeef can lnd pay the same invoice twice?

**Comment by valentinewallace** [comment]
@tanx I asked @wpaulino, it does not allow paying the same invoice twice anymore.
