### ISSUE TITLE
Neutrino never finishes syncing, only after restart

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#558]
The app keeps polling the `getInfo` api even it has caught up to the current block height. @halseth and me have debugged the issue and it seems there is a deadlock caused by calling `NewAddress` before neutrino has finished syncing.

I've tried to work around the issue by deferring `NewAddress` until after neutrino is synced, but this makes the app unusable in the initial onboarding since we need to display the wallet address in the deposit screen before syncing neutrino the first time.

**Comment by halseth** [comment]
Neutrino issue: https://github.com/lightninglabs/neutrino/issues/91
