### ISSUE TITLE
[ERR] LNWL: Failed to process consensus server notification

### ISSUE THREAD

**Issue by DaReaper** [lightninglabs/lightning-app#56]
Had received this error when I was synchronizing the chain once again from the beginning. I had restarted the application and the sync continued until completion.

Operating System: Windows 7 Enterprise 64 bit
Lightning app version: Happening on both 0.1.0 Alpha and 0.1.1 Alpha
```
lnd: 2017-10-17 13:28:19.290 [INF] BTCN: Processed 1 block in the last 20m0.71s (height 1210419, 2017-10-17 13:28:17 +0530 IST)

lnd: 2017-10-17 13:28:19.777 [ERR] LNWL: Failed to process consensus server notification (name: `blockconnected`, detail: `failed to store sync information 00000000570271921acfd04558e00ccad4b67a1ccf84f7e2164ee83a427ab905: failed to fetch block hash for height 1210418: couldn't get hash from database`)
```

**Comment by aakselrod** [comment]
Do you have any logs from before this occurred? If so, that would be very useful in troubleshooting the issue.

**Comment by DaReaper** [comment]
@aakselrod I do not have access to the logs during the time this had occurred any more since I had deleted the whole data and logs folder (deleted logs by mistake) to re-sync the chain from scratch, after which I hadn't faced this issue anymore. I had opened up another issue though which I closed since it was a duplicate of this and do not have logs for that either (https://github.com/lightninglabs/lightning-app/issues/65)

**Comment by aakselrod** [comment]
I believe we've figured this out with someone else, @DaReaper. It should be fixed by https://github.com/lightninglabs/neutrino/commit/dd2a98fb21bd13f70ec9e64a4bfec42093a732ba which will be included in the next app release.

**Comment by Joohansson** [comment]
I saw this on windows right now but it synced with network after restarting the app with admin privileges. Don't know if it's needed.
