### ISSUE TITLE
Handle lnd startup failure/crashes

### ISSUE THREAD

**Issue by valentinewallace** [lightninglabs/lightning-app#562]
Currently, scenarios where `lnd` startup failures or crashes are not handled by the app logic aside from logging an error message on startup failure. 

I'd suggest adding a notification and a "restart network connection" button, or just a notification saying we're restarting our network connection and some functionality may be temporarily unavailable.

**Comment by tanx** [comment]
What's the difference to having the user restart the app manually? The user would need to input the wallet password anyway.

**Comment by valentinewallace** [comment]
Good point, so maybe notification with a restart button is the way to go?

**Comment by tanx** [comment]
Or we could just fix the issue when we find it 🙃 FWIW I haven‘t experienced a single crash yet. And I‘m probably the app‘s biggest power user 😃 So not sure it‘s worth prioritising right now.

**Comment by valentinewallace** [comment]
Haha, not saying you're wrong but [this commit](https://github.com/lightninglabs/lightning-app/commit/02acfadfff0250ef7d30ae4376bff285a9563e7c) from today was a hotfix for just such a problem..

**Comment by tanx** [comment]
Yeah? The fix is in right? So kinda proves my point, no?

**Comment by valentinewallace** [comment]
True, I'm good to de-prioritize this for now.

**Comment by tanx** [comment]
Closing this for now
