### ISSUE TITLE
Btcwallet is not always showing change output as unconfirmed when opening channels

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#567]

**Comment by valentinewallace** [comment]
@tanx Do you have any more details on this? 

Trying to understand: does this mean that sometimes change output is shown as confirmed immediately when it actually hasn't been confirmed on the blockchain?

**Comment by tanx** [comment]
Tbh I don't remember exactly what the issue was. @Roasbeef was this addressed or is there an issue in lnd?

**Comment by tanx** [comment]
Awesome. Thanks for the update.
