### ISSUE TITLE
Keep column titles at the top of the page on scroll down

### ISSUE THREAD

**Issue by valentinewallace** [lightninglabs/lightning-app#611]
Currently, if a user has a lot of channels/transactions and they scroll down on the page, the column titles disappear. Instead, the titles should stay at the top of the page while the list of channels scrolls underneath. 

before scroll:
![deepinscreenshot_select-area_20180905124356](https://user-images.githubusercontent.com/10647624/45117042-6a3ced80-b109-11e8-994d-c14eab8e6cd5.png)

after scroll:
![deepinscreenshot_select-area_20180905124408](https://user-images.githubusercontent.com/10647624/45117057-745eec00-b109-11e8-9009-0a098e63f07a.png)

**Comment by tanx** [comment]
Can you post a screenshot?
