### ISSUE TITLE
Broadcast of the channel funding tx requires a restart of the app

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#651]
Once the deposit transaction comes in, autopilot starts opening channels, but the funding tx isn't listed by the `gettransactions` grpc api and it isn't broadcasted. Only after a restart of the app is the tx broadcasted.

Probably related to #650

**Comment by tanx** [comment]
Retested this today. Seems fixed in the current build.

**Comment by valentinewallace** [comment]
Confirmed with the lnd side that this issue has not yet been fixed, reopening.

**Comment by molxyz** [comment]
@tanx 
Per your request, here's some log for one of my "pending" channels:  https://hastebin.com/raw/bosunalome

The TXID is  62396698407f966a04cf87646601e267b843794a2e5f55be2ec4c73b40f42396
Pubkey of the remote node:  03b1cf5623ca6757d49de3b6e2b9340065ba991c75b8e9cd8aec51dc54322cbd1d

If you need more info, please let me know.  Thanks.

**Comment by tanx** [comment]
@Roasbeef this issues also seemed to be resolved with https://github.com/lightninglabs/lightning-app/commit/c8fea7e63dd6f4e0628cef21469e9712206f41ff

Just a coincidence while while testing this time or was this fixed in lnd?

**Comment by tanx** [comment]
This is fixed in v0.4.0-alpha of the app (lnd v0.5.2-beta)

**Comment by tanx** [comment]
Still got this bug again.

**Comment by tanx** [comment]
The issue was partly mitigated in the new neutrino version. But still need to wait ~20 min (1-2 blocks) for funding tx to be broadcast.

**Comment by tanx** [comment]
@Roasbeef been testing this with a local btcd node to minimize latency to the neutrino client. Seems like transactions are broadcast instantly. So maybe it's just a matter of increasing the timeout issue in neutrino?

**Comment by tanx** [comment]
This is fixed in app `v0.4.5`. TX broadcasted instantly. Maybe due to lag running under poor hotel wifi. cc @wpaulino @Roasbeef
