### ISSUE TITLE
Add functionality to transfer funds out

### ISSUE THREAD

**Issue by erkarl** [lightninglabs/lightning-app#656]
I’ve been trying to transfer funds out from the Lightning App’s wallet, but as soon as I close channels, the autopilot opens up new ones. This effectively makes transferring funds out of Lightning App impossible for novice users.

We could:
1. Add autopilot configuration to the settings (related to: https://github.com/lightninglabs/lightning-app/issues/13). While this approach is the easiest it will definitely not make sense for beginners.
2. Include max amount (`channelbalance` + `walletbalance`) the user can send under bitcoin/on-chain transaction view. If the user enters an amount that is greater than the current `walletbalance` the application could disable the autopilot and close channels under the hood to make the transaction possible.

**Comment by tanx** [comment]
Good point. We should add a feature to transfer funds out which:

1. Deactivates autopilot
2. Closes all channels
3. Notifies the user once all channels are closed

**Comment by tanx** [comment]
Closing in favor of https://github.com/lightninglabs/lightning-app/issues/865
