### ISSUE TITLE
Release signing key is not trusted

### ISSUE THREAD

**Issue by sbp** [lightninglabs/lightning-app#66]
The hashes of the [0.1-alpha](https://github.com/lightninglabs/lightning-app/releases/tag/0.1-alpha) builds are recorded in a file called `manifest-0.1-alpha.txt`, which has the signature `manifest-0.1-alpha.txt.gpg`. This has been signed by the RSA key with the short ID `964EA263DD637C21`. I was able to `recv-keys` this and verify the signature using the RSA key with the fingerprint `65317176B6857F98834EDBE8964EA263DD637C21`, but `gpg` rightly complains that this key is not trusted:

```
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner
```

This could be *anybody's key*. There is no indication that it belongs to Olaoluwa Osuntokun as the key metadata says, nor that Olaoluwa Osuntokun is an authorised Lightning Labs developer and release signer, etc. I could not find any record of this key outside of a few Github mentions of it; nobody else has signed it. It is not part of the [web of trust](https://en.wikipedia.org/wiki/Web_of_trust).

You should either remove the release hash manifest signature, or incorporate the signing key into the web of trust somehow, and preferably provide instructions to users on how to validate this fact for themselves once the key is trusted.

**Comment by Roasbeef** [comment]
This is the key I also sign all [releases of `lnd`](https://github.com/lightningnetwork/lnd/releases) and [commits of lnd with](https://github.com/lightningnetwork/lnd/commit/d8949174589c6a92073a602ec123c99309284053). 

> s, nor that Olaoluwa Osuntokun is an authorised Lightning Labs developer and release signer, etc

It's easy to verify that [I'm a member of our organization on Github](https://github.com/orgs/lightninglabs/people), and also present [on our official website](https://lightning.engineering/team.html). Agreed that we can make it much easier to verify my identity. 

I'll update my [keybase profile](https://keybase.io/roasbeef) (which attests to my uniform online identity) with the key as well. 

> and preferably provide instructions to users on how to validate this fact for themselves once the key is trusted

Definitely, the next release will also include instructions on how to verify the integrity and authenticity of the downloaded binaries.

**Comment by sbp** [comment]
Please give an explanation when closing issues, especially when closing issues labelled "security".

In this case it seems that `Lightning.app` is now signed with a key that macOS Gatekeeper recognises as valid, which means that it is trusted in Apple's ad hoc CA style authority chain. You can confirm this from the command line:

```
$ codesign -vv Lightning.app
Lightning.app: valid on disk
Lightning.app: satisfies its Designated Requirement
```

And a prose description of the authority chain can also [be obtained](https://apple.stackexchange.com/questions/321473):

```
$ codesign -dvvv Lightning.app 2>&1 | grep Authority
Authority=Developer ID Application: Bryan Vu (643LLJCYK9)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
```

It's not clear how to get the full `643LLJCYK9` public key and certificate, but in any case this makes it clear that it's been signed by the Developer ID Certification Authority, so you know who to blame if the app is not secure. Bryan Vu is presumably @bryanvu.

The signed manifest went away after `v0.1.5-alpha`, i.e. starting with `0.2.0-prealpha.8`.

**Comment by tanx** [comment]
I was just going through old issues for v0.1.x before we release the new v0.2.x. v0.1.x is no longer usable.

> In this case it seems that Lightning.app is now signed with a key that macOS Gatekeeper recognises as valid, which means that it is trusted in Apple's ad hoc CA style authority chain.

Yes, we switched to OS native CAs and will be signing our application builds.
