### ISSUE TITLE
Getting node info failed

### ISSUE THREAD

**Issue by Tigerix** [lightninglabs/lightning-app#660]
First start - setting up Lightning with recovery seed and password - after 10 minutes block header download stops - progress circle keeps spinning.

Windows 10

[2018-09-11 21:37:15.881] [error] Getting node info failed { code: 12,
  details: 'unknown service lnrpc.Lightning',
  metadata: { _internal_repr: {} } }

[log.log](https://github.com/lightninglabs/lightning-app/files/2372525/log.log)
[log.old.log](https://github.com/lightninglabs/lightning-app/files/2372530/log.old.log)

**Comment by valentinewallace** [comment]
What platform are you running on?

**Comment by Tigerix** [comment]
Windows 10

**Comment by Roasbeef** [comment]
Did you have an existing `lnd` node running? Looks like lnd is hasn't yet been unlocked, but it's trying to access the normal RPC?

**Comment by Tigerix** [comment]
I have Zap installed but not running... Also some older version of eclair and lightning labs app, also not running intentionally.
