### ISSUE TITLE
Truncate invoice note with "..." if it's too long in lightning confirm view

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#661]

**Comment by erkarl** [comment]
@tanx isn't `NamedField` that is being used to display the invoice note already doing this?

![screen shot 2018-09-12 at 15 26 27](https://user-images.githubusercontent.com/1056569/45424857-72180700-b6a0-11e8-84b7-4e063d35a491.png)
![screen shot 2018-09-12 at 15 20 54](https://user-images.githubusercontent.com/1056569/45424865-76dcbb00-b6a0-11e8-8e37-8f54efadfa4c.png)

**Comment by tanx** [comment]
@erkarl oh yes. Cool! Mission accomplished 🏖
