### ISSUE TITLE
Windows 10: Copy address to clipboard does not work

### ISSUE THREAD

**Issue by sondreb** [lightninglabs/lightning-app#677]
On the funding page, I click the button to copy address to clipboard. Then I clicked the Done button.

When I wanted to paste the address in Notepad, there was nothing there.

Now I'm "stuck", as the new app does not support navigation back, and there is no way to generate a new (or see the same) deposit address.

From this screen, it should be possible to back again to the address:

![image](https://user-images.githubusercontent.com/309938/45497280-add1d000-b777-11e8-8c31-9e3b30b92eac.png)

**Comment by sondreb** [comment]
Exit and re-open the app, shows the normal full UI, so that is a temporary solution.

**Comment by sondreb** [comment]
And I did another attempt at copy to clipboard, this time it worked. So either I'm mistaken, that clipboard always works, or clipboard copy does not work on the initial setup.

**Comment by erkarl** [comment]
I cannot reproduce this on a fresh Windows 10 and Lightning App install. The copy during the initial setup worked.

**Comment by sondreb** [comment]
I deleted my AppData folder for "lightning-app", and can confirm that copy worked fine. I also verified that address was still in clipboard after I navigate away from address page.

I would still suggest that there are some way of getting back to the initial address for first-time-setup. I'll close this issue.
