### ISSUE TITLE
App comes up blank after first run

### ISSUE THREAD

**Issue by sbp** [lightninglabs/lightning-app#68]
I built commit `01d61006c11aca7c5ab04a0651bb2d61bed74d0c` from source using the instructions in the README, namely:

```
git clone https://github.com/lightninglabs/lightning-app.git
cd lightning-app
npm run setup
npm start
```

This worked fine, the Electron app opened and the UI was as expected. I then closed the app and opened it again with `npm start`, but this time the Electron app window was blank. I tried closing it and starting once again using `npm start` but the problem persisted.

OS: macOS 10.12.6.

**Comment by thejourneydude** [comment]
What is your terminal output telling you?

**Comment by sbp** [comment]
The full output:

```
$ npm start

> lightning-app@0.1.1 start /path/to/lightning-app
> cd apps/desktop && npm start -s


 ___       ________       ________  ________  ________    
|\  \     |\   ___  \    |\   __  \|\   __  \|\   __  \   
\ \  \    \ \  \\ \  \   \ \  \|\  \ \  \|\  \ \  \|\  \  
 \ \  \    \ \  \\ \  \   \ \   __  \ \   ____\ \   ____\ 
  \ \  \____\ \  \\ \  \   \ \  \ \  \ \  \___|\ \  \___| 
   \ \_______\ \__\\ \__\   \ \__\ \__\ \__\    \ \__\    
    \|_______|\|__| \|__|    \|__|\|__|\|__|     \|__|    


[webpack] Building...
[webpack] webpack built 3e9b823e17c2b65141db in 13866ms
^C[webpack] npm run start-webpack exited with code 0
--> Sending SIGTERM to other processes..
[electron] npm run start-electron exited with code 0
```

The `^C` is my input, after waiting much longer than it took to load first time.

**Comment by thejourneydude** [comment]
Have you tried `Cmd + R`? This issue is mentioned in the [Readme](https://github.com/lightninglabs/lightning-app#errors).

**Comment by thejourneydude** [comment]
After some investigation, all evidence suggests this is caused by a race condition between Webpack and Electron during `npm start`. 

Expect a PR with this fix in the next day or two.
