### ISSUE TITLE
Copied to clipboard message is not readable when the wallet has the default window size

### ISSUE THREAD

**Issue by philippgille** [lightninglabs/lightning-app#682]
### Description

The "Copied to clipboard" message is not readable when clicking on the button to copy the address to the clipboard. This mainly applies to the initial setup screen. See below for comparing screenshots.

### Steps to reproduce the behavior

1. Download and install `Lightning-win32v0.2.1-alpha`
2. Don't resize the app's window
3. Go through the initial screens until "YOUR SHINY NEW ADDRESS"
4. Click on the small button with the icon to copy the address to the clipboard

### Expected behavior

A readable notification of the successful operation in some place that's not in front of other important GUi elements

### Actual behavior

A notification right across the QR code, with white letters and white background, so not readable.

### Screenshot and/or logs if applicable

![45584725-416ee200-b8d9-11e8-8fff-dfc313336048](https://user-images.githubusercontent.com/170670/45584809-631c9900-b8da-11e8-9306-0534b88b51d7.png)

After the initial setup, when clicking on "Add coin" on the top of the main screen, it's better, but still not perfect:

![capture](https://user-images.githubusercontent.com/170670/45584818-7def0d80-b8da-11e8-8559-4b63b6ad8f61.PNG)

**Comment by philippgille** [comment]
The text is a bit misplaced as well, see for example the "g" of "exchange" is cut off a bit, too. Same with the "y" in "Only".

**Comment by cdelargy** [comment]
Duplicated this issue on 0.2.1-alpha on OSX.

**Comment by philippgille** [comment]
Please see my comment on the PR, and please also consider my comment above (https://github.com/lightninglabs/lightning-app/issues/682#issuecomment-421545077), which isn't addressed in the PR, while I think the cut off text should be fixed as well.
