### ISSUE TITLE
Opening Autopilot Channel fails

### ISSUE THREAD

**Issue by haukehess** [lightninglabs/lightning-app#683]
### Description
Lightning Desktop tried to open channel, tx is confirmed (5af191782176922a1c7b6961cfe4e65241c0df217e6df15f2cc9f6848966ea7d) but channel is still status pending
### Steps to reproduce the behavior
don't know
### Expected behavior
Channel should be green aka usable after 6 confirmations
### Actual behavior
seems to wait forever even after 6 confirmations of funding tx

**Comment by erkarl** [comment]
Probably related to: https://github.com/lightninglabs/lightning-app/issues/657

**Comment by haukehess** [comment]
Yep, seems the same issue. Closing here
