### ISSUE TITLE
euro symbol '€' positioning in New Lightning App

### ISSUE THREAD

**Issue by mesqueeb** [lightninglabs/lightning-app#689]
Some feedback on the [New Lightning App blog post](https://blog.lightning.engineering/announcement/2018/09/10/lightning-app.html).
I wasn't sure where to put this feedback, so I openend an issue here.

Your screenshots show the euro symbol '€' **behind** the numbers:

![](https://blog.lightning.engineering/assets/images/new-app-fiat.png)

However, it's the convention to write either:
- € 10
- 10 EUR

Having the euro symbol '€' behind the numbers will be experienced as very strange or incorrect by most users I think.

**Comment by wallacewest** [comment]
Well, this depends on the default system language, as the app uses `Number.prototype.toLocaleString()` to format the amount and position the symbol.

Give the app a chance and try to play with your default system language settings to see how it impacts the formatting. ;)

![ln](https://user-images.githubusercontent.com/42651128/45928051-88924e00-bf3d-11e8-9799-9534ba056945.png)

[Number.prototype.toLocaleString() - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#Using_options)

**Comment by mesqueeb** [comment]
@wallacewest I'm not sure I would rely on that...
I just checked the returned values for Belgium vs the Netherlands
```js
var number = 123456.789;
number.toLocaleString('nl-NL', { style: 'currency', currency: 'EUR' })
number.toLocaleString('nl-BE', { style: 'currency', currency: 'EUR' })
```
And it returns `€10` for the Netherlands but `10€` for Belgium...
And I've lived in Belgium for whole my life and no one writes `10€`...

**Comment by tanx** [comment]
In Germany we write `10,00 €`. For US it's `$10.00` ... looks fine the me or am I missing something?

**Comment by mesqueeb** [comment]
@tanx just what I said: 
It returns 10€ for Belgium.
But no one writes 10€ In Belgium. We write €10

**Comment by tanx** [comment]
Closing this for now
