### ISSUE TITLE
Unable to query bootstrapper with: BOLT-0010 DNS Seed

### ISSUE THREAD

**Issue by OpenGrid** [lightninglabs/lightning-app#69]
Attempting to bootstrap with: Authenticated Channel Graph
[INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [nodes.lightning.directory]
[INF] RPCS: [listchannels] fetched 0 channels from DB
[ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [nodes.lightning.directory]: lookup _nodes._tcp.nodes.lightning.directory on 127.0.0.53:53: read udp 127.0.0.1:58051->127.0.0.53:53: i/o timeout 
[INF] DISC: Obtained 0 addrs to bootstrap network with

**Comment by toxonaut** [comment]
Same problem

**Comment by thejourneydude** [comment]
I've experienced this problem as well when I broke the codebase. Can you guys provide more information such as what commit you're codebase is at, what is happening to the application, anything else we should know, etc.?

**Comment by bryanvu** [comment]
Closing as duplicate of issue #26.
