### ISSUE TITLE
Amend "Developing Locally" portion of README with lnd build flag instructions

### ISSUE THREAD

**Issue by valentinewallace** [lightninglabs/lightning-app#694]
To be able to pass the integration tests, you'll need to build LND commit `51d43be1f369c7ec5ae8bc3bb282a45c6a0776ea` with experimental build flag as in [this line](https://github.com/lightninglabs/lightning-app/blob/master/assets/script/install_lnd.sh#L37). The README should be edited to reflect this.

**Comment by blockchainsolutionshi** [comment]
So I rebuilt LND with the experimental tag and it still throws the same error

**Comment by erkarl** [comment]
@blockchainsolutionshi did you also copy over the binary to `./assets/bin`?

For OSX:
`cp $GOPATH/bin/lnd ./assets/bin/darwin`

**Comment by blockchainsolutionshi** [comment]
That worked thank you
