### ISSUE TITLE
Issues do not always provide enough information

### ISSUE THREAD

**Issue by thejourneydude** [lightninglabs/lightning-app#71]
Since this is an open-source project, there will be people who create issues and may not provide enough information to debug the issue. Because of this, other contributors and the maintainers must ask follow-up questions to fully understand the bug. This is problematic as it becomes time-consuming for both parties.

One practical fix is to use [issue templates](https://help.github.com/articles/creating-an-issue-template-for-your-repository/). With an issue template, issue creators will be asked several questions regarding the issue. This provide enough information for others to understand and reproduce the issue. There are plenty of examples of issue templates online. One example can be found below.

---------

## Anything else we should know?

**Comment by bryanvu** [comment]
Done. Thanks @thejourneydude!

**Comment by thejourneydude** [comment]
Thanks @bryanvu!
