### ISSUE TITLE
Lack of continuous flow in app setup (v0.2.3-alpha - Windows)

### ISSUE THREAD

**Issue by molxyz** [lightninglabs/lightning-app#718]
Operating system:  Windows 10
App version:  0.2.3-alpha (fresh install, standalone, not run with local bitcoind)
The app initial setup went well with creating pass phrase and syncing. 
Coins were sent to the app in several transactions... 
At one point I clicked on the "copy" button next to the address to send more coin to the wallet, the app suddenly switched to this next screen:

![image](https://user-images.githubusercontent.com/21127776/46562580-af9c3880-c8ca-11e8-8e40-c32f1912a9a2.png)

And it stayed on this screen even after all transactions had more than 6 confirmations. 
Also notice there's not a button on this screen to go to the next screen.
So I rebooted the app. Then I was able to see my channels were being populated by autopilot.
Checking on the status of each tx I noticed the tx at the bottom (which seems to be the first tx created by autopilot) was not on any explorer while other txs showed up on explorers.
After a couple hours and 8 channels created, the screen showed  4 channels at the top as  `Open` while 4 channels at the bottom still on `Pending Open`.
I checked the bottom channels, they had more than 6 confirmations, except the middle one with the TXID starting with `be36ae75454... ` could not be found on any explorer. 

![image](https://user-images.githubusercontent.com/21127776/46562906-71077d80-c8cc-11e8-8ad1-93644e5b6245.png)

The app was restarted several times but it showed the same screen.  I closed the app after this but will test again.

**Comment by tanx** [comment]
This should be fixed in the current release `v0.2.4-alpha` as it upgrades to current lnd and also other dependencies. Closing this for now.
