### ISSUE TITLE
Wallet address is missing and QR code is incorrect

### ISSUE THREAD

**Issue by molxyz** [lightninglabs/lightning-app#727]
Description
v0.2.5 fresh install on Windows.
QR code and wallet address appear on screen "Your shiny new address" but after that the address screens shows no address and QR code is unreadable.

 Steps to reproduce the behavior
Click on button "WALLET Add coin" to get to the address screen.

Expected behavior
The app should show a normal QR code for a new address which should appears next to it.

 Actual behavior
There's not an address and the QR code looks broken.

Screenshot and/or logs if applicable
![image](https://user-images.githubusercontent.com/21127776/46714271-9677ec80-cc28-11e8-9fae-dfa8bfc4b290.png)

EDIT:  Strange that the address shows up in the log: 
2018-10-10 01:01:26.708 [INF] RPCS: [newaddress] addr=2MwYufcuYy9mcuMqwgLWksfHbD65X7BCRs4

[01:08:03.397] [info] Saved state

**Comment by tanx** [comment]
Ok strange. I couldn't reproduce this in v0.2.6. Have you tried with that one?

**Comment by molxyz** [comment]
@tanx 
Haven't seen this in later versions anymore so i'm closing this issue.

**Comment by tanx** [comment]
Ok cool thanks
