### ISSUE TITLE
We don't have tests

### ISSUE THREAD

**Issue by thejourneydude** [lightninglabs/lightning-app#73]
### Description
We currently don't have tests for this application. Tests provide numerous advantages such as ensuring our code doesn't break and gives developers confidence that our code works. If we all agree that this application needs tests, there are a couple of questions to ask.

1) What libraries/tools do we use for testing? There is [Jasmine](https://jasmine.github.io/), [Mocha](https://mochajs.org/), [Jest](https://facebook.github.io/jest/), etc.

2) If we adopt testing, what is the policy for testing new code going forward? 

3) How do we handle old code that has yet been tested? 

I'm sure there are other questions that need to be answered but that's all I have for now.

As a side note, I would love to start writing tests for every lightning package in this application. This way, I can familiarize myself with the codebase. If we can agree that we need tests and state which libraries/tools we should use, and if I have the maintainer's blessing, I'll get to work on writing these tests.  

### Steps to reproduce the behavior
None.

### Expected behavior
We have a full-suite of tests that ensures our code works as intended and provides full code-coverage.

### Actual behavior
We have no tests. :(

### Screenshot and/or logs if applicable
None.

**Comment by casesandberg** [comment]
I suggest using [jest](https://facebook.github.io/jest/) as the test runner and [enzyme](https://github.com/airbnb/enzyme) for any component-specific assertions. I can take a stab at getting a few in there this week.

**Comment by thejourneydude** [comment]
@casesandberg Sweet. We may need to coordinate who's doing what so we don't both write duplicate tests for the same code. 

I _think_ I'm going to tackle the `lightning-currency`, `lightning-popup`, and `lightning-forms` packages this upcoming week. If anyone thinks I should test something else, let me know. I don't want to step on anyones shoes 😉.

**Comment by bryanvu** [comment]
Huge thanks @casesandberg and @thejourneydude. This is definitely something we've been needing, but haven't figured out how to do.

**Comment by casesandberg** [comment]
That sounds good to me! I'm happy to take `lightning-core` and `redux-grpc-middleware`. I'll throw up a branch tomorrow with the testing structure that we can then branch off of to do the individual packages. Does that sound good to you @thejourneydude?

**Comment by thejourneydude** [comment]
Sounds good!

**Comment by thejourneydude** [comment]
@casesandberg After some investigation I discovered that the `lightning-currency` package is not being used anywhere. I'm inclined to remove the package altogether instead of testing it since when/if we need the package we can go back to our git history and get the code that way.
