### ISSUE TITLE
Integrate secure PRNG native module for source of entropy for wallet password

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#777]
A crypto api for expo is in the works: https://expo.canny.io/feature-requests/p/crypto-api

In the meantime, this seems to be a popular choice: https://github.com/mvayngrib/react-native-randombytes

**Comment by Overtorment** [comment]
Crypto API for Expo is no longer in the works.
We had same strugle with https://github.com/BlueWallet/BlueWallet and finally ditched Expo in favor of pure RN.

**Comment by tanx** [comment]
Depends on #1054
