### ISSUE TITLE
Deauthorize spend functionality during an active App session 

### ISSUE THREAD

**Issue by rstmsn** [lightninglabs/lightning-app#779]
This issue suggests the addition of a feature that would allow the user to deauthorize or lock the ability to spend funds from an authenticated instance of the desktop app. 
Once activated, the user would be required to reauthenticate with the app by providing their password, before the ability to make payments is restored. 

This feature would improve overall wallet security and would suit use cases where third [potentially untrusted] parties have been granted temporary access to the users terminal, (e.g. screensharing/remote desktop assistance), and where sleep/locking the users terminal is inappropriate. 

In such circumstances, the authenticated Lightning-app user may wish to both obfuscate their wallet balance, and lock the ability for outgoing payments to be made. 

With both of these objectives in mind, it would seem more appropriate that the proposed functionality return the user to an initial authentication like screen, rather than simply disabling the in app 'pay' button. 

Ideally, the background instance of Lnd should remain alive & functional, so as to maintain the 'active' status of all open channels, and to continue to contribute to the overall health of the network as a whole.

![screen shot 2018-11-06 at 23 50 41](https://user-images.githubusercontent.com/1072503/48101408-ceba1d00-e21e-11e8-9436-4ca644fb3ef1.png)

**Comment by tanx** [comment]
The current `Lock` feature is to close the app 🙃

> Ideally, the background instance of Lnd should remain alive & functional, so as to maintain the 'active' status of all open channels, and to continue to contribute to the overall health of the network as a whole.

Channels opened by user agents are private anyway and not advertised for routing payments. See: https://blog.lightning.engineering/posts/2018/05/30/routing.html
