### ISSUE TITLE
Remove sleep from start-electron script

### ISSUE THREAD

**Issue by bryanvu** [lightninglabs/lightning-app#78]
### Description

Currently, there's a sleep added here: https://github.com/lightninglabs/lightning-app/blob/ac5d5ace932f3e9b9204472f4e530a9cee1bbf77/apps/desktop/package.json#L14.

This solves a race condition as described in PR #77 and Issue #68. This sleep should be removed and a better solution found to removing this race condition.

**Comment by thejourneydude** [comment]
This issue should be removed considering PR #80 removes the sleep command.
