### ISSUE TITLE
Question: Is it possible to open a channel between an Eclair wallet and this lightning app?

### ISSUE THREAD

**Issue by fresheneesz** [lightninglabs/lightning-app#79]
I haven't been able to get a friend to run this lightning app, so I'm trying out Eclair. It looks pretty simple to set up, so I was wondering if I could create a channel between my Eclair wallet and this one. Is that possible? This lightning app doesn't seem to have a pubkey@hostIp formatted node URI I can connect to in Eclair, and neither does Eclair. Is there any way for me to connect these two lightning wallets?

**Comment by DaReaper** [comment]
Yep it's possible

Here's the Node URL format that you need to Paste in Eclair wallet: pubkey@yourip:theport

Pubkey you can get from the Lightning app wallet, your IP (external or internal) and the port (usually defaults to 9735). I was able to add this lightning channel on my eclair wallet by clicking the '+' button and selecting 'Paste A Node URI' option (once I've copied the Node URI in the above mentioned format). Eclair wallet currently only supports outbound transactions (as such you can only make Lightning payments but not receive lightning requests).

**Comment by fresheneesz** [comment]
Cool! Looks like its working. I see that the app recognized the connection request in the logs in the settings view. I don't see any new pending channel in the Channels view tho. I'll report back after trying to make a transaction.

**Comment by Roasbeef** [comment]
Note that there have been some breaking spec changes lately. `lnd` has these implemented, but I haven't yet resumed cross-implementation testing and I'm not sure the latest in-app-store version of eclair has been shipped with these new changes.

**Comment by fresheneesz** [comment]
Yup, I found that out: https://github.com/ACINQ/eclair/issues/197 . Sounds like they'll update soon.
