### ISSUE TITLE
LoadNetworkSpinner not displaying progress anymore 

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#801]
Looks like a regression from fixing #786

![image](https://user-images.githubusercontent.com/1374174/48778514-4b440580-eccd-11e8-823c-0c30a5136576.png)

**Comment by valentinewallace** [comment]
Closed by https://github.com/lightningnetwork/lnd/pull/2205.

**Comment by tanx** [comment]
@valentinewallace I don't understand. This regression was caused by #800 ?

**Comment by tanx** [comment]
@valentinewallace ah no sorry. You're right. I just tested with lnd@`721e9a2a90eb6a3eb985b02af6c56762026aa16f` and this bug doesn't happen. Where as with `d6d833c2421f4a65c6db5190d1dcd73f549fbf70` there is no progress. 

/cc @Roasbeef

**Comment by tanx** [comment]
Lovely!
