### ISSUE TITLE
Dynamically retrieve BTC conversation rates

### ISSUE THREAD

**Issue by thejourneydude** [lightninglabs/lightning-app#81]
### Description
When we use the lightning-currency package, our conversion rates for BTC to USD and BTC to EUR are out-of-date. 

### Steps to reproduce the behavior
Call `getCurrency('usd')` or `getCurrency('eur')` and you'll see that the `format` functions returned don't match the current conversion rate.

### Expected behavior
When we call the `format()` function, we should expect an accurate conversation rate. 

### Actual behavior
The rates are stuck at 1 BTC = 1194.99 USD and 1 BTC = 1131.87 EUR.

### Screenshot and/or logs if applicable
Please visit [here](https://github.com/lightninglabs/lightning-app/blob/master/packages/lightning-currency/currencies.js#L30) and [here](https://github.com/lightninglabs/lightning-app/blob/master/packages/lightning-currency/currencies.js#L37) to see where these conversion rates are set.

**Comment by nalinbhardwaj** [comment]
I would like to try fixing this.

**Comment by thejourneydude** [comment]
Thanks @nalinbhardwaj! First off, I'm not a maintainer of this repo so don't take what I say as an authoritative answer. 

Right now this bug exists inside the lightning-currency package. A couple of days ago I determined (see #76) that this package is dead-code and should be removed from the codebase. I've been meaning to [submit a PR that removes this package](https://github.com/thejourneydude/lightning-app/tree/remove-lightning-currency-package) but have been busy. There can be a couple of ways to approach this:

1) If the maintainers want to keep package in the codebase, go right ahead and fix the bug. :)

2) If the maintainers want the package removed, you can write a PR for the fix followed up with a PR to remove the package. If/when we need this package again we will likely pull the code from the git history with your fix.

3) If the maintainers want the package removed, you can write a simple git gist for the bug fix and append it to a new PR inside it's description. The PR itself would remove the lightning-currency package from the codebase.

**Comment by nalinbhardwaj** [comment]
@thejourneydude I had been confused about where it was actually used, I think the package is present for potential future use since it never was used in the first place(as far as I understand)?

I'll hold off any changes until the maintainers make a decision I think.

**Comment by bryanvu** [comment]
Thanks @thejourneydude and @nalinbhardwaj. @casesandberg or @Roasbeef, any comments on the intended use for this package?

**Comment by casesandberg** [comment]
`lightning-currency` was intended to be the single source of truth for handling different currencies, and their conversions and formatting. The code ended up being copied over and used in other packages while prototyping (see [lightning-core/helpers/currencies.js](https://github.com/lightninglabs/lightning-app/blob/master/packages/lightning-core/helpers/currencies.js) and [lightning-core/common/Money.js](https://github.com/lightninglabs/lightning-app/blob/master/packages/lightning-core/common/Money.js)).

My vote would be to remove the logic that leaked into `lightning-core` to prevent more coupling and move the Money and currency helpers to the `lightning-currency` package. The currencies should definitely be dynamic (pulling from an API?)
