### ISSUE TITLE
Wallet balance went to 0 after paying

### ISSUE THREAD

**Issue by cheeseSnake** [lightninglabs/lightning-app#82]
Running Fedora release 25
Sent 100000 SAT 2daa4dcd5d56329a10d7a31304eed6b07c101c6091882d235da87c077ebde5d6 
![1](https://user-images.githubusercontent.com/33094536/32006742-309ff48a-b96d-11e7-9322-8d42c6645c93.png)

After I hit send Send Payment in the $Pay tab, my balance was 0
![2](https://user-images.githubusercontent.com/33094536/32006750-3464ffc0-b96d-11e7-81dc-7bc9ac275c75.png)

~40 minutes later it correctly stated my balance. 
![3](https://user-images.githubusercontent.com/33094536/32006755-37261a3c-b96d-11e7-83bd-fd2a8a4346cf.png)

**Comment by Roasbeef** [comment]
If you only had a single output in the wallet, then that send would _consume_ that output and create unconfirmed change. The wallet doesn't currently display any balance information for unconfirmed change.

**Comment by scaleToTheFuture** [comment]
can confirm the issue. Same behaviour when opening lightning channels. Balance goes to 0 until channel is open. Very confusing... 
Unconfirmed sats should be displayed (either separately or in total balance)

**Comment by Roasbeef** [comment]
The next version of the application will include unconfirmed+confirmed in the balance display 👍

**Comment by zechendorf** [comment]
@Roasbeef - how are you guys working - is there a ticket for this feature so I can give input there?

Based on my understanding we have multiple types of balances that should be added and displayed in the below left corner:

![screenshot from 2017-12-29 06-54-43](https://user-images.githubusercontent.com/11517177/34430414-2daeac6e-ec65-11e7-8bb9-f21060ef432d.png)

1. Unconfirmed on chain transactions
2. Confirmed on chain transactions
3. Channel balances

For a more "instant" look and feel it would be great if unconfirmed transactions would instantly be added to the balance also. I find the way copay handles this quite intuitive

![screenshot from 2017-12-29 07-06-34](https://user-images.githubusercontent.com/11517177/34430597-f032b11c-ec66-11e7-900b-af833bfdb1c6.png)

It shows the total amount and below this it shows the confirmed amount. Additionally we cold show the amount in channels so the user would see:

* total amount (including channels and unconfirmed transactions)
* confirmed amount (wallet)
* channel amount (lightning)

**Comment by copumpkin** [comment]
I noticed this too, then found this issue.

**Comment by copumpkin** [comment]
It also seems safe to indicate that change I generated is 100% my own, regardless of confirmations. If the transaction confirms, the change is mine, and if it doesn't confirm, the full amount is still mine. So unconfirmed change is still in a sense different from random person on the internet sending me money in an unconfirmed transaction.
