### ISSUE TITLE
Auto open channels?

### ISSUE THREAD

**Issue by fubuloubu** [lightninglabs/lightning-app#853]
### Description
Does the app auto open channels? I don't think I asked it to open a channel for me, but it opened 3 channels using all my (testnet) Bitcoin. Seems like unintuitive behavior that should at least be announced/confirmed if that is the intent.

![screenshot from 2019-01-06 23-14-30](https://user-images.githubusercontent.com/3859395/50748749-e2770500-1208-11e9-9243-18b1a9ae3f50.png)

**Comment by tanx** [comment]
> Does the app auto open channels?

yep :) The intention behind our current is layed out here: https://blog.lightning.engineering/announcement/2018/09/10/lightning-app.html

Obviously it's early days and we're still learning how users use Lighting. The goal of our app is to have channel management fade into the background as the tech matures.
