### ISSUE TITLE
Windows app cannot find peers

### ISSUE THREAD

**Issue by MidnightLightning** [lightninglabs/lightning-app#86]
### Description
Upon installing the Windows application for the first time, it seems to be stuck trying to find peers; is this due to limited use on the network, or an issue on my end? I see this series of lines repeated in the "Settings" log:

```
lnd: 2017-11-05 15:09:50.514 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-11-05 15:09:55.325 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters
lnd: 2017-11-05 15:09:55.326 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-11-05 15:10:00.442 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters
lnd: 2017-11-05 15:10:00.442 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-11-05 15:10:05.555 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters
lnd: 2017-11-05 15:10:05.555 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-11-05 15:10:10.533 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-11-05 15:10:10.670 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters
lnd: 2017-11-05 15:10:10.670 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-11-05 15:10:15.855 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters
lnd: 2017-11-05 15:10:15.855 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-11-05 15:10:20.982 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters
lnd: 2017-11-05 15:10:20.982 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-11-05 15:10:26.095 [INF] BTCN: Disconnecting peer 165.227.7.29:18333 (outbound), cannot serve compact filters
lnd: 2017-11-05 15:10:26.095 [INF] BTCN: Lost peer 165.227.7.29:18333 (outbound)
lnd: 2017-11-05 15:10:30.512 [INF] RPCS: [listchannels] fetched 0 channels from DB
```

### Steps to reproduce the behavior
Open application on Windows 10 workstation

### Expected behavior
Blue "Syncing to chain" icon disappears after establishing a link to the chain state.

### Actual behavior
Log indicates a repeating cycle of failure to make connection to peer.

### Screenshot and/or logs if applicable
See description

**Comment by Roasbeef** [comment]
Looks like you're running a dated version of the application. [`v0.1.2`](https://github.com/lightninglabs/lightning-app/releases/tag/v0.1.2-alpha) was recently released.

**Comment by Roasbeef** [comment]
It looks like you're running an outdated version of the application. We recently updated `neutrino` to match the latest version of our draft BIP. If you download the recent [0.1.2 release](https://github.com/lightninglabs/lightning-app/releases/tag/v0.1.2-alpha), this issue _should_ be resolved.

**Comment by ghanavati27** [comment]
Here is same problem. i downloaded latest 0.1.2 , Fixed! thanks for your great project

**Comment by MidnightLightning** [comment]
Yes, that works for me now!
