### ISSUE TITLE
Nav transitions are sometimes buggy i.e. go in the wrong direction

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#860]
This might be a bug in react navigation. Gonna try to upgrade to the most recent 2.x.x release to fix this one.

**Comment by valentinewallace** [comment]
would this be an example of that?

![lightningapp](https://user-images.githubusercontent.com/10647624/51150563-b288bc80-181b-11e9-9b52-98624289f2a7.gif)

**Comment by tanx** [comment]
This was another issue. Sometimes the swipe went left instead of right. Let's if the current refactoring fixed it.

It's true that the some navigations are now modal instead of swipes. The problem is with ListViews is that they didn't get re-rendered with swipe navigation. Let's keep this issue open as a reminder to fix that. At least lists render now which is more important.
