### ISSUE TITLE
integrate new autopilot sub-server within lnd

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/lightning-app#863]
Similar to the `WalletUnlocker` gRPC service, `lnd` now has a special `Autopilot` server gRPC service. This new services needs to be compiled in with a special build tag for now (`autopilotrpc`) and will be created after the primary RPC server for lnd starts up (after unlock/create). 

The [proto file for the new service can be found here](https://github.com/lightningnetwork/lnd/blob/master/lnrpc/autopilotrpc/autopilot.proto). Atm, we only two calls: `Status` and `ModifyStatus`. These let the caller obtain the current state of autopilot (atm active or not) and also turn off/on the system all together. This is useful as atm, there isn't anyway of turning of `ATPL` if the users wishes to sweep all their coins from the wallet. 

With this new service, we can expose an option in the settings to turn autopilot on/off. We may also not even need to set the main flag anymore as we can save the state in local storage (or w/e) and make the call each time `lnd` comes up. 

In the future, this will also be expanded to pull in supplementary scoring information for the autopilot agent. This isn't merged into lnd yet though, so I'll hold off describing that new system until then.

**Comment by tanx** [comment]
Require for #656

**Comment by tanx** [comment]
Already integrated in `v0.4.5-alpha`
