### ISSUE TITLE
Listing invoice fails on iOS

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#873]
The grpc request for listing invoices fails on iOS.

**Comment by halseth** [comment]
Looks like it is not the grpc request that fails, but the following parsing of the response:
```js
     this._store.invoices = invoices.map(invoice => ({
        id: toHex(invoice.rHash),
        type: 'lightning',
        amount: invoice.value,
        status: invoice.settled ? 'complete' : 'in-progress',
        date: parseDate(invoice.creationDate),
        memo: invoice.memo,
      }));
```

Looks like it is the call to `toHex` that fails: https://github.com/lightninglabs/lightning-app/blob/9d5071608ec0c48bc8aa2564635d7345fa84f3a1/src/helper.js#L172

Possibly decoding of response is different on mobile?
