### ISSUE TITLE
Track user behavior

### ISSUE THREAD

**Issue by thejourneydude** [lightninglabs/lightning-app#88]
### Description
We lack the ability to track user's behavior. 

With analytical data, we will be able to make more informed decision's about UI, future features, and potentially help with debugging issues. There are a variety of libraries we can use to track analytical data.

- [Electron Google Analytics](https://github.com/vacu/electron-google-analytics) using [Google Analytics](https://analytics.google.com/analytics/web/).
- [Deskmetrics](https://deskmetrics.com/)
- [Neutrino Metrics](https://neutrinometrics.net/) (looks defunct but may be wrong)
- Create our own custom solution

I think the first behavior to track is user clicks. That way, we learn what pages users are visiting the most. From there we can consider other behaviors like "time on a page" and "current version running".

One downside to tracking analytics is that we are invading user's privacy. This issue is especially important since we are involved in the cryptocurrency field. I could be overthinking the privacy issue, but I welcome input on the matter nevertheless.

### Steps to reproduce the behavior
None.

### Expected behavior
Collect and view analytics data on user's behavior.

### Actual behavior
We have no analytics data on user's behavior.

### Screenshot and/or logs if applicable
None.

**Comment by bryanvu** [comment]
@thejourneydude, I agree that we definitely need to do some thinking about how to understand user behavior so that we can build a much more usable and streamlined UI. However, my thinking is that we'll have to do it without relying on traditional click-tracking and other kinds of normal analytics solutions that would be used with React/Electron apps. Privacy is a concern as you mention, but for me, security and attack surface size are even bigger concerns. IMO, the app should be sandboxed as per issue #75, all network traffic should go through the lnd back-end, and lnd network calls will be limited to the Bitcoin and Lightning wire protocols. Thoughts?

**Comment by thejourneydude** [comment]
After researching #75, this makes sense to me. I'm going to close this issue.

-----

If we can't use traditional analytics, we will have to find alternative means to ensure we are building a great UI experience. A couple of ways we can do this:

1) [Usability testing](https://uxmastery.com/beginners-guide-to-usability-testing/): Have users test our app and receive live feedback. One upside to having an active Slack community is that we have a plethora of users we can talk to immediately.

2) Mockup requirements: Whenever we plan to make changes to the UI, we need to first come up with an agreed UI mockup. This helps save the developer time and ensures our UI is uniform across the board. I think #94 can help with this. 

3) Creating User Stories: Related to point 1, but we need to know what users are doing when they use our app. Talking to users and getting feedback on how they use our app will help guide us on what are our most important features and thus most used UI. Some of this data can come from general feedback in the Slack community. Other info can come from personal conversations with users. 

These are my general thoughts and I'm sure they will change over time.
