### ISSUE TITLE
Fix header regression for iOS tx detail view

### ISSUE THREAD

**Issue by valentinewallace** [lightninglabs/lightning-app#883]
Starting at commit 1a7ec72077186476738c8c9fcaf2cdfce574b416, the transaction detail pages look like this: https://i.imgur.com/VqX7RT3.png

when they should look like this: https://i.imgur.com/6QVk9EE.png

**Comment by tanx** [comment]
Yeah I saw that yesterday too. Fixed in https://github.com/lightninglabs/lightning-app/commit/83a9c7a7d03a1c02dfc6fe6d0f3f12f7318b2647
