### ISSUE TITLE
Mobile app crashes sometimes when opening QR code scanner

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#892]

**Comment by tanx** [comment]
This seems to be resolved in build v0.0.7

**Comment by molxyz** [comment]
@tanx  QR code scanner does not work for the latest iOS app v0.0.18
Click on `PAY` then click on `SCAN`. Result: the app logs out.  When you log back in after entering the pin code, the app opens the next blank dark screen with `Loading network...` spinning and it won't stop until you just have to restart the phone. The spinner also creates overheating.

**Comment by tanx** [comment]
@molxyz mmmh yeah. Still lots of quality issues on mobile in general. We're planning to revisit focus on mobile until after the desktop mainnet release.

**Comment by tanx** [comment]
Depends on #1054

**Comment by tanx** [comment]
Resolved by using `react-native-camera` in `0.2.0`
