### ISSUE TITLE
Initial sync hangs on iOS

### ISSUE THREAD

**Issue by champo** [lightninglabs/lightning-app#904]
### Description
The initial sync hanged at height 137000.

### Steps to reproduce the behavior
 - Create a new wallet
 - Send funds to the address using faucet
 - Wait at "Almost there screen"

**Comment by tanx** [comment]
Yeah, sync stability is still pretty much hit and miss on iOS right now. I usually need to restart the app several times to get to a fully synced home screen.

**Comment by tanx** [comment]
Mmmh. I tried to reproduce several times. Wasn't able to trigger the bug. Perhaps try again with the current build v0.0.7. Closing this for now.
