### ISSUE TITLE
Error on launch on iPad - Unhandled JS Exception: Application main has not been registered

### ISSUE THREAD

**Issue by bretton** [lightninglabs/lightning-app#905]
### Description

I installed testflight, and entered my code to install Lightning.app

When launching Lightning.app the application fails to launch.

### Steps to reproduce the behavior

Install testflight on ipad 3 (3G model) running iOS 9.3.5 and install Lightning.app

### Expected behavior

Application should launch and sync and allow me to fund the wallet

### Actual behavior

Error notice as per screenshot below, no ability to change or edit anything.

### Screenshot and/or logs if applicable

https://i.imgur.com/YJXtAW2.jpg

**Comment by tanx** [comment]
Good catch. I'm surprised the binary even installed on the iPad. Closing in favor of #906
