### ISSUE TITLE
Closed channels still have "CLOSE CHANNEL" button 

### ISSUE THREAD

**Issue by molxyz** [lightninglabs/lightning-app#912]
### Description
On the "CHANNELS" screen if you click on `Pending Force Closing` and `Closed` txs a small popup screen shows up and on that screen there's this button `CLOSE CHANNEL` that if you click on it, it takes you to another screen saying you can close those channels again, but those channels are already closed! 

### Screenshot and/or logs if applicable
![image](https://user-images.githubusercontent.com/21127776/51925788-d3c1df00-23bd-11e9-96ca-b99cf1103ece.png)

![image](https://user-images.githubusercontent.com/21127776/51925831-e4725500-23bd-11e9-83a6-4d7faf1adfc8.png)

**Comment by tanx** [comment]
Nice catch!
