### ISSUE TITLE
UI fix for sending funds

### ISSUE THREAD

**Issue by scaleToTheFuture** [lightninglabs/lightning-app#92]
### Description
While sending coins (classic on-chain sending), the "Send payment" button stays active while the command is being processed. I didn't know that my click was accepted by the program. So is was clicking it again. Resulted in sending amount twice. 

### Proposal
"Send payment" button should be deactivated while sending is in progress, so double sending isn't possible anymore, and it is clear, that the app has received the command.

**Comment by thejourneydude** [comment]
Confirmed on my end as well.

---------

After some initial investigation it doesn't look like this is a quick fix. The Form component is designed in such a way that we can't simply disable the button* during the submit, at least through the `disabled` attribute. I'll have to ponder this some more and figure out the best way to approach this. 

* The button you see on the page is actually not a button, but a div. This is problematic as we are unable to use the `disabled` attribute.

**Comment by copumpkin** [comment]
This seems to happen (although I didn't get a double channel) with the channel creation form too. I click on it, and it stays active with no indication of something happening for a bit, allowing me to click on it while I wait.
