### ISSUE TITLE
iOS app slides back to "Confirm" screen after sending payment successfully

### ISSUE THREAD

**Issue by molxyz** [lightninglabs/lightning-app#921]
### Description
This doesn't happen every time but so often that the app quickly slides back to the `Confirm` screen after making a successful payment.  If you miss catching the payment screen, it makes you think the invoice hasn't been paid and if you try to press on `Confirm` again, you get the error message that the payment has failed. 
### Steps to reproduce the behavior
Create an invoice QR code, click on `Pay`, click on `Scan`, click on `Confirm`.  Try this several times. 
### Expected behavior
When a payment is sent successfully, only the screen for `Payment sent! Done` should appear.

**Comment by tanx** [comment]
@molxyz thanks!

Someone also captured this bug in a video on twitter https://twitter.com/dopetard/status/1090761513806094336

**Comment by molxyz** [comment]
@tanx  Haha.. I'm glad he got it on a video! Read your comment on that twitter thread, my phone is not on a VPN though. Ankur said he could get it synced in 11 minutes, so did I. So I'm wondering maybe it's not because of the latency but because of something else? 

Thanks, tanx, for sharing this.
