### ISSUE TITLE
No currency symbol

### ISSUE THREAD

**Issue by halseth** [lightninglabs/lightning-app#932]
### Description
On Moto X 2014, no currency symbol is shown. Clicking the balance changes the currency to BTC, which is shown correctly. Also tried changing to EUR and GBP, still no symbol.

### Steps to reproduce the behavior
Running the app, deposit funds.  Wait for sync to finish.

### Expected behavior
USD or EUR is shown by the balance.

### Actual behavior
No currency symbol is shown.

### Screenshot and/or logs if applicable
![screenshot_20190205-154444](https://user-images.githubusercontent.com/3765732/52281024-7699d080-295d-11e9-807e-b79da326f3af.png)

**Comment by tanx** [comment]
@halseth which Android version is on Moto X 2014?

**Comment by halseth** [comment]
6.0

**Comment by halseth** [comment]
After opening channels
![screenshot_20190206-094217](https://user-images.githubusercontent.com/3765732/52331528-b2ce3f00-29f8-11e9-8db5-a29bd86ee553.png)
![screenshot_20190206-094224](https://user-images.githubusercontent.com/3765732/52331530-b366d580-29f8-11e9-8965-581b8dec614a.png)

**Comment by tanx** [comment]
We should try this https://www.npmjs.com/package/number-to-locale-string-polyfill

**Comment by tanx** [comment]
I got this working https://github.com/facebook/react-native/issues/19410#issuecomment-434232762
