### ISSUE TITLE
Create style guide page

### ISSUE THREAD

**Issue by thejourneydude** [lightninglabs/lightning-app#94]
### Description
We currently don't have a style guide page.

This style guide page would act as a palette. We can use this palette to make informed UI decisions on new UI features and enforce consistency across the entire app. No more guessing how the UI will look with elements that never have been paired together. A style guide page will give us a de-facto UI vision.
 
I'm thinking that we create a HTML page that can be visited within a browser, say `localhost:1234/style_guide`. This HTML page contains every known element in our app. The exact implementation can change accordingly to needs. What is important is that there is a page that contains every known HTML element and it's potential CSS styles.

### Steps to reproduce the behavior
None.

### Expected behavior
None.

### Actual behavior
None.

### Screenshot and/or logs if applicable
None.

**Comment by tanx** [comment]
Resolved in https://github.com/lightninglabs/lightning-app/pull/287
