### ISSUE TITLE
Display a testnet indicator on the home screen

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#940]
![fJMspBG](https://user-images.githubusercontent.com/1374174/54725088-c5679680-4ba8-11e9-87d3-bce2d45fbcc8.jpg)

**Comment by joachimneumann** [comment]
You could add an indicator to every screen when the app uses testnet:
<img width="514" alt="screenshot 2019-02-13 at 04 36 24" src="https://user-images.githubusercontent.com/5642225/52685145-fd940d80-2f48-11e9-9b06-740a42272f6c.png">

**Comment by joachimneumann** [comment]
@tanx, you might want to add the iOS tag to this issue and insert "iOS" at the beginning of the title

**Comment by cilphex** [comment]
Does this replace https://github.com/lightninglabs/lightning-app/issues/726?

**Comment by tanx** [comment]
@valentinewallace I added Lee's design to the ticket here.
