### ISSUE TITLE
Long seed words partly hidden

### ISSUE THREAD

**Issue by bit-the-dust** [lightninglabs/lightning-app#941]
### Description
Long seed words are partly hidden by the fields in which they are displayed.

### Steps to reproduce the behavior
Create a new account, view the seed words. 

### Expected behavior
The full length of the longest seed words should be displayed.

### Actual behavior
If the seed words happen to be long ones, the end of the words are hidden by the field in which they are displayed, e.g.

- mountain
- economy
- cinnamon

**Comment by bit-the-dust** [comment]
The fields in which the seed words are displayed are too narrow for longer seed words, e.g.

- mountain
- economy
- cinnamon

The end of the words are hidden. You can see enough to tell what the words are, so not critical, but given the importance of backup, this may cause anxieties for newbies.

Version 0.0.13 (13) on iOS

**Comment by valentinewallace** [comment]
@bit-the-dust Can't repro:

![52051108_403949527019512_8149707840093683712_n](https://user-images.githubusercontent.com/10647624/52673286-1d89e980-2ed5-11e9-8d2d-dc23426a2d6a.jpg)

Do you have a screenshot?

**Comment by bit-the-dust** [comment]
@valentinewallace I don't know how to take a screenshot, but yours helped me realise what the problem is. My text size setting is large, one stop before the largest on the iPhone text size setting.

Perhaps the scale of the seed word text needs to be restricted to ensure it is visible. 

Hope this helps.

**Comment by tanx** [comment]
> My text size setting is large, one stop before the largest on the iPhone text size setting.

Ok thanks. Closing this for now then.
