### ISSUE TITLE
Payment screen shows zero fee and zero total for Y'alls test net articles

### ISSUE THREAD

**Issue by bit-the-dust** [lightninglabs/lightning-app#943]
### Description
Open a Y'alls test net invoice. Lightning shows £0.00 fee and £0.00 total on payment screen with the payment note. 

iOS 0.0.13

### Steps to reproduce the behavior
Set Fiat currency, e.g. £. Sync app, fund the wallet and open channels. Go to testnet.yalls.org in Safari, click on an article. Copy the invoice using the on screen button. Switch to the app, click Pay. Paste the invoice. (Or scan QR.) Attempt to pay the invoice.

### Expected behavior
Show the payment screen with requested fee and total with enough decimal places to see the amounts, and an invoice note.

### Actual behavior
Shows £0.00 fee, £0.00 total and only the invoice note. The fiat amount is too small to display at two decimal places, which is confusing. 

On my original test, the payment failed because I didn't have a channel balance or a route. However, the zero display made it confusing because I could not see the amounts and I thought the app had not set the amounts correctly.

Later payment tests with open channels were more reliable. The amounts are present, but not visible at two decimal places.

**Comment by bit-the-dust** [comment]
The equivalent steps with starblocks.acinq.co displays a zero fee, the correct total and invoice note. (Payment fails with message "Lightning payment error: unable to find a path to destination.")

**Comment by bit-the-dust** [comment]
There is a similar display problem on the transactions listing screen and detail view, though its less confusing after a payment has actually completed.

**Comment by tanx** [comment]
Looks like this is just due to the current exchange rate of btc being lower than 1 cent. Would you expect the fiat displayed precision to be higher than two decimal values?

**Comment by Roasbeef** [comment]
Yeah tanx is right, when you try to send 1 satoshi, the amount is well below 1 cent. We can possibly just add some like "infinitesimal" (lol not actually the suggested language) indicator to convey that you're about to send a suuuuper small amount in fiat.

**Comment by bit-the-dust** [comment]
Thanks @tanx and @Roasbeef.

It would be unusual to show fiat with so many decimal places, so maybe "Less than £0.01" or something similar would work. Or show payment amounts in Satoshis if they are below this threshold.

Showing that the app has registered some non-zero amount is the key.

**Comment by tanx** [comment]
Or we could just wait for BTCUSD to moon so that 1 SAT is ~0.01 USD :)

**Comment by tanx** [comment]
We now display `< $0.01` for small SAT amounts.
