### ISSUE TITLE
Failed to launch on iPhone: Unhandled JS Exception

### ISSUE THREAD

**Issue by rstmsn** [lightninglabs/lightning-app#944]
### Description

'Unhandled JS Exception: Application main has not been registered' when launching 'Lightning App' through Testflight. 
The purple 'Lightning' splash screen is displayed successfully, then fails with the error shown below.

Launched on an iPhone 4S running iOS 9.3.5

### Screenshot and/or logs if applicable

![img_2860](https://user-images.githubusercontent.com/1072503/52480315-3c217500-2ba3-11e9-9088-638a6a0f5560.PNG)

**Comment by rstmsn** [comment]
**Update:** 
It appears TestFlight is forcing my device to run Lightning version 0.0.7. 
Two builds are listed within TestFlight: 0.0.7 and 0.0.13. 
0.0.7 is available to Open, however 0.0.13 shows as 'Requires Latest OS'.

**Screenshots:**

![img_2862](https://user-images.githubusercontent.com/1072503/52486649-9aeeea80-2bb3-11e9-9889-e35499ed9d07.PNG)
![img_2863](https://user-images.githubusercontent.com/1072503/52486650-9b878100-2bb3-11e9-904f-f82a000da36e.PNG)
![img_2864](https://user-images.githubusercontent.com/1072503/52486651-9b878100-2bb3-11e9-88ba-875787b2afda.PNG)

**Comment by tanx** [comment]
As of expo 31 support for iOS 9 was dropped. See: https://blog.expo.io/expo-sdk-v32-0-0-is-now-available-6b78f92a6c52

v0.0.13 is based on expo 32 and requires at least iOS 10
