### ISSUE TITLE
Feature request - to auto paste payment request / address / Lightning Addr  - ios

### ISSUE THREAD

**Issue by weaklysubjective** [lightninglabs/lightning-app#947]
### Description
Tedious to type string , error prone. Some assistance is available (ability to paste payment request) but Connection ID (pubkey@hostIP) when creating channels has to be typed

### Steps to reproduce the behavior
create a channel
### Expected behavior
paste option ?

**Comment by tanx** [comment]
Duplicate of https://github.com/lightninglabs/lightning-app/issues/911
