### ISSUE TITLE
When App starts in dev mode, pass command-line parameters to lnd

### ISSUE THREAD

**Issue by bryanvu** [lightninglabs/lightning-app#95]
### Description

Currently, when the App starts up in dev mode, the configuration is read from lnd.conf. This makes it difficult to run two instances of the app on the same machine, which would be useful for testing and such. the `npm run start` command should take command-line arguments for port numbers (and other configuration options) and use those when starting lnd.

### Expected behavior

`npm run setup --peerport=10019 --rpcport=10017 --datadir=test_lnd --logdir=test_lnd` should start up the App with a second instance of lnd using a different set of ports and file locations.

**Comment by t4sk** [comment]
@bryanvu 
"`npm run setup ...` should start up the App"

Reading the description, I think you meant to say
"`npm start --peerport=10019 --rpcport=10017 --datadir=test_lnd --logdir=test_lnd` should start up the App".

**Comment by diofeher** [comment]
Started to work on that.
