### ISSUE TITLE
iOS iPhone - Balance shows zero during initial sync

### ISSUE THREAD

**Issue by FontaineDenton** [lightninglabs/lightning-app#956]
### Description
Before blocks are fully synced I send a deposit to the wallet. The balance doesn't show until after full sync. I think this would be confusing to newbies.
### Steps to reproduce the behavior
Deposit testnet btc before sync is finished.
### Expected behavior
An API call to a third party block explorer so at least the balance shows up while syncing.
### Actual behavior
0 balance shown after sending btc to the wallet.

**Comment by tanx** [comment]
> Before blocks are fully synced I send a deposit to the wallet. The balance doesn't show until after full sync. I think this would be confusing to newbies.

Agreed. Which is why we display the loading screen for the initial sync. Maybe you didn't wait for the sync to finish and restarted the app?

**Comment by FontaineDenton** [comment]
Yes I closed the app before sync fully finished, assuming sync would keep going in the background. Once the sync completed the balance showed.

**Comment by tanx** [comment]
> Yes I closed the app before sync fully finished, assuming sync would keep going in the background. Once the sync completed the balance showed.

Cool. Ok closing this for now.
