### ISSUE TITLE
btcd cluster is sometimes overloaded

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#958]
This should probably be resolved by spinning up more instances:

![image1](https://user-images.githubusercontent.com/1374174/52546885-65394400-2df5-11e9-8eea-0fbc8c85291c.png)

**Comment by valentinewallace** [comment]
@tanx I think we can close this given that the underlying problem was that one of the cluster nodes was behind?

**Comment by tanx** [comment]
@valentinewallace ah cool. Thanks for checking 👍
