### ISSUE TITLE
app shows the close channel option for channels that are already closed

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/lightning-app#963]
The app shows the "close channel" option for channels that are already closed, or in the process of being closed: 

<img width="446" alt="screen shot 2019-02-10 at 1 26 58 am" src="https://user-images.githubusercontent.com/998190/52593791-b6016a80-2dfe-11e9-942b-b488d3c6e17e.png">

**Comment by alexbosworth** [comment]
Similar to https://github.com/lightninglabs/lightning-app/issues/912 ?

**Comment by tanx** [comment]
Yep. Duplicate of #912
