### ISSUE TITLE
Add memo/description to transaction detail page

### ISSUE THREAD

**Issue by cfromknecht** [lightninglabs/lightning-app#977]
Currently the transaction detail page displays invoice id (payment hash), date, amount, fee, and status. It would be great if it also showed the dsecription that's displayed when the payment is made so that userrs identify payments after the fact. For instance, if i make several small payments to y'alls, there's no indication as to which is which unless i remember exact amounts/order.

I saw that there was also an issue closed for expanding the transaction details page (#11), though that information seemed more specific to the nitty-gritty we are trying to abstract away. Since the memo is displayed during sends, to me it seems appropriate to also display it after. Lmk if I missed an open, related issue

**Comment by tanx** [comment]
So looking at the grpc api... `memo` is only an attribute for invoices created:

https://api.lightning.community/?javascript#invoice

There is currently no way to get a memo/description for payments sent:

https://api.lightning.community/?javascript#payment

Or am I missing something?

**Comment by cfromknecht** [comment]
@tanx you're correct, turns out we don't store the payment request that we were satisfying after successfully paying. I've modified the existing behavior to save the payment request on success in the this PR https://github.com/lightningnetwork/lnd/pull/2717

Once that's merged, we should be able to decode the payreq and display the memo on the details page :)

**Comment by cfromknecht** [comment]
@tanx https://github.com/lightningnetwork/lnd/pull/2717 has been merged! the `ListPayments` response should now include the payreq for all payments going forward :)

**Comment by tanx** [comment]
@cfromknecht nice! Will add this to ToDo.

**Comment by otech47** [comment]
I can take a stab at this

**Comment by tanx** [comment]
> I can take a stab at this

@otech47 awesome! thanks for the PR. Will review this asap.
