### ISSUE TITLE
Incorrect instructions in release page

### ISSUE THREAD

**Issue by Bosma** [lightninglabs/lightning-app#98]
### Description
https://github.com/lightninglabs/lightning-app/releases

> Once you have his PGP key you can verify the release (assuming manifest-v0.1.2-alpha.txt and manifest-v0.1.2-alpha.txt.gpg are in the current directory) with:
> 
> gpg --verify manifest-v0.1.2-alpha.txt.gpg

This is incorrect. manifest-v0.1.2-alpha.txt.gpg is not a detached signature, so it will not verify the manifest-v0.1.2-alpha.txt file.

Two fixes:
Create a detached signature for manifest-v0.1.2-alpha.txt by using `gpg --sign --detach-sig manifest-v0.1.2-alpha.txt` instead of `gpg --sign manifest-v0.1.2-alpha.txt`.

Alternatively, recommend that uses run `gpg --decrypt manifest-v0.1.2-alpha.txt` as it will show the signed data that is included in the gpg file. And delete the manifest-v0.1.2-alpha.txt file as it is not signed.

**Comment by Roasbeef** [comment]
Doh! The instructions for the prior release have been fixed, and also the latest release now has the proper instructions.
