### ISSUE TITLE
Disable navigating back (swipe left) on home screen and loading screen

### ISSUE THREAD

**Issue by tanx** [lightninglabs/lightning-app#981]
We should disable navigating back when it's not appropriate for the UI flow or when it can cause undesired side effects.

**Comment by tanx** [comment]
See: https://reactnavigation.org/docs/en/stack-actions.html#reset

**Comment by giulnz** [comment]
### Screenshot and/or logs if applicable
![e768a94e-c552-49fe-a823-2cd974b66f3b](https://user-images.githubusercontent.com/21366178/57455195-e1afb780-726a-11e9-926d-3c2d9935f3a1.jpg)
