### ISSUE TITLE
iOS autopilot network issues

### ISSUE THREAD

**Issue by Bombasarkadian** [lightninglabs/lightning-app#982]
### Description

It seems that lnd autopilot doesn't work reliably on iOS (iPhone X, iOS version `12.2`). After initial sync and wallet funding in version `0.0.14` no channels were automatically created. Logs reveal that device had issues with dns bootstrapping. There were different errors when connected to wifi and when using mobile network.

When running on wifi it will fail with "Unable to query bootstrapper (...): dial tcp 104.131.26.124:53: connect: connection refused". Also it seems that bootstrapping was retried constantly with no delay in-between (about once every 150ms).

When connecting with mobile network the error was "Unable to query bootstrapper (...): lookup soa.nodes.lightning.directory: no such host". Reconnection was retried after 30 seconds.

Restarting the app didn't seem to fix the issue. Only after I've reinstalled the app 3 times autopilot just started and showed no issues since.

There are no issues when running `lnd 0.5.2-beta` on Ubuntu connected to the same wifi network (dns servers: 176.103.130.130 and 176.103.130.131)

It seems like there was some issues with autopilot on iOS in the past #917, but they were resolved in previous versions.

### Steps to reproduce the behavior

- Install app
- Wait for the initial sync
- Fund wallet

### Expected behavior

Channels start to open automatically

### Actual behavior

No channels are opened and autopilot never finishes bootstrapping

### Screenshot and/or logs if applicable 

DNS response using wifi network (when mobile wallet couldn't sync):
```
~ dig test.nodes.lightning.directory SRV

; <<>> DiG 9.10.6 <<>> test.nodes.lightning.directory SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43891
;; flags: qr rd ra; QUERY: 1, ANSWER: 25, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;test.nodes.lightning.directory.	IN	SRV

;; ANSWER SECTION:
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qw5uxwckz5se8za0a9k56l8qcx5ene3cfv54w5p0zxujkqs9wmt8qvxvjtm.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1q0whnfhex3f5mq2knxuvsp0gzqmmf7d7j7nvyvjyayhkm8vzw247g9npe57.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1q0mtk6dwjaegtg59kjf5kha5ef059anml9csh0ag94u7syvdlnxnknpr5py.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 10009 ln1qdty6czlnhratcaynxzak0kecg5rqxhc9ctwzkymper36a7ncklmjn5eart.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1q0lpcfca53k6tnmr904cg4gugyqqvnvrpwyac3hcjagj8qpueyllxx9zaps.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qtgga9j7f48xl4gwl82w64jmaxj4sk5enrj0njfud7d0gws7y6ujwp4ea4v.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qf4ar7zdelp38uswk7vmmvf9hfqer8n596pmtevdrwck493el439k2legff.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qvdrg7x5sxuju0pgsypzsffgnrzlpkp0cng875sscne56j4626mkjd787c2.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qfnaycrpqkm35ezmjq530wzhptwpkphlwgfn4gaeckxjqdkae5c9uc2uxtt.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1q2lf85w668x2u7lw576zlrdul0d0knf5yv6uvqcjtm63sgqzjz69qg9cgse.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qg0guv362qtks4q09mkf86p7nj6q6mjgdtypzqk8kw8xpde6khr7yfhpcm5.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qv96c8tzk6pc547rq8t7qfz89xuknx5d4nlul00rtx4u9npqwqdr5hq3te6.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qdrlzn7xhkjj66unzvu9xd0md8h4z45sjqpt4qh8yvlrwzrsrjt2smu2g4d.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qd5z77f3r9z4jvnxf3anexfvqyvlpc8jxrh7zryjet6ny7c9mxrgyh2qj8y.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qwxruv486vwt05meqkqjfc4knwmyqkqtun8zp6myu0dgvjfz8ppawvfjce4.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qgkgweteunpv45vcz90ulu5vjgveq60a3fvm5f4kqschgjunkp0nwznl5ve.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qv8shunq4nda8mw2mpxhtz8v03wlgug7sln2yvqklxym35ayz3erq52gauc.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qd2dy8p57ewrg20wmnheapc6w2rqzwk4kfmj9gp82t3f5j5g3v8xyrkzaks.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qdv04yqkuh0qpghjkzk4rtj0v5529kau9kh96kdfetaxdak4us666k67wh9.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1q0n5lj6u2sw2ltszl7chw3njkw4muswykem5adyvmwzdp307vvuh55wlzg5.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qtjl2urw952j56kvvlryd2pmk8y50w82nzk37y3jwggnvynyrtwj530gs5a.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qguy047lg2wxal3uv2k8qknynwfvj8x5dfkrh6rlw3ssdp5uefve6wpslqw.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qgce6ygp7t66yh6955tq8p8w76vg7mnjjas9n4knfu8lkutee80fwqvsv33.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1q2ng38vae7vnm68gjcw0tdhfarjlwkepnw6wrfpwfwyvyzkxk2xazajdcc9.test.nodes.lightning.directory.
test.nodes.lightning.directory.	50 IN	SRV	10 10 9735 ln1qwyx8nu2hygyvgc02cwdtvuxe0lcxz06qt3lpsldzcdr46my5epmjr2pvg2.test.nodes.lightning.directory.

;; Query time: 55 msec
;; SERVER: 176.103.130.130#53(176.103.130.130)
;; WHEN: Mon Feb 18 00:19:28 CET 2019
;; MSG SIZE  rcvd: 2884
```

Issue when connected to wifi:
![img_4663](https://user-images.githubusercontent.com/2972266/52921228-2afc0500-3315-11e9-8515-0d07589c60b6.PNG)

Issue when connected to mobile network:
![img_4665](https://user-images.githubusercontent.com/2972266/52921229-2cc5c880-3315-11e9-96e5-5d10b674e640.PNG)

Successful connection after third reinstall:
![img_4667](https://user-images.githubusercontent.com/2972266/52921378-aa3e0880-3316-11e9-9369-6e153923f41e.PNG)

**Comment by Roasbeef** [comment]
The testnet DNS seed was down for a period of time, but it's up again now. That explains its inability to bootstrap.

**Comment by Bombasarkadian** [comment]
I guess it might have been it, as I haven't seen this issue anymore. Wouldn't it be a good idea to either add some indicator (so user know when there are network issues) or even better add more dns seed servers as a fallback?

**Comment by tanx** [comment]
> I guess it might have been it, as I haven't seen this issue anymore.

Cool. Closing for now.

> Wouldn't it be a good idea to either add some indicator (so user know when there are network issues) or even better add more dns seed servers as a fallback?

The hope is that we can move to mainnet after the desktop release. That should be a bit more reliable.
