### ISSUE TITLE
Windows client has "Syncing to Chain" even when caught up to chain tip

### ISSUE THREAD

**Issue by MidnightLightning** [lightninglabs/lightning-app#99]
### Description
Windows 64-bit OS, running v0.1.3.1 client application. The "Syncing to Chain" indicator in the lower-left never goes away, even after the log indicates it's fully caught-up.

```
lnd: 2017-12-03 23:15:12.627 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-12-03 23:15:32.614 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-12-03 23:15:52.614 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-12-03 23:16:12.618 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-12-03 23:16:22.855 [INF] BTCN: Processed 1 block in the last 8m52.05s (height 1253205, 2017-12-03 23:16:20 -0600 CST)
lnd: 2017-12-03 23:16:32.619 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-12-03 23:16:52.621 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-12-03 23:17:12.618 [INF] RPCS: [listchannels] fetched 0 channels from DB
```

### Steps to reproduce the behavior
This error happened after upgrading versions, and attempting to keep the wallet information from the previous client. Deleting the `%APPDATA/Local/Lnd/` folder and letting the new client re-create it, and then copy the `wallet.db` file from the old version into the new. Open client and the balance will be updated to show the old key's balance. Go to "Settings" tab. Verify that the blocks are being processed one-by-one and not in  big batches, indicating just new blocks being seen by the network as the chain grows, but the "Syncing to Chain" indicator still remains.

### Expected behavior
The "Syncing to Chain" indicator goes away

### Actual behavior
The "Syncing to Chain" indicator remains, and other UI actions like opening a channel are blocked because of it.

### Screenshot and/or logs if applicable
![Settings log](https://user-images.githubusercontent.com/250250/33537520-642d2196-d881-11e7-9ae1-d14ca12ab677.PNG)

**Comment by ghanavati27** [comment]
Same problem for me ,too.
Log of installed program v0.1.3.1 on my PC windows 10
lnd: 2017-12-04 18:58:20.042 [INF] BTCN: New valid peer 165.227.7.29:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)
lnd: 2017-12-04 18:58:20.248 [INF] BTCN: Syncing to block height 1253248 from peer 165.227.7.29:18333
lnd: 2017-12-04 18:58:20.491 [INF] LNWL: Opened wallet
lnd: 2017-12-04 18:58:21.734 [INF] LNWL: The wallet has been unlocked without a time limit 2017-12-04 18:58:21.735 [INF] LTND: LightningWallet opened 2017-12-04 18:58:21.925 [INF] LNWL: Started rescan from block 000000000be4729460cbcbfa65e8e0da05ee82c3026fed21ad6843a6f4b510cf (height 1231327) for 21 addresses
lnd: 2017-12-04 18:58:21.926 [INF] LNWL: Catching up block hashes to height 1231327, this might take a while
lnd: 2017-12-04 18:58:22.045 [INF] LNWL: Done catching up block hashes 2017-12-04 18:58:22.045 [INF] LNWL: Finished rescan for 21 addresses (synced to block 000000000be4729460cbcbfa65e8e0da05ee82c3026fed21ad6843a6f4b510cf, height 1231327)
lnd Error: no active channels exist


And also install version v0.1.3.1 on my server win server 2012R2
lnd: 2017-12-04 03:00:12.538 [WRN] LTND: open ../lnd.conf: The system cannot find the file specified. 2017-12-04 03:00:12.539 [INF] LTND: Version 0.3.0-alpha 2017-12-04 03:00:12.540 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0 2017-12-04 03:00:12.557 [INF] LTND: Primary chain is set to: bitcoin 2017-12-04 03:00:12.591 [INF] BTCN: Loaded 1049 addresses from file 'C:\Users\Administrator\AppData\Local\Lnd\data\testnet3\bitcoin\peers.json' 2017-12-04 03:00:12.592 [INF] CMGR: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org: no such host 2017-12-04 03:00:12.592 [INF] CMGR: DNS discovery failed on seed x49.testnet-seed.bitcoin.jonasschnelli.ch: lookup x49.testnet-seed.bitcoin.jonasschnelli.ch: no such host 2017-12-04 03:00:12.624 [INF] CMGR: 50 addresses found from DNS seed testnet-seed.bitcoin.schildbach.de 2017-12-04 03:00:12.780 [INF] CMGR: 3 addresses found from DNS seed testnet-seed.bluematt.me
lnd: 2017-12-04 03:00:12.906 [INF] BTCN: New valid peer 165.227.7.29:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)
lnd: 2017-12-04 03:00:12.942 [INF] BTCN: Catching up regular filter headers from 1231741 to 1233741 2017-12-04 03:00:12.942 [INF] BTCN: Catching up extended filter headers from 1231741 to 1233741
lnd: 2017-12-04 03:00:12.956 [INF] BTCN: Syncing to block height 1253248 from peer 165.227.7.29:18333
lnd: 2017-12-04 03:00:14.360 [INF] LNWL: Opened wallet
lnd: 2017-12-04 03:00:12.538 [WRN] LTND: open ../lnd.conf: The system cannot find the file specified. 2017-12-04 03:00:12.539 [INF] LTND: Version 0.3.0-alpha 2017-12-04 03:00:12.540 [INF] CHDB: Checking for schema update: latest_version=0, db_version=0 2017-12-04 03:00:12.557 [INF] LTND: Primary chain is set to: bitcoin 2017-12-04 03:00:12.591 [INF] BTCN: Loaded 1049 addresses from file 'C:\Users\Administrator\AppData\Local\Lnd\data\testnet3\bitcoin\peers.json' 2017-12-04 03:00:12.592 [INF] CMGR: DNS discovery failed on seed x49.seed.tbtc.petertodd.org: lookup x49.seed.tbtc.petertodd.org: no such host 2017-12-04 03:00:12.592 [INF] CMGR: DNS discovery failed on seed x49.testnet-seed.bitcoin.jonasschnelli.ch: lookup x49.testnet-seed.bitcoin.jonasschnelli.ch: no such host 2017-12-04 03:00:12.624 [INF] CMGR: 50 addresses found from DNS seed testnet-seed.bitcoin.schildbach.de 2017-12-04 03:00:12.780 [INF] CMGR: 3 addresses found from DNS seed testnet-seed.bluematt.me
lnd: 2017-12-04 03:00:12.906 [INF] BTCN: New valid peer 165.227.7.29:18333 (outbound) (/btcwire:0.5.0/btcd:0.12.0/)
lnd: 2017-12-04 03:00:12.942 [INF] BTCN: Catching up regular filter headers from 1231741 to 1233741 2017-12-04 03:00:12.942 [INF] BTCN: Catching up extended filter headers from 1231741 to 1233741
lnd: 2017-12-04 03:00:12.956 [INF] BTCN: Syncing to block height 1253248 from peer 165.227.7.29:18333
lnd: 2017-12-04 03:00:14.360 [INF] LNWL: Opened wallet
lnd: 2017-12-04 03:00:16.662 [INF] LNWL: The wallet has been unlocked without a time limit
lnd: 2017-12-04 03:00:16.677 [INF] LTND: LightningWallet opened
lnd: 2017-12-04 03:00:16.685 [INF] LNWL: Started rescan from block 0000000005c2d3ca4c9f4c517e02d7e142d761c4dc438e379b34b0801d2e17ac (height 1231241) for 35 addresses 2017-12-04 03:00:16.686 [INF] LNWL: Catching up block hashes to height 1231242, this might take a while
lnd Error: no active channels exist

**Comment by Roasbeef** [comment]
Both instances: were you running prior versions of the app on the same system? If so, which version? Two versions ago the filter format used by `neutrino` was modified, so users needed to clear out their old application data before updating.

**Comment by MidnightLightning** [comment]
I had 0.1.2.1 installed, and after downloading the new version, the new one wouldn't start up (some error about the database already open). I moved the `%APPDATA` `Lnd` folder, started the 0.1.3.1 one, let it recreate the `Lnd` folder, and then quit it, copied my `wallet.dat` file into the new `Lnd` folder and restarted the app. After finishing syncing, it never got rid of the "Syncing to chain" message, even after multiple application restarts.

**Comment by ghanavati27** [comment]
I deleted lnd folder in APPDATA and problem has been fixed.
Now program working very well with new wallet

**Comment by ghanavati27** [comment]
I created a channel from my PC to my server. 
Channel is confirmed and open.
I created a payment request in my server and try to pay it with my PC , but i getting this error
"Payment route failure"

Also, i created another channel with eclair node .
03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134@endurance.acinq.co:9735
My channel with them is confirmed and open.
But still when i trying to pay my order in https://starblocks.acinq.co , i getting error "Payment route failure" .
Am i wrong  or something else ?

**Comment by Roasbeef** [comment]
Pinging their node, I get no response, and are also unable to connect directly. Possibly something is wrong on their end:
```
⛰  ping endurance.acinq.co
PING endurance.acinq.co (34.250.234.192): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
```

**Comment by ghanavati27** [comment]
They blocked ping . but their node working. i create 2 channels from my PC and my server with them.
Both channels are confirmed and opened.
But please forget eclair problems . why i getting error when i want pay from my pc channel to my server ?

**Comment by Roasbeef** [comment]
Do you have the logs from the payment attempt? What `lnd` commit is your server node running on? Is the channel shown as "active" in the UI?

**Comment by ghanavati27** [comment]
Is the channel shown as "active" in the UI?
No , it shown "OPEN"

**Comment by Roasbeef** [comment]
I see, it must show "active" in the UI, otherwise it isn't available for sending. Do you the logs of the node on your PC you can send me? Also do you know what commit the `lnd` node on your server is running on?

**Comment by ghanavati27** [comment]
I use lightning-app v0.1.3.1-alpha in my PC and also my server.
I don't know what commit the lnd node .....
my PC lnd log attached.
[lnd.zip](https://github.com/lightninglabs/lightning-app/files/1529650/lnd.zip)

**Comment by Roasbeef** [comment]
```
2017-12-05 11:46:08.887 [ERR] SRVR: unable to send message to 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134, peer not found
2017-12-05 11:46:08.887 [WRN] FNDG: unable to send fundingLocked to peer 03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134: unable to find peer. Will retry when online
```

The final step to complete channel opening is sending this `FundingLocked` message. The server (or either side) wasn't able to send it. The channel isn't usable until this is sent. Which node funded the channel?

**Comment by ghanavati27** [comment]
my PC funded

**Comment by ghanavati27** [comment]
03933884aaf1d6b108397e5efe5c86bcf2d8ca8d2f700eda99db9214fc2712b134 is Eclair node.
my server node is 02c87e2edf5b781ea69d183d748fd22c2724e4ffe1ae34f0f6dd38b9128671b1d2
my pc node is 02d06b42d9fad1fc12d9c10ce7057c88ba3cf103e0117f6c65865b2f478e1985b3

**Comment by Roasbeef** [comment]
Ah there's a (known) bug atm where the funder won't reconnect to the fundee unless it's restarted in the event that the connection dies. The internal logic _should_ resend upon reconnection. Eclair wont' send the `FundingLocked` message until 6 blocks have gone past confirmation.

**Comment by ghanavati27** [comment]
I funded a channel by my PC to my server .
Why this channel can't be activate?
Why my server won't send FundingLocked also ?

**Comment by Roasbeef** [comment]
FWIW, I'm also unable to pay to Starblocks over my existing channel. I think maybe they're doing some maintenance on the node.

**Comment by Roasbeef** [comment]
Both of the peers need to be connected for the `FundingLocked` to be sent. Looking at your logs, they aren't connected. Is your PC behind a NAT?

**Comment by ghanavati27** [comment]
humm, i think so.
I using my mobile internet hotspot and sharing it for my PC.
so my ip remapped ?
Maybe this is my problem !!!

**Comment by Roasbeef** [comment]
Possibly, this issue tracks our progress with NAT traversal: https://github.com/lightningnetwork/lnd/issues/185

**Comment by ghanavati27** [comment]
I will install lightning-app in another server and open new channel between 2 servers.
Both servers are not behind NAT.

**Comment by Roasbeef** [comment]
A better place (as this isn't at all related to this issue) to continue this conversation would be on our developer/test slack: https://join.slack.com/t/lightningcommunity/shared_invite/MjI4OTg3MzQ4MjI2LTE1MDMxNzM1NTMtNjlmOGYzOTI1Ng

If you use IRC, we're also on `#lnd` on Freenode.

**Comment by ghanavati27** [comment]
Ok Roasbeef , i will join there.
Thank you for spending your time in this conversation.

**Comment by MidnightLightning** [comment]
I deleted my `%APPDATA/Local/Lnd/` folder again and restarted the application, and let the client sync the whole blockchain. It did properly turn off the "Syncing to Chain" indicator that time. I then closed the client, and replaced the `wallet.dat` file with my original one, to restore the testnet funds I already had. But upon starting the client back up again, the "Syncing to  Chain" indicator was back, and it remained there. The wallet did indicate it was using my original account (and showed that account's balance), though. Is there some other way I should restore my private key that doesn't break the "am I done with the Sync" logic of the client?

**Comment by bryanvu** [comment]
@MidnightLightning same comment about this being better discussed on the Slack, but at this point, we don't have a way to export the seed/private key from the wallet (we're working on it), so it's easier to just get more testnet funds from a faucet or send your testnet funds to another wallet before upgrading, and then sending the funds back.

**Comment by MidnightLightning** [comment]
So, you can't simply copy `wallet.db` files from one installation into another? I had thought they were akin to `wallet.dat` files, but looks like they're not; they aren't actually text files.

So, this seems to be a bug that if the `wallet.db` file is incorrect/corrupted in this way, the application properly lists the balance of the private keys in the wallet, but doesn't give any other sort of error (if you don't support that feature, at least having an error message indicating that's the problem would be nice).

**Comment by scaleToTheFuture** [comment]
i've got the same issue: syncing never stops even though it has long reached end of blockchain
lnd: 2017-12-10 07:13:52.120 [INF] BTCN: Processed 1 block in the last 5m4.89s (height 1254376, 2017-12-10 07:12:50 +0100 CET)
using version 0.1.3.1 on windows

**Comment by iamparkerm** [comment]
I deleted the previous install, deleted the entire /Lnd folder in C:\Users\username\AppData\Local\Lnd, restarted my windows machine, then re-synced and it worked.
